### ISSUE TITLE
Retry operation completed toast notification doesn't automatically disappear

### ISSUE THREAD

**Issue by mauroservienti** [Particular/ServicePulse#1054]
When retrying a message a toast notification is displayed to report the retry status. I expect a toast notification to automatically disappear after a while, or at least if I move to a different page than the failed messages one. Instead, it's easy to end up in a situation like the following:

![image](https://user-images.githubusercontent.com/1325611/117816544-ea2a9680-b266-11eb-8b22-f69012bab538.png)

**Comment by aleksandr-samila** [comment]
Fixed by: https://github.com/Particular/ServicePulse/pull/1059
