### ISSUE TITLE
Email notifications don't allow multiple recipients

### ISSUE THREAD

**Issue by kbaley** [Particular/ServicePulse#1079]
When configuring health check email notifications, only one email address is allowed. When you try to enter more than one (separated by a comma or semi-colon) and click Save, there's no error message and the dialog stays up.

***************

*Technical information if reporting a bug:*

- ServicePulse 1.30.0
- ServiceControl 4.18.0

**Comment by kbaley** [comment]
I've labeled this as a bug primarily because the dialog doesn't give an indication that there is anything wrong.

**Comment by kbaley** [comment]
When implemented, there should be some help text to indicate how to add multiple email addresses. E.g.

> Separate multiple email address with a comma. E.g. jack@skellington.com,oogie@boogie.com

**Comment by soujay** [comment]
Will be released in 1.36.5

**Comment by soujay** [comment]
The bug has been fixed in ServicePulse 1.37.0 and has been released.
https://github.com/Particular/ServicePulse/releases/tag/1.37.0
