### ISSUE TITLE
Unsupported Service Control Version on Firefox

### ISSUE THREAD

**Issue by kylejuliandev** [Particular/ServicePulse#1164]
Hi,

I recently installed Service Pulse (v1.31.1) locally to explore the metrics, monitoring, and other tooling that is available. Upon installation, I am greeted with an `Unsupported Service Control Version` error page. I am using Firefox to access `http://localhost:9090/#/dashboard`

![Unsupported Service Control Version](https://user-images.githubusercontent.com/38759683/158172414-9c35189b-660d-4906-aba9-86dc749ce450.png)

From the Developer console in the Browser I see the following:

<details>

<summary>Console Log Stack trace</summary>

```
TypeError: currentVersion is null
    isUpgradeAvailable services.semver.js:29
    checkVersions app.controller.js:152
    Angular 22
    getReleases services.platform-update.js:15
    getReleases services.platform-update.js:14
    checkVersions app.controller.js:140
    controller app.controller.js:189
    handler factory.notifier.js:12
    $emit Angular
    notify factory.notifier.js:19
    ConnectionsStatus connectionsStatus.js:17
    handler factory.notifier.js:12
    $emit Angular
    notify factory.notifier.js:19
    controller app.controller.js:284
    handler factory.notifier.js:12
    $emit Angular
    notify factory.notifier.js:19
    connectToSignalR factory.listener.js:48
    jQuery 7
 Possibly unhandled rejection: {} angular.js:15635
```
</details>

Weirdly enough, when I open this page on Edge (99.0.1150.39) everything loads as expected.

***************

*Technical information if reporting a bug:*

- **ServicePulse version: 1.31.1** 
- **ServiceControl version:  4.21.8** 
- **Browser version: Firefox 98.0**

**Comment by WojcikMike** [comment]
Hi @kylejuliandev, as stated on the other issue, this looks like a support question which is best addressed through our [support channels](https://particular.net/support) or [discuss forums](https://discuss.particular.net/). I think it can be related to the other issue that you created, and recreating the index would make this go away.

**Comment by WojcikMike** [comment]
Closing as this seems like a support issue
