### ISSUE TITLE
MESSAGE BODY json formatting

### ISSUE THREAD

**Issue by bruusi** [Particular/ServicePulse#1194]
Describe your problem / suggestion / idea / feedback here.

Upgraded to new version and the formatting of JSON seems to be escaped.

Technical information if reporting a bug:

- ServicePulse v1.31.2
- Service Control:  v4.21.8
- Latest Chrome 

![Escaped format json message](https://user-images.githubusercontent.com/1063126/166870070-9f05f2b0-4829-4698-b9ee-b1c6e78fcc3f.PNG)

**Comment by bruusi** [comment]
NServiceBus.ContentType is set to "application/json"

**Comment by boblangley** [comment]
@bruusi I wanted to let you know we will look into this shortly. In the meantime, it may be a good idea to submit a support ticket to us as well (support@particular.net).

**Comment by WilliamBZA** [comment]
I'm on it @bruusi. A fix should be out in a little bit.

**Comment by WilliamBZA** [comment]
@bruusi [1.31.3](https://github.com/Particular/ServicePulse/releases/tag/1.31.3) has been released to fix this.
