### ISSUE TITLE
NServiceBus Governance - Central place to view all published message types

### ISSUE THREAD

**Issue by fafachd** [Particular/ServicePulse#124]
I get asked this question a lot: With NServiceBus, is there a central place where a business can see a list of the types of message each service publishes?

It would be fantastic if ServicePulse showed a list of IEvents published by each service, perhaps with drill-in details showing field names and field types. This would be very helpful in selling NServiceBus as well.

Thoughts?

Thanks,
Danny

**Comment by fafachd** [comment]
Any update on this? This would be an awesome selling point!

It seems like it would be really easy for each endpoint to send a list of events they publish and commands they handle to the configured audit queue, and have SC save the information and expose it through the REST API, or also on SP.

**Comment by andreasohlund** [comment]
@fafachd not exactly what you asked for but ServicePulse now shows metrics for individual message types.

https://docs.particular.net/monitoring/metrics/in-servicepulse

Would that cover you needs or would seeing the actual properties important?
