### ISSUE TITLE
Enable ServicePulse to manage multiple ServiceControl installations

### ISSUE THREAD

**Issue by helenktsai** [Particular/ServicePulse#1242]
*Issue transferred from internal repo*

Currently, each ServiceControl installation needs a dedicated ServicePulse installation. It would be helpful to be able to connect a single ServicePulse installation to multiple ServiceControl installations.

**Comment by janv8000** [comment]
For anyone reading this, there is a documented _workaround_:

https://docs.particular.net/servicepulse/host-config#configuring-connections-via-the-servicepulse-ui

> In order to use the query string to specify a ServiceControl instance that ServicePulse should connect to, the browser URL should be of the format:

> http://localhost:9090/?scu=http://qacontrol:33333/api/&mu=http://qamonitoring:33633/#/

> The query string parameter for scu= is the URL representation of the ServiceControl API url, and the query string paramater mu= is the URL of the ServiceControl Monitoring server. In the example above, ServicePulse is connecting to the ServiceControl instance at http://qacontrol:33333/api/ and connecting to a ServiceControl Monitoring instance at http://qamonitoring:33633/. By providing these connection details in the URL, a browser bookmark or desktop shortcut can be created to instantly open ServicePulse with those connection details or easily share them with other people.

**Comment by DavidBoike** [comment]
I'd call that more than a workaround, that's explicitly what we built to solve this problem. :wink:

I think this is just a case of a case that should have been closed when we built the feature.
