### ISSUE TITLE
Improve management around decommissioning of resources

### ISSUE THREAD

**Issue by helenktsai** [Particular/ServicePulse#1250]
*Issue transferred from internal repo*

For systems that rely on frequent spinning up/down of endpoints, e.g. in cloud environments, handling the decommissioning of endpoint instances can be problematic since there is no comprehensive way for managing the decommissioning. Users may need to have endpoints removed automatically from logs or SP monitoring/heartbeats lists or automatically run specific tasks when an endpoint is shutdown.

**Comment by johnsimons** [comment]
Support for elastic scaled endpoints has been added recently, see https://docs.particular.net/monitoring/heartbeats/in-servicepulse#configuration-do-not-track-instances 
Endpoint instances can also be deleted manually, see https://docs.particular.net/monitoring/heartbeats/in-servicepulse#instances-removing-endpoint-instances
