### ISSUE TITLE
Update monitoring for elastic scale environments

### ISSUE THREAD

**Issue by helenktsai** [Particular/ServicePulse#1257]
Currently, monitoring focuses on physical instances being up or down. In an elastic scale environment, where you typically don't own the physical infrastructure, specific physical instances are no longer relevant. Instead, the focus should be on a minimum (or maximum) number of physical instances of each logical endpoint running. In other words, if a physical instance goes offline but another one replaces it, the fact that this is a different physical instance is irrelevant, as long as the total number of physical instances remains stable over time.

Additionally, because individual physical instances are tracked, scaled down instances are treated as dead (not heartbeating) and there is currently no way to remove those instances as it is assumed that they will eventually be coming back online.

**Comment by cjoergensen** [comment]
We are experiencing exactly what you are describing. We are hosting our endpoints in Kubernetes and are scaling these up and down using KEDA. When there no workloads the number of instances goes to zero and new instances are spawned when needed.

This breaks the instances view in ServicePulse:
![image](https://user-images.githubusercontent.com/8087733/200610009-13e4bec3-1c58-4e1a-b52d-53a44eeef2d5.png)

A solution to this could be two tabs that shows active and passive instance and have an option to purge all passive.

**Comment by WojcikMike** [comment]
Thanks, @cjoergensen for this information. We will see how we can make this situation better.

**Comment by ramonsmits** [comment]
It is related to the following issue that existing long before this one was created:

- https://github.com/Particular/ServicePulse/issues/468

**Comment by WilliamBZA** [comment]
[I spiked a way](https://github.com/Particular/ServiceControl/pull/3546) to achieve this using a new setting. The code uses a background task to check once an hour if there are any instances that are staler than the threshold. If they are staler than the threshold, they get removed. The spike wasn't completed but can be used as a reference point in the future.

**Comment by PhilBastian** [comment]
Hi @cjoergensen and everyone tracking this issue
ServicePulse 1.42.1 and ServiceControl 5.9.1 have addressed this issue, by allowing elastic scale environments to be marked as such, which is then treated differently on the heartbeats screen. Monitoring for offline endpoints now goes away automatically after 1 hour for all endpoint types.

For more information you can see the [updated documentation](https://docs.particular.net/monitoring/heartbeats/in-servicepulse)

**Comment by cjoergensen** [comment]
> Hi @cjoergensen and everyone tracking this issue ServicePulse 1.42.1 and ServiceControl 5.9.1 have addressed this issue, by allowing elastic scale environments to be marked as such, which is then treated differently on the heartbeats screen. Monitoring for offline endpoints now goes away automatically after 1 hour for all endpoint types.
> 
> For more information you can see the [updated documentation](https://docs.particular.net/monitoring/heartbeats/in-servicepulse)

That great! Thanks for the update.
