### ISSUE TITLE
Timespan sparkline values show 'Invalid date' when displaying HR unit values

### ISSUE THREAD

**Issue by saschanm** [Particular/ServicePulse#1262]
After upgrade from 1.31.1 to 1.32.1 sparkline values (critical time, processing time etc.) are now displaying **Invalid date** when values resolve to HR unit.
![image](https://user-images.githubusercontent.com/2804274/181864246-4e4e95c3-9795-43d5-b4c1-397ef3775827.png)

- **ServicePulse version: 1.32.1** 
- **ServiceControl version:  v4.22.0** 
- **Browser version: Chrome 103.0.5060.134**

**Comment by cquirosj** [comment]
@saschanm thanks for reporting this. Could you please confirm if you took the screenshot from the instances tab like in the following screenshot or from somewhere else? 
<img width="1400" alt="image" src="https://user-images.githubusercontent.com/545695/182418316-f8d15dec-81a3-41d8-b3f3-200d22d58fce.png">

**Comment by saschanm** [comment]
> @saschanm thanks for reporting this. Could you please confirm if you took the screenshot from the instances tab like in the following screenshot or from somewhere else? <img alt="image" width="1400" src="https://user-images.githubusercontent.com/545695/182418316-f8d15dec-81a3-41d8-b3f3-200d22d58fce.png">

Apologies.

My screenshot was from the root 'Monitoring' tab. As I have reverted to older version I can not confirm if the same issue is repeated on the endpoint drilldowns.

**Comment by cquirosj** [comment]
@saschanm thanks again for reporting and for the additional information. We are routing this to the appropriate team to get it fixed.

**Comment by HEskandari** [comment]
I verified the issue, which happens occasionally, using [Monitoring demo](https://docs.particular.net/tutorials/monitoring-demo/).

**Comment by cquirosj** [comment]
A fix will be shipped with release 1.32.3

**Comment by saschanm** [comment]
Fix is not quite right still - though it is workable enough that I have not rolled back this time.

Problem is HR unit is used once time reached 1 minute, but it displays **1 HR**.
See below screenshot, all of these are actually critical time 24 mins, 2mins, 1min etc...

Previous implementation would display, for example, 24mins as **00:24 HR**, which probably explains the bug.

![image](https://user-images.githubusercontent.com/2804274/184053604-1fa85f1e-72c7-415d-87f5-ee70514f674b.png)

**Comment by cquirosj** [comment]
@saschanm thanks for reporting this. I will open a new with the information you provided.

**Comment by saschanm** [comment]
> @saschanm bug #[1271](https://github.com/Particular/ServicePulse/issues/1271) was opened with the information you provided. A fix will be shipped in version 1.32.4. Thanks again.

Thanks for the quick turnaround.
