### ISSUE TITLE
JSON message body isn't prettified

### ISSUE THREAD

**Issue by johannwalder** [Particular/ServicePulse#1269]
Similar issue has been fixed in version 1.31.3 but now with version 1.32.2 we are back at the same problem. The JSON body isn't prettified because of the newly added condition to check the content type. At least for our systems, the default **NServiceBus.ContentType** header is **application/json** and not **text/json**. And therefore the body will not be prettified and longer. 

Thank you!

***************

*Technical information if reporting a bug:*

- **ServicePulse version:** 1.32.2
- **ServiceControl version:** 4.23.0
- **Browser version:** any

**Comment by soujay** [comment]
Thank you for letting us know about this bug. We have added it to our backlog and will let you know once the updated version is released.

**Comment by cquirosj** [comment]
This will be shipped in version 1.32.4
