### ISSUE TITLE
Unable to read the Dead Letter Queue length when open the CustomCheck tab

### ISSUE THREAD

**Issue by TC-xHuang** [Particular/ServicePulse#1340]
Got an error message in CustomCheck when installed the ServicePulse:

Unable to read the Dead Letter Queue length. The performance counter with category 'MSMQ Queue' and name 'Messages in Queue' and instance name 'Computer Queues' is not available. It is possible that the counter category, name and instance name have been localized into different languages. Consider overriding the counter category, name and instance name in the application configuration file by adding:

```xml
   <appSettings>
     <add key="ServiceControl/Msmq/PerformanceCounterCategoryName" value="LocalizedCategoryName" />
     <add key="ServiceControl/Msmq/PerformanceCounterName" value="LocalizedCounterName" />
     <add key="ServiceControl/Msmq/PerformanceCounterInstanceName" value="LocalizedCounterInstanceName" />
   </appSettings>
```

***************

*Technical information if reporting a bug:*

- **ServicePulse version:** 1.15.0, and 1.33.1
- **ServiceControl version:** 4.16.0
- **Browser version:** Chrome 107.0.5304.123

**Comment by tmasternak** [comment]
Hi @TC-xHuang,

it looks like you are running on a non-English operating system and the counter names have been localized. You can provide correct (localized) names by adding the following lines to the `ServiceControl.exe.config` file in the installation path of ServiceControl:

``` xml
<appSettings>
   <add key="ServiceControl/Msmq/PerformanceCounterCategoryName" value="MSMQ Queue" />
   <add key="ServiceControl/Msmq/PerformanceCounterName" value="Messages in Queue" />
   <add key="ServiceControl/Msmq/PerformanceCounterInstanceName" value="Computer Queues" />
</appSettings>
``` 

Please note that in the snippet above you need to change "MSMQ Queue", "Messages in Queue" and "Computer Queues" to proper localized versions. You can find the names using one of [the monitoring tools](https://learn.microsoft.com/en-us/windows/win32/perfctrs/performance-counters-tools?source=recommendations#data-collection-tools) e.g. PerfMon.exe that is pre-installed on Windows.

**Comment by TC-xHuang** [comment]
Got it, thank you @tmasternak
