### ISSUE TITLE
It's not possible to disable ServiceControl Monitoring 

### ISSUE THREAD

**Issue by tmasternak** [Particular/ServicePulse#1362]
Providing "!" as the value for ServiceControl Monitoring in the Configuration should result in ServicePulse not trying to connect to the monitoring endpoint, and not showing any errors. 

## Root cause
It looks that before making any request the code [checks if the monitoring endpoint URL is "!"](https://github.com/Particular/ServicePulse/blob/master/src/ServicePulse.Host/vue/src/composables/serviceServiceControlUrls.js#L14) and if that is the case `null` is returned as the response of the remote call. That in case causes an [exception to be thrown](https://github.com/Particular/ServicePulse/blob/master/src/ServicePulse.Host/vue/src/composables/serviceServiceControl.js#L405) - which should probably treat this case as an empty response instead.

**Comment by ramonsmits** [comment]
It works here when changing the setting but it isn't durable. Re-opening SP fails and shows the "old" value. I would think validation isn't allowing `!` somewhere.

**Comment by WilliamBZA** [comment]
@ramonsmits when you say "Re-opening", do you mean refreshing the page? Or new browser window?

I've tried in firefox and chrome and wasn't able to reproduce it showing the old value.

**Comment by ramonsmits** [comment]
Tested it again (SP v1.37.1), and now it is durable between restarts on Brave v1.62.153 (Jan 25, 2024)

https://youtu.be/IrNmfgNxisM

btw, also tested this with Edge 121.0.2277.83 (Official build) (64-bit)

**Comment by adamralph** [comment]
I tested the latest SC and SP on an old Windows machine and it worked perfectly across SP restarts. It looks like the bug no longer exists.
