### ISSUE TITLE
ServicePulse in IIS with TLS not working as expected

### ISSUE THREAD

**Issue by papauorg** [Particular/ServicePulse#1364]
Hello,

I just installed ServiceControl, Monitoring and ServicePulse on a VM. My goal is to publish the ServicePulse website to our internal network over https and with windows authentication so I followed this guide: https://docs.particular.net/servicepulse/install-servicepulse-in-iis

Unfortunately I can't get the ServicePulse site to properly connect with ServiceControl and the Monitoring instance. To me it seems like there is a problem with the redirect rules.

I saw that there was an update to ServicePulse recently that had some changes in the redirects that must be configured in IIS. https://discuss.particular.net/t/servicepulse-1-33-1-minor-release-available/3289 This is the version I installed and also used the described redirect.

So what are the circumstances:

- ServicePulse is available under the inteded URL (tested locally via https://localhost/), but the connection to ServiceControl and Monitoring does not work:
![ServicePulse and Monitoring connection](https://user-images.githubusercontent.com/2471424/215473204-82d1e92a-4c61-40a0-9235-93a5af0b42d9.png)

- ServiceControl api is available via the redirect when calling it directly in the browser:
![Service Control API call](https://user-images.githubusercontent.com/2471424/215473384-a8fbcc08-1753-42c0-965c-a3411512bd7f.png)

- Monitoring service is available when calling it directly in the browser:
![Monitoring service API call](https://user-images.githubusercontent.com/2471424/215473442-a9cb5789-0bab-41db-9bca-609fdefffb4f.png)

- When configuring the monitoring and api endpoints in ServicePulse according to the documentation (without trailing slash) there seems to be a missing "/" in the requests
![Missing slash](https://user-images.githubusercontent.com/2471424/215473521-fc1ea488-7bbc-4f83-80a2-b90294cfcaf8.png)

- When configuring the monitoring and api endpoints with trailing slash the requests will end in an 200 - OK BUT with html content:
![HTML response](https://user-images.githubusercontent.com/2471424/215473583-4bbc9914-566f-4cf3-86c5-89823dd16785.png)

I don't know if and what I did wrong here. Can you please give me some guidance?

Thank you and best regards,
Philipp

***************

*Technical information if reporting a bug:*

- **ServicePulse version:** v1.33.1
- **ServiceControl version:** v4.27.6
- **Browser version:** Mozilla Firefox 109

**Comment by DavidBoike** [comment]
We've been investigating, and although we don't know a lot just yet, we think there might be an issue with ServicePulse version 1.33.1. In the meantime, does this work out for you if you downgrade to [version 1.32.4](https://github.com/Particular/ServicePulse/releases/tag/1.32.4)?

**Comment by tmasternak** [comment]
Hi @papauorg,

it looks that our documentation does not match the configuration needed for version `1.33.1+`. Could you try using the following setup:

1. Remove `api` and `monitoring` subfolders in your IIS site
2. Use the following as `web.config` in the root folder of your site

```xml
<?xml version="1.0" encoding="UTF-8"?>
<configuration>
  <system.webServer>
    <rewrite>
      <rules>
       <rule name="Rewrite monitoring api url" stopProcessing="true">
            <match url="^monitoring/(.*)" />
            <action type="Rewrite" url="http://localhost:33633/{R:1}" />
        </rule>
        <rule name="Rewrite main instance api url" stopProcessing="true">
            <match url="^api/(.*)" />
            <action type="Rewrite" url="http://localhost:33333/api/{R:1}" />
        </rule>
        <rule name="Handle app.constants.js requests from AngularJs" stopProcessing="true">
          <match url="^a/js/app.constants.js(.*)" />
          <action type="Rewrite" url="/js/app.constants.js{R:1}" />
        </rule>
        <rule name="Handle Vue.js routing paths" stopProcessing="true">
          <match url="(.*)" />
          <conditions logicalGrouping="MatchAll">
            <add input="{REQUEST_FILENAME}" matchType="IsFile" negate="true" />
            <add input="{REQUEST_FILENAME}" matchType="IsDirectory" negate="true" />
          </conditions>
          <action type="Rewrite" url="/" />
        </rule>
      </rules>
    </rewrite>
  </system.webServer>
</configuration>
```

3. Use `api/` and `monitoring/` as the API URL in the ServicePulse configuration
4. Make sure to [clear your browser cache](https://support.piktochart.com/article/243-clear-browser-cache)

**Comment by tmasternak** [comment]
I also made changes to the doco page https://github.com/Particular/docs.particular.net/pull/5992

**Comment by papauorg** [comment]
>In the meantime, does this work out for you if you downgrade to [version 1.32.4](https://github.com/Particular/ServicePulse/releases/tag/1.32.4)?

@DavidBoike I used the approach with the changed web.config, see below. Thanks for your answer!

> it looks that our documentation does not match the configuration needed for version `1.33.1+`. Could you try using the following setup:

@tmasternak I just tried your approach. Seems like it's working fine so far. Thanks!
