### ISSUE TITLE
Change ServicePulse error number display to show 10+ if 10 or more retry attempts

### ISSUE THREAD

**Issue by jpalac** [Particular/ServicePulse#1366]
As part of [a platform stability enhancement](https://github.com/Particular/GeneralPlatformExperience/issues/2444 ) we have modified the [number of retry attempts](https://github.com/Particular/ServiceControl/pull/3372) stored in RavenDB to a max number of 10.

The number of retries is shown on the SP dashboard next to each error. With the SC change above, the number will always be 10 if the retry is 10 or more which may be confusing for the user. We should adjust the display to say something like "10+" if the number of retry attempts returned from SC is 10 so that the user knows it could be 10 or more.

**Comment by WilliamBZA** [comment]
Will be released in 1.34.0
