### ISSUE TITLE
Subfolder deployments do not work

### ISSUE THREAD

**Issue by tmasternak** [Particular/ServicePulse#1375]
There is no way to deploy ServicePulse in a subfolder e.g. `https:\\somedomain.com\subfolder`. In order to host multiple ServicePulse under one domain separate subdomains need to be used e.g. `https:\\prod.domain.com`, `https:\\stagging.domain.com` etc. 

It seems that with VueJs a subfolder deployment option [needs to be specified during build time](https://stackoverflow.com/questions/43879418/deploy-vuejs-app-in-a-subdirectory). As a result, users requiring such a deployment might be required to build from the sources.

**Comment by yogeshbissessur** [comment]
Hi,

we are also experiencing the same problem with our setup, is there a workaround or fixed for this?

**Comment by tmasternak** [comment]
Hi @yogeshbissessur,

they only approach we can recommend for now is to use a subdomain instead of a subfolder.

**Comment by WilliamBZA** [comment]
This will be fixed in 1.34.0. Hopefully it will be released soon.

**Comment by WilliamBZA** [comment]
Changes merged to master, this will make it into the next release.
