### ISSUE TITLE
Ambiguous error on failed install if port already in use 

### ISSUE THREAD

**Issue by gbiellem** [Particular/ServicePulse#142]
![image](https://cloud.githubusercontent.com/assets/2351700/3240232/bea209de-f121-11e3-85f8-6a86a52272dd.png)

This is the the error returned from the Service Pulse installer when something is already configured to listen on the default Service Pulse port of 9090.

Suggest we make this a bit friendlier - this probably applies to SC as well but I haven't tested it

**Comment by jmkelly** [comment]
Just to add some more context, I did not get an error message that indicated the likely cause of the issue (which made this pretty frustrating to track down)
![image](https://cloud.githubusercontent.com/assets/124026/9128356/3fd0d30c-3d0a-11e5-9ade-eb10d6668c7a.png)

**Comment by WojcikMike** [comment]
The current installer works as described
