### ISSUE TITLE
Plugin needs to be installed - Fresh Install error

### ISSUE THREAD

**Issue by Romiko** [Particular/ServicePulse#144]
Hi,

Priority-Low.

When I install the endpoints for the first time. I get a message in ServicePulse saying plugin needs to be installed, with a few seconds, the plugin gets installed. See below, the first message (bottom to top), says it needs to be installed, a few seconds later, the hearbeat is working. So perhaps the check for plugins needs to occur at a later point in time, if possible...Not sure..

Endpoint SB.Billing.SaveOrderParts running on host SYD-GWSUPPORT has been confirmed to have heartbeats enabled

37 minutes ago

info

HeartbeatMonitoring

 /endpoint/SYD-GWSUPPORT 

/host/e58bf697-bfa6-56bb-84fd-b463a8889b73 

New 'SB.Billing.SaveOrderParts' endpoint detected at 'SYD-GWSUPPORT'. In order for this endpoint to be monitored the plugin needs to be installed.

37 minutes ago

info

EndpointControl

 /endpoint/SB.Billing.SaveOrderParts 

/host/e58bf697-bfa6-56bb-84fd-b463a8889b73

**Comment by WojcikMike** [comment]
@Romiko thank you for registering this issue, as you mentioned it is a low priority so we might pick it in future, but at the moment it will stay in our backlog.

**Comment by WilliamBZA** [comment]
This has been fixed quite a while ago, and is no longer relevant with the dedicated monitoring page. Closing.
