### ISSUE TITLE
Display a tool tip in the endpoint overview and details view if the endpoint is stale or monitoring disconnected

### ISSUE THREAD

**Issue by soujay** [Particular/ServicePulse#1457]
### Describe the suggested improvement

**Is your improvement related to a problem? Please describe.**
   Currently, if the endpoint becomes stale or if the monitoring is not yet setup to send metrics, the monitoring page and the endpoint details page in ServicePulse display a "?" next to the different metrics like queue length, throughput etc. It is not intuitive to the customer as to why there are no metrics data displayed. 

**Describe the suggested solution**

The suggested improvement is to display a tooltip  when the mouse hovers over the "?" to inform the user about why there is no data.

![image](https://user-images.githubusercontent.com/88632084/226189157-680f2d9f-9e70-4b2f-b59e-227e243d3f5b.png)

![image](https://user-images.githubusercontent.com/88632084/226189199-510a5801-6ed9-482b-b168-813fe6b214a8.png)

**Describe alternatives you've considered**

  Display a notification popup or a banner at the top of the page

**Comment by awright18** [comment]
This will be shipped with release 1.35.0
