### ISSUE TITLE
Connection test fails if the url does not end with a slash (version 1.33.1)

### ISSUE THREAD

**Issue by ramonsmits** [Particular/ServicePulse#1469]
#### Expected behavior

Testing connectivity to `http://zolder:33633` should be successful.

#### Actual behavior

Testing connectivity to `http://zolder:33633` fails, but if you add a slash (i.e. ``http://zolder:33633/` it succeeds.

#### Versions

Please list the version of the relevant packages or applications in which the bug exists.        

### Steps to reproduce

1. Open Configuration Tab
2. Select Connections sub tab
3. Enter value without a slash at the end like `http://zolder:33633`
4. Click Test
5. Test shows "CONNECTION FAILED"

**Comment by soujay** [comment]
Will be released in SP 1.36.5

**Comment by soujay** [comment]
The bug has been fixed in ServicePulse 1.37.0 and has been released.
https://github.com/Particular/ServicePulse/releases/tag/1.37.0
