### ISSUE TITLE
ServicePulse Installer failures when upgrading on machines with multiple SP instances. 

### ISSUE THREAD

**Issue by gbiellem** [Particular/ServicePulse#151]
Upgrading  ServicePulse Installer fails on machines with multiple instances of SP installed. 
The service fails to start and causes the installer to roll back.  Originally posted as a  problem on Google groups.   I've replicated the failure on an Azure instance but the MSI log doesn't indicate why the service fails to start.  

This only happens with an upgrade on the test machine, if I uninstall the old version of SP, ensure the folder is  deleted, URLACL etc are definitely removed and then the install worked fine.

**Comment by johnsimons** [comment]
@gbiellem is it ok if we backlog this one ?

**Comment by gbiellem** [comment]
backlogged

**Comment by NArnott** [comment]
Any headway on this? We're evaluating SP right now (having using NSB for a couple years), and love that ServiceControl lets me easily set up multiple instances, but am bummed that SP doesn't have that same experience. Even ServiceInsight has some support for multiple instances.

All this manual setup/copy/install/port setup for SP is more than I want to tackle and maintain.

**Comment by SzymonPobiega** [comment]
Hi @NArnott 

We are not currently working but we are looking into alternative ways to achieve the same result. There is no dates set for this yet, though.

**Comment by sergioc** [comment]
@NArnott we've recently [released the ability to easily let one SP instance connect to different ServiceControl instances](https://docs.particular.net/servicepulse/host-config#configuring-connections-via-the-servicepulse-ui). Would that help in your case?

**Comment by NArnott** [comment]
@sergioc I noticed that, and it works to a degree. We have 4 environments though, and having to remember to path/port to for each one isn't very user friendly. I'd love to be able to enter a list of known connections (with titles, such as Production, Staging, etc), so when a user goes to SP, they can quickly select which environment they want to view.

**Comment by sergioc** [comment]
@NArnott the connection details are stored in the URL, so you can bookmark each connection in the browser and label it with the respective environment's name. How does that sound?

**Comment by NArnott** [comment]
@sergioc  Oh, I was under the impression that if one person switch connections, it would switch for all users. That works then. Thanks!

**Comment by WilliamBZA** [comment]
Closing since SP can service multiple instances of SC now without needing to install multiple instances of SP.
