### ISSUE TITLE
If the viewport width is lower than 1440px the nav bar disappears and it's not clear why 

### ISSUE THREAD

**Issue by mauroservienti** [Particular/ServicePulse#1517]
#### Description

![image](https://github.com/Particular/ServicePulse/assets/1325611/37063cff-258a-40ef-9efd-3f64d0b29acf)

#### Expected behavior

The nav bar is visible in some form

#### Actual behavior

Nothing is visible and it's not clear that it's due to the size of the browser window

#### Versions

Please list the version of the relevant packages or applications in which the bug exists.        

- 1.36.3

### Steps to reproduce

Reduce the width of the browser window

**Comment by mikeminutillo** [comment]
Fixed by https://github.com/Particular/ServicePulse/pull/1668 and https://github.com/Particular/ServicePulse/pull/1679
