### ISSUE TITLE
The "Connect new endpoint" link in the UI footer leads to a blank page

### ISSUE THREAD

**Issue by mauroservienti** [Particular/ServicePulse#1518]
#### Description

![image](https://github.com/Particular/ServicePulse/assets/1325611/f35b6d01-3618-4fcd-b58d-63f8628df4d9)

#### Versions

Please list the version of the relevant packages or applications in which the bug exists.        

- 1.36.3

### Steps to reproduce

Click on the link in the footer to connect a new endpoint (/configuration#/endpoint-connection)

**Comment by soujay** [comment]
The bug has been fixed in ServicePulse 1.37.0 and has been released.
https://github.com/Particular/ServicePulse/releases/tag/1.37.0
