### ISSUE TITLE
 When a message is edited and retried again, the operation is ignored and only a warning is logged

### ISSUE THREAD

**Issue by mauroservienti** [Particular/ServicePulse#1526]
#### Description

When a message fails and is ingested by ServiceControl, at retry time, if the edit & retry feature is enabled, it's possible to edit the message (both headers and body) before retrying it. To retry a message, users need to click on the failed message group to expand the group, then click on the message they want to edit to visualize the message details. The toolbar on the message details screen shows the "Edit & Retry" button.

Clicking the "Edit & Retry" button opens a popup with the message details and the option to retry the message. Upon retry, the popup is closed, but the screen still shows the message details, and the still enabled "Edit & Retry" button allows you to edit the message again. The following screenshot shows a message that has been edited and retried:

![image](https://github.com/Particular/ServicePulse/assets/1325611/563abd8d-7d43-48ba-b414-9548a759f179)

If the edited and retried message in the meantime succeeds, the currently displayed message gets labeled as `Processed`:

![image](https://github.com/Particular/ServicePulse/assets/1325611/dc9eb8ec-a768-4d01-b05e-10e3a6e90d39)

The "Delete message" and "Retry message" buttons are correctly disabled, but the "Edit & Retry" one is not. If users try to edit and retry the message again, it looks like it's retried again, but then in ServiceControl, there is a check that prevents editing and retrying the same message multiple times. the problem is that the request is silently discarded, and only a warning is logged.

#### Expected behavior

The same message cannot be edited and retried multiple times. Only if it fails again the newly failed copy can be edited and retried.

#### Versions

All version

### Steps to reproduce

See the description above

**Comment by soujay** [comment]
will be shipped with Release  1.36.4
