### ISSUE TITLE
In the "Endpoints Overview" and "Configuration" screens, allow for the list of endpoints to be sorted and filtered

### ISSUE THREAD

**Issue by CallumHibbert** [Particular/ServicePulse#153]
In the "Endpoints Overview" and "Configuration" screens the ordering of the endpoints list appears to be random (or maybe be based on when the endpoint was registered or last active or something). When you have more than a few endpoints, this quickly becomes unmanageable.

This is especially true when using MSMQ transport and the distributor pattern - you have multiple instances of the same endpoint but they are not grouped together.

So perhaps, in addition to ordering and filtering, any endpoints with the same name (but on different machines) should be grouped together.

Thanks.

**Comment by johnsimons** [comment]
As a first stab, lets just alphabetically sort them

**Comment by johnsimons** [comment]
#183 slightly improves the lists

**Comment by pablocastilla** [comment]
I think an option to filter by "not heartbeating" would be very interesting. Specially if you have a lot of endpoints.

**Comment by sergioc** [comment]
@petersgiles there's some good clues here about dealing with a potential consolidation of the Endpoints and Configuration screens.

**Comment by andreasohlund** [comment]
Had a user ask for this today where they want to have filtered dashboards for their various teams

**Comment by WilliamBZA** [comment]
This will be released in version 1.25.0 (next week)

**Comment by WilliamBZA** [comment]
Release is out! You can download [1.25.0](https://github.com/Particular/ServicePulse/releases/tag/1.25.0) and this should be done.
