### ISSUE TITLE
Vue router links do not work in a js alerts or toast

### ISSUE THREAD

**Issue by soujay** [Particular/ServicePulse#1543]
#### Description
The links to the vue pages do not work as expected when called from a js alert or toast  Eg:

https://github.com/Particular/ServicePulse/blob/master/src/ServicePulse.Host/vue/src/composables/serviceServiceControl.js#L97

` useShowToast("error", "Error", "Could not connect to ServiceControl at " + serviceControlUrl.value + '. <a class="btn btn-default" href="/#/configuration/connections">View connection settings</a>');`
   
#### Expected behavior
The links should resolve to the correct vue page

#### Actual behavior
The link is incorrect the does not load the expected url
#### Versions

Please list the version of the relevant packages or applications in which the bug exists.        
Version 1.33.1 and above

### Steps to reproduce

1) Go to Configurations-> connections tab
2) Enter in an incorrect ServiceControl connection url and press "Save"
3) Navigate to the "Dashboard" page
4) Notice that there is an error  toast pop up "View connection settings".Click on the link
5) The link is incorrect the does not load the expected url

**Comment by johnsimons** [comment]
This seems to be working in latest version
