### ISSUE TITLE
Health check notifications page insinuates that notification of messages entering error queue is possible

### ISSUE THREAD

**Issue by dbelcham** [Particular/ServicePulse#1552]
#### Description
When you open the Configuration | Health Check Notifications page in Service Pulse, the message reads
> Configure notifications for health checks built into ServiceControl (low disk space, stale database indexes, and messages in error queue).
<img width="695" alt="image" src="https://github.com/Particular/ServicePulse/assets/1378057/f46c7055-f6ac-4581-935f-27722c4afecc">

#### Expected behavior
According to [this post by Tomasz](https://discuss.particular.net/t/servicepulse-mail-notifications/2854/2), it is not possible to generate notifications about messages entering the error queue from the Health Check Notifications configuration.

#### Actual behavior
If it isn't possible to receive notifications about messages appearing in the error queue by configuring email information in this location, it shouldn't be mentioned as one of the outcomes

#### Versions
v1.32.4

### Steps to reproduce

1. Open ServicePulse
2. Open the Configuration page
3. Open the Health Check Notifications tab

**Comment by soujay** [comment]
@dbelcham : Thank you for bringing this to our attention. I can see that we missed updating the text in the Service Pulse UI although the [docs](https://docs.particular.net/servicepulse/health-check-notifications) mentions that  emails will be sent only when internal health checks fail. 
We will have the UI updated as well.

**Comment by soujay** [comment]
@dbelcham : The bug has been fixed in ServicePulse 1.37.0 and has been released.
https://github.com/Particular/ServicePulse/releases/tag/1.37.0
