### ISSUE TITLE
Messagebody is not shown for large messages

### ISSUE THREAD

**Issue by mwettste** [Particular/ServicePulse#1578]
#### Description
For some of our failed messages, the "Message Body" Tab in ServicePulse does not show the actual Json Message Body.
We guess that this could be caused by relatively large message bodies, since messages with smaller payload are displayed normally.

Exact message size which causes the issue is not known, but for one with 13500 characters, it does not display anymore.

#### Expected behavior
Message Body is displayed for all messages.

#### Actual behavior
Message Body is not displayed for messages with large payloads.

#### Versions
ServicePulse v1.37.0

![image](https://github.com/Particular/ServicePulse/assets/3648752/5e0013cb-88b6-445f-9595-2c5f37f274c8)

### Steps to reproduce

Have a large message (~13500 Bytes) that fails and try to view the message body in ServicePulse

#### Workarounds
Complete Message Body can be requested via the API, but this is quite cumbersome.

**Comment by kentdr** [comment]
@mwettste, when I attempt this locally the message body shows up fine.   I suggest you put in a support case so we can go over more details about your specific setup.

**Comment by mwettste** [comment]
Hi @kentdr , sorry for taking so long to get back to you. We did not have any deadletters the past few weeks, so the issue wasn't as pressing anymore. I'll reach out via support case when the issue occurs again.

I will close the issue for now.
