### ISSUE TITLE
Favicon Indicator Flag

### ISSUE THREAD

**Issue by gbiellem** [Particular/ServicePulse#158]
Moved from https://github.com/Particular/ServiceControl/issues/383  - Raised by @enegelev 
" I would like to propose that you guys add a failed message indicator as part of the favicon in the browser tab. Thanks."

**Comment by HEskandari** [comment]
While acknowledging that there are hacks that'd work only on certain browsers, there's no 'proper' way of doing this across all the mainstream browsers so I'm closing this off as a 'Won't fix'.
