### ISSUE TITLE
Failed messages button link is broken when ServicePulse is hosted in a subfolder

### ISSUE THREAD

**Issue by kentdr** [Particular/ServicePulse#1584]
#### Description
     
When on the Monitoring page, Endpoint overview.  The "Failed messages" button does not take into account the subfolder where ServicePulse was served from

![image](https://github.com/Particular/ServicePulse/assets/83468000/4a79ca51-cd2e-4d00-8e18-b2fdd6f4d874)

#### Expected behavior

  The link should use the base URL when selected.  

#### Actual behavior
 
 The link does not use the base URL.  

#### Versions

 1.37.0

### Steps to reproduce

- Configure ServicePulse to be served from a subfolder.  
- Setup a monitoring instance and configure ServicePulse to reference it.
- Setup an NServiceBus endpoint with monitoring and cause a message to be written to the error queue.
- Navigate to the Monitoring page in ServicePulse
- Click the envelope icon next to an endpoint with errors.

**Comment by Aszuul** [comment]
The events tab seems to have the same issue. the Service Pulse version we were testing is 1.37. Had to downgrade to 1.30 for now to avoid the issue.

**Comment by DavidBoike** [comment]
The fix will be released in 1.39.0.
