### ISSUE TITLE
Add date/time to list of events

### ISSUE THREAD

**Issue by SeanFeldman** [Particular/ServicePulse#159]
From customer:

In the events screen there are messages without 'day time', these are marked with the red circles.
I think it is better to start or end every message in this window with 'day time' like :
9/22/2014 12:39:57 PM Endpoint has failed to send expected heartbeat to ServiceControl.
It is possible that the endpoint could be down or is unresponsive.
If this condition persists, you might want to restart your endpoint.

Or something like this instead of the message 2 days ago :
![image001](https://cloud.githubusercontent.com/assets/1309622/4465648/45fe579e-48dd-11e4-8659-99af94f2cc9d.png)

Tip :
Add in the configuration option of the control centre a new option : Don't show events older then .. days. The administrator can decide how many days in the past, the messages should be shown on the screen.
For example :
1 administrator (3 weeks holidays) want to hold a month in his ServicePulse
1 administrator with replacement during his holidays want to hold 3 days or 7 days in his ServicePulse, because of the weekend.

With greetings
Paul

**Comment by johnsimons** [comment]
@SeanFeldman @andreasohlund the list of events is already displaying dates of when the event occurred.
We currently format the datetime as approximate, but if the user hovers over it a full date/time is displayed.

The only thing that we could do here is provide a toggle to display date/time vs approximate date, is that what we should be doing ?

**Comment by SeanFeldman** [comment]
@johnsimons this came as a suggestion from a [support case](https://nservicebus.desk.com/agent/case/7038). If those dates can be retrieved from tooltips, I's say we close this issue.
