### ISSUE TITLE
Add ServiceControl license via ServicePulse

### ISSUE THREAD

**Issue by gbiellem** [Particular/ServicePulse#160]
Add  a simple upload license UI. 

- [ ]  Extend ServiceControl to allow license upload and store it in HKCU
- [ ] Add a license upload UI to ServicePulse. Will only be available for supported version of ServiceControl.

Upload license page could also show a more detailed view of license info such as:
- Trial License Expiry Date
- License Expiry Date

This would address some of the confusion related to applying the ServiceControl license.

**Comment by petersgiles** [comment]
+1

**Comment by johnsimons** [comment]
Isn't some of the confusion also related with showing the license status for individual endpoints ?

**Comment by johnsimons** [comment]
So to understand this correctly, we would still allow the user to license SP/SC as part of the installation, but for the cases where the user is evaluating (so no license yet), we give them the option of licensing the product after installation, is this right ?

Would a user install an evaluation copy of SC/SP in Prod ? Is this just an issue in DEV ?

**Comment by petersgiles** [comment]
If there are multiple licenses to monitor and install that makes an even stronger case for this. 

Is there a use case for ServicePulse in Dev? I thought the tool to use was ServiceInsight. 
In any case all the significant changes would need to happen in ServiceControl. 

SC should probably be able to tell users if they are licensed 'enough' as well. SP could display warnings etc. And SC would throw this info into the logs we ask for as part of support calls.

**Comment by gbiellem** [comment]
> Isn't some of the confusion also related with showing the license status for individual endpoints ?

Good point. perhaps teh wording isn't explicit enough 

> So to understand this correctly, we would still allow the user to license SP/SC as part of the installation, but for the cases where the user is evaluating (so no license yet), we give them the option of licensing the product after installation, is this right ?

The  SC installer/config UI @distantcam and I are working on isn't just going to be available at installation time, it will be accessible post install from the start menu.   So there will already be a GUI that will allow the viewing and adding of the license post install.  I think duplicating the functionality in SP is still worthwhile though - It means they can deal with it in the same place they receive the warning 

> Is there a use case for ServicePulse in Dev? 

We provide it as part of the Platform installer at the moment so it does end up on dev machines. Hard to say how much it is used beyond evaluation for these users

**Comment by johnsimons** [comment]
@gbiellem how about 
> Would a user install an evaluation copy of SC/SP in Prod ? Is this just an issue in DEV ?

?

**Comment by gbiellem** [comment]
> Would a user install an evaluation copy of SC/SP in Prod ? Is this just an issue in DEV ?

I have dealt with a customer who put SP into Prod only and others who's test/prod environment is the same PC to cut costs (cloud) so yeah it does happen.

**Comment by johnsimons** [comment]
@gbiellem 
>I have dealt with a customer who put SP into Prod

But was this installed unlicensed?

**Comment by gbiellem** [comment]
> But was this installed unlicensed? 

No idea.

**Comment by petersgiles** [comment]
Closing because the ServiceControl Management Utility does this.
