### ISSUE TITLE
ServicePulse does not display the "FailedQueue" value for failed messages

### ISSUE THREAD

**Issue by CallumHibbert** [Particular/ServicePulse#161]
When looking at a failed message in ServicePulse you cannot see the "FailedQueue" value that is shown in ServiceInsight. This value is important because it tells you which queue the message will be returned to on retry.

ServicePulse does display the message headers which includes "Processing Machine" and "Processing Endpoint". However, in a scenario where you are using MSMQ and the distributor, the "Processing Machine" and "Processing Endpoint" are not where the failed message will be returned to.

I think there needs to be some clarity on where the failed message will actually be sent to on a retry and the tooling should be explicit.

Thanks.

**Comment by petersgiles** [comment]
This information is shown in 1.4.0

![issue](https://cloud.githubusercontent.com/assets/1644481/13448609/aace5d66-e078-11e5-9ea0-89c6ae0fc005.PNG)
