### ISSUE TITLE
Subpath Disregarded: HeartBeats, Monitoring, CustomChecks, and Events in ServicePulse v1.37.0

### ISSUE THREAD

**Issue by cjoergensen** [Particular/ServicePulse#1613]
#### Description

The HeartBeats, Monitoring, CustomChecks, and Events pages consistently reference the root, such as '/a/#/endpoints.' This poses issues when ServicePulse is hosted under a subpath, for example, https://domain/subpath/servicepulse/.

#### Expected behavior
The anticipated behavior is to acknowledge the subpath, resulting in URLs like https://domain/subpath/servicepulse/a/#endpoints.

#### Versions
ServicePulse v1.37.0

### Steps to reproduce

Host ServicePulse at a subpath.
Navigate to the HeartBeats, Monitoring, CustomChecks, or Events section.
Observe that the links generated for these sections point to the root, such as '/a/#/endpoints' instead of incorporating the subpath.

**Comment by andreasohlund** [comment]
Thanks @cjoergensen , we'll look into this

**Comment by cjoergensen** [comment]
@WilliamBZA setting the `base_url` to the full subpath (`/subpath/servicepulse/`) and clearing the browser cache does the trick. Thank you!

**Comment by andreasohlund** [comment]
@cjoergensen great news! Is there anything in our docs you think we can add to make this more clear? https://docs.particular.net/servicepulse/install-servicepulse-in-iis#basic-setup-hosting-servicepulse-within-a-subfolder

**Comment by cjoergensen** [comment]
@andreasohlund The instructions are clear, but as we're using Kubernetes (k8s) for hosting instead of IIS, I didn't think to refer to that specific page. It's also worth mentioning that browser caching can be a bit deceiving in this context. 😀

**Comment by andreasohlund** [comment]
Got it!

[We'll try to clarify that ServicePulse can be hosted in other web servers that IIS](https://github.com/Particular/docs.particular.net/issues/6340) and how to set that up.

We're on a path to provide you containers for both ServiceControl and ServicePulse to avoid you having to do this work manually in the future.
