### ISSUE TITLE
Provide a way to add description of failed message in ServicePulse by an Ops admin

### ISSUE THREAD

**Issue by eiki25** [Particular/ServicePulse#164]
I would like to see description of failed message in ServicePulse
Naming the message something that the Ops understand is not sufficient. More detail would enable them to respond to the issue.

Would be nice to be able to add the description as a attribute on the contract class
[FailedMessageDescription("This Message connects to System x and x, and should always be retried")]

**Comment by WojcikMike** [comment]
It seems that this issue covers the same need as #393. As such I will close this issue and keep a reference to it, to keep the backlog of items easier to manage.
