### ISSUE TITLE
Internet Explorer 11 is incorrectly detected as an old browser

### ISSUE THREAD

**Issue by johnsimons** [Particular/ServicePulse#167]
When using IE11, SP reports the browser as not being up to date.

Conditional comments were removed from IE10, so IE10 and up will not understand the test.

**Comment by johnsimons** [comment]
@gbiellem have u heard of any affected users ?

**Comment by gbiellem** [comment]
Just that @johnsimons guy who raised the issue :)

**Comment by johnsimons** [comment]
Cannot replicate
