### ISSUE TITLE
 Unable to dismiss custom check notification when using ServiceControl 5.0 or higher

### ISSUE THREAD

**Issue by soujay** [Particular/ServicePulse#1675]
#### Description
After upgrading the ServiceControl to the latest version 5.0.3,the users are unable to dismiss the notifications.
![image](https://github.com/Particular/ServicePulse/assets/88632084/735289cc-767f-4e12-86bb-88d46aab0016)

 A js error is seen in the developer console
![image](https://github.com/Particular/ServiceControl/assets/2351700/265484ae-f138-4143-8e76-f6069eb84498)

#### Expected behavior
- The user should be able to dismiss the custom checks notifications upon clicking on the dismiss button
#### Actual behavior
- The user is unable to dismiss the custom checks notifications and there is a js error in the console
#### Versions
SC 5.0.3, SP 1.37.0

### Steps to reproduce

- Upgrade Servicecontrol version 5.0.3 by following the steps in our docs
- Open ServicePulse and navigate to the Custom Checks tab
- Notice that there is an entry about the remaining disk space.
- The notification cannot be dismissed even after clicking on the dismiss button

**Comment by egroeneveld** [comment]
Hi, thank you for moving on this one. One remark: The same behavior occurs with a fresh install, not just after an upgrade.

**Comment by soujay** [comment]
Similar bug that was reported earlier: https://github.com/Particular/ServiceControl/issues/3898

**Comment by TravisNickels** [comment]
Being released in ServicePulse v1.37.1

**Comment by soujay** [comment]
The bug has been addressed and released in [ServicePulse 1.37.1](https://github.com/Particular/ServicePulse/releases/tag/1.37.1)
