### ISSUE TITLE
FailedMessagesView: When message types are not present in the metadata from SC, then SP must display proper default values instead of NULL_TYPE

### ISSUE THREAD

**Issue by indualagarsamy** [Particular/ServicePulse#169]
For external integration scenarios when 3rd party systems are sending messages to NSB endpoints, they may not contain the `EnclosedMessageTypes` header.

When SC parses this information, the meta data for MessageType will be null. 
We need to set proper value such as `Not available - missing metadata EnclosedMessageTypes` or something of the sort.

Relates to Particular/ServiceControl#429

**Comment by gbiellem** [comment]
@indualagarsamy  - this will be addressed as part of https://github.com/Particular/Requirements/issues/194 correct?

**Comment by indualagarsamy** [comment]
@gbiellem - that's correct. we should.

**Comment by weralabaj** [comment]
![bug](https://cloud.githubusercontent.com/assets/7335079/8797210/3473228a-2f9a-11e5-9e12-0cef6336e2c7.png)
This is how it currently looks like, seems like it was fixed as part of something else. Can we close this one? Or do we want do display different text, rather than "unknown"? 
@gbiellem @indualagarsamy

**Comment by gbiellem** [comment]
I'd prefer a  bit more detail like `Message Type Unknown` or @indualagarsamy's suggestion of  `Not available - missing metadata EnclosedMessageTypes`

**Comment by weralabaj** [comment]
Ok, I'll go with 'Message Type Unknown - missing metadata EnclosedMessageTypes'.

**Comment by weralabaj** [comment]
@johnsimons that was done as part of 194, was merged and can be released independently of SC changes. Can be closed.

**Comment by johnsimons** [comment]
Fixed in https://github.com/Particular/ServicePulse/commit/cee57dc4edcdecfa711f7c8f746989f6ea784d9a
