### ISSUE TITLE
New design: Failed Messages page

### ISSUE THREAD

**Issue by dannycohen** [Particular/ServicePulse#170]
1. Consistent visual language with other pages (specifically Endpoint Management)
* Adjustable for large numbers of failed messages
* Adjustable for significant variety in numbers of message types, endpoints, hosts

**Comment by udidahan** [comment]
Please take into account the issue of deserialization failures described in https://github.com/Particular/Requirements/issues/58

**Comment by gbiellem** [comment]
@dannycohen  Which requirements does this link to?  I know we've has some meeting on moving this forward prior to the new requirements process but at the moment this activity is under the radar and we should try and get it into the pipeline properly

**Comment by sergioc** [comment]
@gbiellem @indualagarsamy would it be useful to also indicate which is the endpoint / instance that sent the message that failed?

**Comment by cjoergensen** [comment]
Hi

The page also has some issues with long endpoint and message type names:

![image](https://cloud.githubusercontent.com/assets/8087733/6730785/cc6d3894-ce3f-11e4-9f6d-404ae559fa67.png)

**Comment by jinskeep** [comment]
I want to second  what cjoergensen posted. our ServicePulse looks just like this as most our endponts have really long names. Having a UI that is more flexible would be greatly appreciated.

**Comment by johnsimons** [comment]
@cjoergensen @jinskeep we considering adding the ellipses in the middle, do you think that would work for you ?
So an example, instead of:
`My.Super.Super.Very.Very.Long.Namespace...`
it would be:
`My.Super...MyMessageName`

**Comment by gbiellem** [comment]
@johnsimons And mouseover for fullname?

**Comment by johnsimons** [comment]
Yes, I think that is already what happens

**Comment by gbiellem** [comment]
Yep - its does, just making sure we're keeping it in the redesign

**Comment by cjoergensen** [comment]
@johnsimons The ellipses in the middle seems like a good solution. But the mouseover also has some problems with long names:

![image](https://cloud.githubusercontent.com/assets/8087733/6751198/aee16fc6-cf01-11e4-9b81-06bea302762e.png)

**Comment by johnsimons** [comment]
@cjoergensen that is annoying :disappointed: 

@gbiellem I think this is because we use the default hovering tip from the `title` attribute, I reckon we can fix this by using the bootstrap tip component.

**Comment by sergioc** [comment]
@cjoergensen @jinskeep we are currently working on an update for this screen that will address both issues with standard and tooltip displays of message names. Stay tuned!
