### ISSUE TITLE
When a message is missing headers such as TimeSent, display appropriate defaults

### ISSUE THREAD

**Issue by indualagarsamy** [Particular/ServicePulse#172]
At the moment, when a message is missing the `TimeSent` header and that message ended up in the error queue, ServicePulse could display the wrong duration. If SC sends the min date value, it could display `2015 years ago`.
While the data needs to be cleaned up in SC, and SC should send in null dates when data is missing, the UI should still display proper defaults such as `TimeSent value is not available` for the missing values.

**Comment by weralabaj** [comment]
@johnsimons that was done as part of 194, was merged and can be released independently of SC changes. Can be closed.

**Comment by johnsimons** [comment]
Fixed in https://github.com/Particular/ServicePulse/commit/91f5c61f680b47e5c1e01ce37135e52dd69e8180
