### ISSUE TITLE
Is ServicePulse 1.1.0 only compatible with ServiceControl 1.5.0?

### ISSUE THREAD

**Issue by bjartwolf** [Particular/ServicePulse#173]
According to the docs (https://github.com/Particular/ServicePulse/releases/tag/1.1.0), ServicePulse 1.1.0 has ServiceControl 1.0.0 as a prerequisite? Should this be 1.0.0 or later or do I have to downgrade ServiceControl 1.5.0 to 1.0.0 (I just went with the default download for ServiceControl)

**Comment by gbiellem** [comment]
Hi @bjartwolf 

Thanks for the heads up - yes that prerequisite is incorrect.  ServicePulse 1.1.0 will work with ServiceControl 1.x.x, so definitely use the latest.

**Comment by gbiellem** [comment]
I've updated the SP release notes to avoid this confusion in future

**Comment by bjartwolf** [comment]
:thumbsup:
