### ISSUE TITLE
When the monitoring backend is unavailable the "View connection settings" button URL is incorrect

### ISSUE THREAD

**Issue by mauroservienti** [Particular/ServicePulse#1766]
#### Description

When the Monitoring backend is unavailable, users are presented with the following toast notification:

![image](https://github.com/Particular/ServicePulse/assets/1325611/b36474e7-b99e-44d7-99fe-58754f32b8bf)

The `View connection settings` button link is incorrect (see the above screenshot in the bottom left corner)

#### Versions

Please list the version of the relevant packages or applications in which the bug exists.        

1.38.1

### Steps to reproduce

- Make the Monitoring backend unavailable
- Observe the link in the toast notification

**Comment by DavidBoike** [comment]
The fix will be released in 1.39.0.
