### ISSUE TITLE
Ability to automatically archive failed messages based on message type

### ISSUE THREAD

**Issue by andreasohlund** [Particular/ServicePulse#1794]
### Describe the feature.

This request is based on feedback from a customer

#### Is your feature related to a problem? Please describe.

Some messages might require any actions if they fail and while a custom recoverability policy might work its easier to set this up in ServicePulse rather than in the endpoint(s)

#### Describe the requested feature
        
Allows auto archive to be configured based message type

#### Describe alternatives you've considered

Custom recoverability in the endpoint(s)

**Comment by mauroservienti** [comment]
Should this be merged into https://github.com/Particular/ServicePulse/issues/1774?

**Comment by andreasohlund** [comment]
Good catch, closing in favor of https://github.com/Particular/ServicePulse/issues/1774
