### ISSUE TITLE
Retry All Messages silently failing

### ISSUE THREAD

**Issue by n-alex-white** [Particular/ServicePulse#185]
When I use Retry All Messages, basically nothing happens. I get a green box appears on the page telling me it is retrying, but nothing ever gets replayed.

I'm guessing that this will be because of the number of messages on the error queue that need to be retried (see picture). 

However, what I would expect is either it would 
a. work its way through them in batches until it was done, or
b. provide an error/warning message to say that it can't process that many messages.

Either way, the current behaviour seems like a bug to me.

![image](https://cloud.githubusercontent.com/assets/2327254/9115894/4d7f5d72-3c59-11e5-8a23-11a856763e7d.png)

Thanks.

**Comment by johnsimons** [comment]
Hi @n-alex-white, we are just about to release new versions of both ServiceControl and ServicePulse that will address this issue.
What version of ServiceControl and ServicePulse are you currently on ?

**Comment by n-alex-white** [comment]
We are on version

    Version: 1.1.1+Branch.master.Sha.aaead68b73a6929ce05f3751e3222856e237037e | Service Control Version: 1.4.4

How can I best keep track of when that new version launches?

**Comment by johnsimons** [comment]
Hi @n-alex-white 

It seems you are a few versions behind on ServiceControl, the latest is v1.5.3
The best way to keep up with updates is to follow https://twitter.com/Particularnews

**Comment by johnsimons** [comment]
@n-alex-white this issue is actually related to https://github.com/Particular/ServiceControl
And this is addressed by https://github.com/Particular/ServiceControl/issues/490, which will be released as part of ServiceControl v1.6

**Comment by johnsimons** [comment]
@n-alex-white we have just releases new versions for ServiceControl, ServicePulse and ServiceInsight.
This issue is addressed in those releases

**Comment by n-alex-white** [comment]
Hi @johnsimons I wonder if this issue could be re-opened?

I've got the latest version of all of these installed and I'm still finding that archiving of large groups of messages just doesn't work. A banner says that it is happening, but nothing actually happens.

**Comment by wolfbyte** [comment]
Hi @n-alex-white, if you are able to email me the [log files](http://docs.particular.net/servicecontrol/logging) from your ServiceControl machine I will try to help to diagnose the issue. mike.minutillo-at-particular.net

**Comment by n-alex-white** [comment]
Thanks @wolfbyte , I've zipped and emailed log files to you.

**Comment by petersgiles** [comment]
@n-alex-white we haven't heard from you in a while. In the meantime we have released a few hotfixes, have tried them? Are you still having this issue?

**Comment by petersgiles** [comment]
closing, no response from customer
