### ISSUE TITLE
Installer fails and doesnt roll back correctly if ServicePulse Port is in use

### ISSUE THREAD

**Issue by jmkelly** [Particular/ServicePulse#186]
I've been battling getting ServicePulse to install, trying to narrow down the cause for the failure and rollback.  

Turns out that even though I ran `netsh http show urlacl  | Select-String -Pattern Reserved.*:9090`, which returned nothing, there was a java process that was listening on port 9090 which caused the ServicePulse service to crash on startup, which then rolled back the install (but left the service).

May I suggest a check in the installer that the port is properly available prior to install?

**Comment by gbiellem** [comment]
@jmkelly  We have an open issue for this here - https://github.com/Particular/ServicePulse/issues/142 so I'll close this one as a duplicate

Also if you are looking for what ports are in use then  netsh.exe  isn't the right tool. What your after is  `netstat.exe -a`

**Comment by jmkelly** [comment]
ok, no worries @gbiellem.  I was following the instructions from .  https://groups.google.com/forum/#!searchin/particularsoftware/servicepulse/particularsoftware/WINyJL-TXUU/H4cf73UDuWEJ to try to find out what my issue was.
