### ISSUE TITLE
Font-Awesome not working in ServicePulse 1.2 on IE 11

### ISSUE THREAD

**Issue by gbiellem** [Particular/ServicePulse#187]
Font-Awesome not working in ServicePulse 1.2 on IE 11
Rolled back to 1.1.1 and it works fine.
I assume we updated it?

//cc @petersgiles  @johnsimons 

<img width="524" alt="font-awesome" src="https://cloud.githubusercontent.com/assets/2351700/9349594/8ce42254-468b-11e5-869c-35e8caf597e5.PNG">

**Comment by petersgiles** [comment]
@gbiellem no AFAIK we didn't update it. looking at the solution its 4.1.0 latest FA is 4.4.0

**Comment by petersgiles** [comment]
@gbiellem probably need something like <meta http-equiv="X-UA-Compatible" content="IE=edge"> in the head of the page. I'll look into it.
