### ISSUE TITLE
Redistributable package for perpetual license users

### ISSUE THREAD

**Issue by satyajit-behera** [Particular/ServicePulse#192]
It may be good to come up with a redistributable package of service pulse which can be distributed with the application (licence embedded in the package).

It will help in easy manageability of distribution of NSB with the custom applications / products.

**Comment by gbiellem** [comment]
No license is directly applied to ServicePulse. Instead SP queries ServiceControl for licensing information.  ServiceControl now supports a command line option to import the license at install time which I think is what you are after.
