### ISSUE TITLE
Error Groups Title

### ISSUE THREAD

**Issue by cjoergensen** [Particular/ServicePulse#194]
The title column in the Error group view could be optimized for longer exception messages, its kinda hard to tell the different exceptions apart:

![image](https://cloud.githubusercontent.com/assets/8087733/10572522/88a994e2-7649-11e5-818c-c792ea14510b.png)

The overview could be better if the column was compose over multiple lines:

[NServiceBus.ExceptionInfo.ExceptionType]
[MessageType]
[NServiceBus.ExceptionInfo.Message - without stacktrace]

Ex.:

![image](https://cloud.githubusercontent.com/assets/8087733/10572724/148be7b6-764b-11e5-8c28-d55ca77fb641.png)

**Comment by petersgiles** [comment]
@cjoergensen I'll talk it over with the design guys

**Comment by petersgiles** [comment]
@cjoergensen we've made an adjustment to show the whole title field. You should see this appear in the next release of Service Pulse.

**Comment by cjoergensen** [comment]
@petersgiles Cool
