### ISSUE TITLE
Error Groups - Messages not sorted properly

### ISSUE THREAD

**Issue by cjoergensen** [Particular/ServicePulse#195]
When browsing failed message inside an Error Group the messages are not sorted properly.

Here is an example of messages sorted by Time Sent:

![untitled](https://cloud.githubusercontent.com/assets/8087733/10577538/5b63435c-766c-11e5-8ae4-291516d5b0f3.png)

**Comment by petersgiles** [comment]
@cjoergensen I'm having a bit of trouble replicating this. Is it possible for you to give me a copy of your database. It's usually located in C:\ProgramData\Particular\ServiceControl

**Comment by petersgiles** [comment]
@cjoergensen I have found the the problem and I have moved this issue to the service control repository.
