### ISSUE TITLE
ServicePulse fails to install when ServiceControl is not installed

### ISSUE THREAD

**Issue by ramonsmits** [Particular/ServicePulse#198]
I tried installing ServicePulse, ServiceControl was not installed. I selected a different port and pressed install. Install failed with the message that the port could not be used. I then installed ServiceControl, then ServicePulse with a custom port and the install went just fine.

**Comment by gbiellem** [comment]
Hi @ramonsmits 

That was the case back in ServicePulse v1.1.1  but it's been fixed since @petersgiles and I retested today and confirmed this.

**Comment by petersgiles** [comment]
Yes confirmed this today
