### ISSUE TITLE
Support switching environments in the UI

### ISSUE THREAD

**Issue by ramonsmits** [Particular/ServicePulse#2035]
### Describe the feature.

Some support to be able to use the same instance to use different ServiceControl instances was already added in https://github.com/Particular/ServicePulse/releases/tag/1.20.0 :

- https://github.com/Particular/ServicePulse/issues/690

but it would be nice if a used could easily switch between multiple configured instance in the UI without requiring separate ServicePulse bookmarks.

This would make it easy to switch between multiple stating environments or maybe multiple production deployments of ServiceControl.

Bonus points if the UI could have a clear identification of which environment is selected. For example

- Have the whole UI have a different 1 or 2 pixel width border color (red, green, purple, etc.), or
- When triggering actions it lists the enviroment like "Retry message on Production", or
- When triggering actions you can a confirmation dialog, or
- List the active environent in the browser title

**Comment by johnsimons** [comment]
This is very similar to https://github.com/Particular/ServicePulse/issues/1535

So I have added a [comment](https://github.com/Particular/ServicePulse/issues/1535#issuecomment-2403675230) to it and I am closing this one.
