### ISSUE TITLE
Support JavaScript Tests in TeamCity

### ISSUE THREAD

**Issue by colin-higgins** [Particular/ServicePulse#204]
## Goal
To support javascript tests in  continuous integration and start gaining test coverage in ServicePulse. 

### Plan of Action
- [x] Choose a testing framework. (Mocha/Jasmine/Karma)
- [x] Write a few small tests. 
- [x] Choose a headless browser. (Phantom/Zombie)
- [x] Add headless browser to TeamCity as a step to execute all javascript tests.

Chutzpah or some task runner can be used for running tests locally. I highly recommend Chutzpah, though I have not tested 2015 support yet.
https://github.com/mmanela/chutzpah

cc / @johnsimons @petersgiles

**Comment by petersgiles** [comment]
@colin-higgins 
I've had a little more experience with Karma but I'm certain Jasmine would be fine too.
I think the best tests to start with would be for the calls to Service Control

- What would be the best way to run the tests on our dev machines?
- Most of my experience is using gulp tasks is there a more visual studio integrated way?

Is this a good time to do create a new issue to do a retrospective review of the code base to identify where we could make things better? It ties in with all the service control stuff that's going on too.

**Comment by colin-higgins** [comment]
@petersgiles 
I'm just the opposite and have used jasmine. :smile: 
As far as visual studio integration, the best I have used is Chutzpah: https://github.com/mmanela/chutzpah

I don't know if it makes sense to add more noise to the ServiceControl futures, there are a lot of cooks with a lot of dishes to prepare in that kitchen already. This can be pretty isolated and non disruptive IMO.

**Comment by petersgiles** [comment]
@colin-higgins I'm happy with jasmine...I agree with your assessment on the other stuff

**Comment by petersgiles** [comment]
done! uses Qunit, Jasmine, & Phantom
