### ISSUE TITLE
Flaky test: test/specs/monitoring/sorting-endpoints.spec.ts

### ISSUE THREAD

**Issue by PhilBastian** [Particular/ServicePulse#2057]
#### Description

Occasionally a CI build will fail due to the test in test/specs/monitoring/sorting-endpoints.spec.ts. An example is https://github.com/Particular/ServicePulse/actions/runs/10826711276/job/30038261421?pr=2056. Re-running the build will generally succeed

### Steps to reproduce

Run a CI build

**Comment by cquirosj** [comment]
A possible fix has been [added](https://github.com/Particular/ServicePulse/pull/2058). Please re-open if this happens again for this test.
