### ISSUE TITLE
No endpoints are visible on the "Endpoints Overview" page

### ISSUE THREAD

**Issue by Bishbulb** [Particular/ServicePulse#207]
I just upgraded to ServicePulse 1.3.3 and now none of my endpoints are showing up:
![screenshot 2015-11-04 07 19 43](https://cloud.githubusercontent.com/assets/1005284/10938007/f488ee6a-82c4-11e5-8d04-181f8659aa13.png)

I have done CTRL+F5 in the browser multiple times, but still don't see anything. The Chrome developer tools indicate that the browser received a 200 response from http://localhost:33333/api/endpoints with all of the data that I would expect to see there.

I am running the latest Chrome 46.0.2490.80, and the latest ServiceControl 1.7.2.

**Comment by Bishbulb** [comment]
This is working for me now - thanks!

**Comment by petersgiles** [comment]
Thank you so much your patience. I really appreciate your contribution to making this product better.
