### ISSUE TITLE
Smoke Test for pre-release

### ISSUE THREAD

**Issue by petersgiles** [Particular/ServicePulse#209]
taskforce: @petersgiles

Recently I've been working on ServicePulse and releasing fixes as I go. I've found myself caught by the lack of unit testing a few times now I think we (me especially) would benefit from a checklist I can follow to ensure better coverage during pre-release testing. At the very least it might save future embarrassment but I imagine it could serve to inform us as to what to put into our client unit test.

---

### Fresh Install
1. Use Custom UI shown in Installer
1. app.config.js updated to correct URL
1. change url and restart - URL stays the same

### Upgrade tests (from 1.1, 1.2, 1.3, 1.3.1, 1.3.2, 1.3.3, 1.3.4)
1. Silent install respects existing setting
1. Interactive install respects existing setting

### Version Stamping
1. Correct version stamped on Extract
1. Correct version stamped on Build 
1. File not restamped on Run

## Test ServicePulse
1. Start ServicePulse & ServiceControl
1. Use the Fault Tolerance sample to create a few errors (turn off retries to save time)
1. Navigate to each page testing the breadcrumbs and other in app links
1. Navigate to Dashboard 
   1. check that the failure counts match your expectations
   1. check that the Latest events log makes sense
   1. check that the endpoint counts are correct
   1. check that clicking on each of the indicators navigates you to the correct page
   1. check that version indicator at the bottom of the page is correct
1. Navigate to Endpoints
   1. check that the active and inactive endpoints are correct
1.  Navigate to Custom Checks
   1. check that any expected custom checks are present
1.  Navigate to Configuration
   1. check that all Endpoints can have their heartbeats activated and deactivated
1.  Navigate to FailedMessages
   1. check that clicking on a message group link navigates to the messages tab and shows just the messages of that group
   1. check that 'view all failed messages' navigates to the messages tab
   1.  In the Error Groups tab check that all ErrorGroups are present (leave the fault tolerance [FT] sample running with the exception on)
      1. check that you can retry an ErrorGroup  & check for processing in FT
      1. check that you can retry ALL ErrorGroups ( the big red button ) & check for processing in FT
      1. check that you can archive an ErrorGroup
   1.  In the Messages tab check that the action buttons on each message function correctly
      1. check that you can retry a Message & check for processing in FT
      1. check that you can archive a Message 

---

I hate to add yet another layer of process to what we do but I wonder if it would be worthwhile to look at a test management tool.

- http://www.gurock.com/testrail/
- http://www.testiatarantula.com/
- http://www.jatakasource.org/testcube/

**Comment by sergioc** [comment]
That's great @petersgiles !

**Comment by sergioc** [comment]
Would a test management tool be worthy at this time for such a small checklist?

**Comment by petersgiles** [comment]
not yet...but i do think at sometime in the near future we may need to look at something beyond unit testing.

There are things that are hard to unit test like data entry elements lining up properly or branding looking right. this will be especially important as we move toward the composite UI approach that is emerging from the SC discussions.

**Comment by sergioc** [comment]
@petersgiles I asked some questions regarding going beyond automated testing here: https://github.com/Particular/PlatformDevelopment/issues/354#issuecomment-139305530

**Comment by sergioc** [comment]
@petersgiles what about Selenium tests? It's more automation, but it could cover that list.

**Comment by petersgiles** [comment]
@sergioc I've heard of Selenium but never used it. Does it do things besides web? we have a lot of WPF out there in the wild.

I don't want to over-cook this as a process. It would be nice to have something for each product that focuses someone preparing for a release on the features that, if not functioning, completely nreak the product.

**Comment by sergioc** [comment]
AFAIK Selenium is commonly used for Web, but [apparently can also be used for WPF](http://stackoverflow.com/questions/12303286/automation-solution-for-both-web-and-wpf-applications).

**Comment by petersgiles** [comment]
Nice, It might be worth looking at this pluralsight course to get an overview of how it actuall works http://www.pluralsight.com/courses/selenium

**Comment by petersgiles** [comment]
Today this improved a bit https://github.com/Particular/ServicePulse/issues/204 established client side unit testing

**Comment by petersgiles** [comment]
Closing, testing has been established in ServicePulse and a good small suite of apps is present to support smoke testing common scenarios
