### ISSUE TITLE
Number of error displayed on the endpoint screen is incorrect

### ISSUE THREAD

**Issue by DCollart** [Particular/ServicePulse#2171]
#### Description
Number of error displayed on specific endpoint screen is not correct.

#### Expected behavior
When I'm in the endpoint screen, the number of error shown aside the title should be related to my endpoint.

#### Actual behavior
I got a number of error related to another endpoint.
When I click on it it's indeed some error unrelated to my endpoint.

#### Versions
ServicePulse v1.41.0
ServiceControl v4.33.5

Please list the version of the relevant packages or applications in which the bug exists.        

### Steps to reproduce

I guess it's quite random but it happens frequently in our instance.

Go to "Monitoring" screen.
Select a endpoint and check the number of error messages before clicking:
![image](https://github.com/user-attachments/assets/f32bdefa-d7ea-45ff-b14a-cff38e39acf9)

Click to go to the endpoint screen and check the number of error messages:
![image](https://github.com/user-attachments/assets/8516a1a7-c1d2-4e25-91b2-37ef8c993a53)

Now there is 2 error messages. If I click on those errors I see those are not related to my endpoint.

I get this issue on multiple endpoint and each time it shows the errors messages of a specific endpoint (so the "targeted" endpoint containing the error messages is always the same).

**Comment by boblangley** [comment]
@DCollart We cannot reproduce this issue.

4.33.0 is an unsupported version of ServiceControl. Can you try updating and see if the problem persists? If so, [please submit a support case](https://particular.net/support) so we can help you in more detail.
