### ISSUE TITLE
ServicePulse Message Body tab: Message not visible

### ISSUE THREAD

**Issue by gursharan001** [Particular/ServicePulse#2175]
#### Description
Message Body tab does not show message body

#### Expected behavior
Message body should be shown

#### Actual behavior
`Message body unavailable` message is shown

#### Versions
ServicePulse - 1.44.1
Service Control - 6.1.0
SC Monitoring - 6.1.0

Please list the version of the relevant packages or applications in which the bug exists.        

### Steps to reproduce

I note that the `Content-Encoding` response header has a value of `br` for the request url of https://service-pulse.docmesh.com/api/messages/<guid>/body

However, the Response tab in edge browser looks something like this
<img width="696" alt="image" src="https://github.com/user-attachments/assets/0b947108-fc18-4747-a242-e93835140ef2">

If i save the response output as a gzip file and uncompress, i get correctly format json message body

so looks like the api is sometimes selecting `gzip` encoding for response but sending a `br` value to browser

#### Workarounds
manually save response as gzip to file system and uncompress

**Comment by boblangley** [comment]
@gursharan001 ServiceControl does not gzip the message bodies.  Are you using a Serializer that would gzip the message body? Is there a chance you are serving the api through a proxy that compresses the result and/or changes the content type?
