### ISSUE TITLE
CSV export is improperly formatted

### ISSUE THREAD

**Issue by SamuelBittmann** [Particular/ServicePulse#2178]
#### Description
When I export one or more failed messages, the CSV seems to be malformatted. This makes the CSV output almost unusable for me, since tools (e.g. PowerShell and Excel) cannot correctly import this data.

#### Expected behavior

1. The exported CSV uses consistent separators for columns (e.g. always commas or tabs) across header and value rows
2. Values are correctly enclosed in `"`, especially multiline values (e.g. stack traces)

#### Actual behavior
1. The header columns are separated by tabs, the columns in the value rows by commas
2. The values are not enclosed/escaped at all, not even multiline stack traces

#### Versions

ServicePulse v1.42.1

### Steps to reproduce

1. In ServicePulse, navigate to failed messages
2. Select one or more failed messages
3. Click on "Export x selected"

**Comment by dvdstelt** [comment]
Hi, the fix shouldn't be too hard. We're assuming we fixed it and are currently testing it, since there were also some updates of packages.
We'll let you know here as soon as we release the fix.

**Comment by ramonsmits** [comment]
Fixed in

- https://github.com/Particular/ServicePulse/releases/tag/1.44.2

**Comment by SamuelBittmann** [comment]
Just tested it, works great. Thanks for fixing it so quickly!
