### ISSUE TITLE
menu text disappears 

### ISSUE THREAD

**Issue by SimonCropp** [Particular/ServicePulse#218]
This seems to occur when the page width is in the range 1000-1190px

![2015-11-11 18_35_59-service pulse](https://cloud.githubusercontent.com/assets/122666/11086242/32a41bd2-88a3-11e5-9ec6-b0f75d66b4fc.png)

**Comment by petersgiles** [comment]
This seems to be by design `span class="hidden-md"` is wrapping each menu item. I can see why too the text wrapping looks pretty goofy. `span class="hidden-sm"` might be preferable though I'll try a few things and paste some screens. You can tell me what you think.

**Comment by petersgiles** [comment]
This what it looks like with the `hidden-md` removed

![pulse medium](https://cloud.githubusercontent.com/assets/1644481/11135555/30e5aeca-89fa-11e5-980f-cbfa94debc22.PNG)

And with the `hidden-sm` class

![pulse small](https://cloud.githubusercontent.com/assets/1644481/11135560/4a34c78a-89fa-11e5-99b5-91a731dac7e8.PNG)

See https://github.com/twbs/bootstrap/issues/8883 for how people are trying to deal with this issue

to get both working together which would mean the text doesn't return to the screen after passing through the medium range I need to do this

```
        <li>
            <a href="/#/endpoints">
                <i class="fa fa-heart icon-white"></i>
                <span class="hidden-sm">
                    <span class="hidden-md">  Endpoints Overview</span>
                </span>
            </a>
        </li>

```

which is probably the best result for now short of redesigning the interface

**Comment by petersgiles** [comment]
@SimonCropp I think this fixes the immediate problem We will have to redesign the interface if it becomes too large a problem
