### ISSUE TITLE
Upgrading from 1.3 the installer ignores existing ServiceControl URI 

### ISSUE THREAD

**Issue by gbiellem** [Particular/ServicePulse#221]
### Symptom 

If a ServiceControl URL was configured to a custom value in config.js the installer would respect that setting and show it in the UI on upgrade.  This behavior was broken by a change in 1.3 as the config now resides in app.constants.js but the installer custom action does not check this file.

### Who affected

Anyone attempting an interact upgrade of ServicePulse since 1.3.

**Comment by petersgiles** [comment]
app.constants.js not app.config.js

**Comment by gbiellem** [comment]
Corrected - Thanks @petersgiles

**Comment by petersgiles** [comment]
@gbiellem there was an app.config briefly but it was consolidated into app.constants probably a dumb idea in retrospect. :(

**Comment by gbiellem** [comment]
@petersgiles  are you saying there are 3 variations?

**Comment by petersgiles** [comment]
yes, but I'm certain the app.config variant never got released.
