### ISSUE TITLE
Error: Cannot load Counter Name data because an invalid index '' was read from the registry.

### ISSUE THREAD

**Issue by ramonsmits** [Particular/ServicePulse#223]
I got the error "Cannot load Counter Name data because an invalid index '' was read from the registry."

I don't know if this is common but we could catch this exception and tel the user to rebuild their performance counters using "lodctr /R"

https://support.microsoft.com/en-us/kb/300956

**Comment by petersgiles** [comment]
@ramonsmits how do I recreate this?

**Comment by gbiellem** [comment]
@petersgiles you can't repro.  It's a side effect of perf counter corruption.  

@ramonsmits  
I don't know why you'd get this from Pulse as it doesn't register any perf counters.  Was this install run through the Platform Installer.  In so then the problem would be a PI one ( it does install perf counters)

**Comment by zumkpisces** [comment]
1. Go to Start, type”cmd”.

2. Right-click on cmd.exe and choose ‘Run as administrator’.

3. Type “lodctr /r” and press enter.

You will then get the message ‘Info: Successfully rebuilt performance counter setting from system backup store’.

4. Check if there are providers that are disabled, write “lodctr /q” and press enter

5. You will then get a long list of providers, make sure that the [CRM Client] is Enabled, see below

If not, write “lodctr /e:CRM Client” and press enter.

6. Install the Microsoft Dynamics CRM for Outlook client Update Rollup

**Comment by petersgiles** [comment]
@ramonsmits please verify that @zumkpisces solution works for you

**Comment by gbiellem** [comment]
As i stated before this isn't any perf counters in  servicepulse so it is unrelated to this  product.  There are already docs covering reseting perf counters in docs.particular.net and on the microsoft site.  So I say this issue should be closed as withdrawn

**Comment by ramonsmits** [comment]
@petersgiles @gbiellem I think I accidentally created it on this repo. I already mentioned the `lodctr /r`  fix that @zumkpisces provides and the whole CRM stuff in his comment is irrelevant.
