### ISSUE TITLE
ServicePulse commandline arguments are not validated

### ISSUE THREAD

**Issue by ramonsmits** [Particular/ServicePulse#228]
ServicePulse command-line arguments are not validated. They are case sensitive and having an argument in incorrect casing or having a typo just ignores it.

**Comment by petersgiles** [comment]
@gbiellem maybe we should look at this http://www.nuget.org/packages/NDesk.Options/ I've used it before and it has a nice api for handling command-line args

**Comment by gbiellem** [comment]
Not sure it's necessary to add a new package, SP is already using the same lib for handling param sets that SC uses and it works pretty well.  I think all that's needed is to ensure it's actually set up correctly

So i think all that's needed is

- Removing case sensitivity ( should be an easy fix.)
- Validate that the provided SC and SP URLs are valid URIs.  
- Ensure the param sets work as advertised
- Update the help text to ensure that users know what the param sets do

Validation of the servicename should be unnecessary as the underlying API will throw if that's a problem.

**Comment by petersgiles** [comment]
ok that sounds fine

**Comment by gbiellem** [comment]
@petersgiles I just realized that the package you proposes above is actually the one we are already using :)

**Comment by petersgiles** [comment]
hahaha...well great minds think alike. from memory that one lets you ignore case, or at least compensate for it pretty easily
