### ISSUE TITLE
Check for ServiceControl Updates

### ISSUE THREAD

**Issue by dannycohen** [Particular/ServicePulse#23]
As Opie, I would like to be notified when a new version of ServiceControl is available, and what are the enhancements provided by it.

1. When ServicePulse starts, check for the latest released version of ServiceControl by calling: http://particular.net/api/products/ServiceControl/Current
   * Note: ServiceControl version API is not yet implemented (see https://github.com/Particular/Website.Backend/issues/133) 
* Compare the version field number of the current release to the ServiceControl version installed. 
* If the current version is newer than the currently installed version, display the following dialog:
```
A newer version of ServiceControl [NewVersionNumber] is available for download at: http://particular.net/downloads.
```
```
For more information on version [NewVersionNumber] see https://github.com/Particular/ServiceControl/releases/tag/[NewVersionNumber] 
```
   * Note: for an example of a release info, see: https://github.com/Particular/NServiceBus/releases/tag/4.0.5
* Repeat the check for updates and the notification every 24 hours (since ServicePulse users tend to leave it running for long periods; note that this is just an in-memory task, and there is no need to persist this timed task; if the user closes ServicePulse, then the check and notification will be performed again on ServicePulse restart)

**Important Notes:**

   * The URI calls to check the latest release  must not delay the loading time of ServicePulse. (It must be done as a background async operation)
   * If there is no internet connection or the Particular.net site is not accessible for any reason, do not display an error message
   * The message dialog must be modeless (it must not interfere with the user's work; it is intended only to draw the user's attention; it can be implemented as a toast popup that can be hidden via a click as stated above). 
* This issue requires the addition of ServiceControl version API support in the Particular.net backend API (see https://github.com/Particular/Website.Backend/issues/133)
* This issue requires the addition of a version parameter in ServiceControl version API (see https://github.com/Particular/ServiceControl/issues/72)
* If ServicePulse and ServiceControl both have a new version, display their indicators together (see #22)

**Comment by petersgiles** [comment]
this was solved in https://github.com/Particular/ServicePulse/issues/22
