### ISSUE TITLE
404 on /css/font-awesome/fonts/fontawesome-webfont.woff2?v=4.4.0

### ISSUE THREAD

**Issue by ramonsmits** [Particular/ServicePulse#230]

**Comment by petersgiles** [comment]
@ramonsmits it would be useful if you explained what your setup is. I'll assume that you've extracted this and are serving in IIS. 

Have you set up IIS mime types to serve web fonts

A typical @font-face declaration includes a .eot file, a .svg file, a .ttf file and a .woff file. If your IIS does not serve any of the previous file types, you need to set the appropriate mime type.

Simply add the following MIME type declarations via IIS Manager (HTTP Headers tab of website properties):

Extension | Mime Type
------------ | -------------
.eot | application/vnd.ms-fontobject
.ttf  | application/octet-stream
.svg | image/svg+xml                 
.woff | application/font-woff         
.woff2 | application/font-woff2   

OR set them in your web.config (these settings can work well if font-awesome isn't working properly)

```
<system.webServer>
    <staticContent>
        <mimeMap fileExtension=".eot" mimeType="application/vnd.ms-fontobject" />
        <mimeMap fileExtension=".ttf" mimeType="application/octet-stream" />
        <mimeMap fileExtension=".svg" mimeType="image/svg+xml" />
        <mimeMap fileExtension=".woff" mimeType="application/font-woff" />
        <mimeMap fileExtension=".woff2" mimeType="application/font-woff2" />
    </staticContent>
</system.webServer>
```

If you still having problems and IIS still is not serving the files, try removing the MIME type declaration before re-declaring it. See the example below for the .woff MIME type.

```
<system.webServer>
    <staticContent>
        <remove fileExtension=".woff" />
        <mimeMap fileExtension=".woff" mimeType="application/font-woff" />
    </staticContent>
</system.webServer>
```

**Comment by SimonCropp** [comment]
lets just move to Helvetica

**Comment by petersgiles** [comment]
> lets just move to Helvetica

That's so sad

**Comment by SimonCropp** [comment]
perhaps. but this is an ops tool. ask any ops person "would you rather Helvetica or the pain and complexity cause by custom fonts".  I mean "Have you set up IIS mime types to serve web fonts" are you serious?

**Comment by petersgiles** [comment]
You don't have to set up fonts for the text to render...it renders in what ever is native on the the OS, probably Ariel on windows, if the webfont isn't present. Not every 404 is the end of the world. If you care enough to extract the site from the host then you probably care enough to make the fonts work...Why IIS doesn't have these mime types by default is the real question.

I guess we could write a PS script to install these type on IIS to help people with this problem. But If you served the site on apache or nginx, or whatever (which I'm pretty sure wouldn't be a problem) should we provide scripts for each of their quirks too.

**Comment by gbiellem** [comment]
Not sure I get the whole "helvetica" conversation in this context.  Font-Awesome is just providing icons.
Is there any reason to use this custom font to provide these icons rather than some actual images?

**Comment by gbiellem** [comment]
@petersgiles  I'd be really surprise if there was anyone hosting SP on Nginx or Apache.
In both cases you still need to setup the mime types when hosting fonts. See https://github.com/fontello/fontello/wiki/How-to-setup-server-to-serve-fonts for a quick guide.

**Comment by petersgiles** [comment]
font-awesome is there because it's part of the template we bought. I doubt this problem is new. We could remove it. or polyfill from a cdn (but i guess there's customers behind firewalls so that won't help them). I think we are drawing attention to the need to redesign SP. This is just one of many issues people have with the look and feel

**Comment by petersgiles** [comment]
...My opinion is that we add the info I've given (if it solves this problem) to the doco regarding extraction of service pulse. Anything else involves design changes and coding, which need a bigger group of people involved.

Anyone disagree?

**Comment by gbiellem** [comment]
@petersgiles - sounds good. I can run through thr setup and and the
appropriate doco

**Comment by petersgiles** [comment]
Yes lets do that together, we might find other things worth noting too, like [this](https://github.com/Particular/ServicePulse/issues/231) probably needs a little explanation too

**Comment by ramonsmits** [comment]
@petersgiles This was a default IIS setup.

**Comment by petersgiles** [comment]
@ramonsmits then it is probably missing the woff2 mime type, we have updated the documentation. To help people with this issue http://docs.particular.net/servicepulse/install-servicepulse-in-iis 



## Adding Mime Types for Web Fonts

If 404 errors when serving webfonts it is possible MIME type for web fonts have not been configured. Add the following MIME type declarations via IIS Manager (HTTP Headers tab of website properties):

Extension | Mime Type
------------ | -------------
.eot | application/vnd.ms-fontobject
.ttf  | application/octet-stream
.svg | image/svg+xml                 
.woff | application/font-woff         
.woff2 | application/font-woff2   

NOTE: Some of these mime types will already be setup on newer versions of IIS. Please verify that all the listed mime types are present.
