### ISSUE TITLE
Deprecate Extract Option from ServicePulse command line

### ISSUE THREAD

**Issue by petersgiles** [Particular/ServicePulse#234]
This option breaks our ability to provide a good upgrade experience for our users.
- The platform installer doesn't support an IIS install of Pulse
- We get regular support requests on how to configure IIS for Pulse 
- We get regular support requests on configuring SSL for Pulse and Control

To the best of my knowledge RavenDB doesn't allow its customers to extract and host it's product in IIS. Slack is written with web technologies and they have a dedicated client, their upgrade experience is a dream btw.

I'm convinced our customers would be better served with a managed install experience that is a known quantity.

related to: https://github.com/Particular/docs.particular.net/pull/948

**Comment by petersgiles** [comment]
@gbiellem @johnsimons are you interested?

**Comment by gbiellem** [comment]
@petersgiles deprecate in favor of what?  

The primary reason users do this is tout IIS in front of it to add an authentication layer. So we need to answer that requirement first.

**Comment by petersgiles** [comment]
some history, https://github.com/Particular/ServicePulse/issues/3
