### ISSUE TITLE
IE11 not working correctly with ServicePulse/Control over SSL

### ISSUE THREAD

**Issue by ramonsmits** [Particular/ServicePulse#235]
Getting the message `error.fatal` when opening ServicePulse over SSL with IE11.Opening it with Chrome does not result in this message.

![error.fatal message](https://www.dropbox.com/s/in2uzq10b0g5jgy/Screenshot%202015-12-01%2017.46.56.png?raw=1)

It seems to work ok I think.

**Comment by petersgiles** [comment]
@ramonsmits check the solution here, you maybe suffering the same thing https://github.com/Particular/ServicePulse/issues/226
