### ISSUE TITLE
Add option to group messages by name or full namespace in the group view

### ISSUE THREAD

**Issue by christoffer-lundqvist** [Particular/ServicePulse#239]
If your handlers don't take care of exception and just bubble them up, you have no clear exception message it's hard to actually know what is the message type. Specially if the code crashed in a library you don't own. It would be better to always (or and option) to always show the type of the message that failed.

![image](https://cloud.githubusercontent.com/assets/16411065/11972744/d573ffd0-a950-11e5-876c-2aaef2a33ef4.png)

**Comment by petersgiles** [comment]
related to: https://github.com/Particular/PlatformDevelopment/issues/282

**Comment by boblangley** [comment]
related to https://github.com/Particular/ServiceControl/issues/721

**Comment by WojcikMike** [comment]
In the latest version of ServicePulse it is already implemented (1.12)
