### ISSUE TITLE
Archiving Message group causes new failed messages of same error type to be ignored when retrying

### ISSUE THREAD

**Issue by gaurav0106** [Particular/ServicePulse#240]
Scenario :
1. Archive a failed message group 
2. A new failed message comes in of the same error type as the above error group of messages which are archived
3. Retry the failed message, Service pulse shows as 'Retrying...' but nothing happens, message does not move from error queue at all.
4. Investigating Service Control logs suggest that the retry request was ignored as message belongs to an error group which has been archived.  
5. Selecting retry all does force all messages to be retried whether belonging to archived group or not.

Issue :
Service pulse should show some kind of visual cue to let the user know that message was not retried as the whole error group is archived instead of just saying 'Retrying...'and then nothing happens

Also once a error group is marked as archived there is no way for user to un-archive it which leads to all future failed messages getting stuck as they cant be retried.

**Comment by johnsimons** [comment]
@mikeminutillo @petersgiles  this seem to be just a timiing issue, maybe we need to show to the user when a message is skipped, thoughts ?

**Comment by johnsimons** [comment]
@gaurav0106 regarding "Selecting retry all does force all messages to be retried whether belonging to archived group or not.", we have fixed this bug in v1.6.3 of ServiceControl, see https://github.com/Particular/ServiceControl/releases/tag/1.6.3, so if you install the latest version of ServiceControl, this should be fixed.

**Comment by petersgiles** [comment]
@johnsimons We have an outstanding issue for better feedback when retrying a failed message https://github.com/Particular/ServicePulse/issues/224 

We do need to invest in making the request to retry a group more precise or at least let users know that if a new message fails before the UI updates it will be processed with all the other messages in the group.

It also seems from @gaurav0106 's description (if I understand correctly) that there may be scenario where 
- A message is retried 
- The user decides to archive the group it belongs to
- Then retry attempt fails
- Then when the user tries to archive it, it says it already belongs to an archive

**Comment by petersgiles** [comment]
@gaurav0106 Are you able to send me a copy of your ServiceControl database? If you can zip it up and send it to me peter.giles@particular.net that would be great. 

If it isn't too big for email it should get through just fine. If that doesn't work we can make some other arrangement (we sometimes use https://www.wetransfer.com for large archives)

Once I get that I will try and reproduce the issue.

Can you also tell me the versions of ServiceControl and ServicePulse you are using.

Thanks

**Comment by gaurav0106** [comment]
DB Sent over email, 

ServiceControl Version 1.8.2
ServicePulse Version 1.3.6

@petersgiles correction in the scenario described:
User archives a error group (wants to ignore all 30 failed messages)
A new failed message comes in the same group (31st message)
User wants to retry only 31st message, he selects the message and retries, Service Pulse says 'Retrying...' but Service Control logs suggest that the retry request was ignored as message belongs to a group which has been archived
User has no way to retry only the 31st message (or to un-archive the error group)

**Comment by petersgiles** [comment]
@gaurav0106 Thanks, I'll take a look at your data and see if there is a workaround

**Comment by johnsimons** [comment]
This sounds like exactly what I was expecting.
Once a user submits a group to be archived, the messages in that group are not a static number, so if new messages come in between the user clicks the button in ServicePulse and ServiceControl gets to do the archiving those messages are included in the archiving, which is exactly what @gaurav0106 is seeing.
Same happens for retrying group or all messages.

@gaurav0106 if you want to have full control on exactly what messages are archived/retried, you will need to individually selecting them.

We could look at introducing an option to retry/archive group between 2 dates.

**Comment by petersgiles** [comment]
@johnsimons I'm actually having a hard time emulating this one. It relies on fairly accurate timing to get it to happen.

To write a test to emulate it I need to 
- Add errors to a queue
- Send Archive request to ServiceControl
- Somehow pause the Archive request while allowing ServiceControl to continue to process messages
- Add more errors of the same type
- Play the Archive request
- Count errors that get archived, which from reading the code, will be the full amount of errors that match the group name

You are right about going to the messages tab and selecting the individual messages that you want archived but once you've archived a group there is no way to restore items from the archive. I think we have a naming issue with the word 'archive' as it implies that you can get them back but we don't seem to offer a mechanism to do so.

**Comment by johnsimons** [comment]
@petersgiles I am not sure why u trying to emulate this ?

Regading an unarchive feature, that has been discussed before, maybe we need to rehydrate that and see what others think?

**Comment by petersgiles** [comment]
@johnsimons just trying to be thorough, I can't find the old unarchive/restore issue, we should link to it here or create a new one

> Service pulse should show some kind of visual cue to let the user know that message was not retried as the whole error group is archived instead of just saying 'Retrying...'and then nothing happens

Referenced this issue with https://github.com/Particular/ServicePulse/issues/224 which is the existing feature request about improving the feedback for user actions.

> Also once a error group is marked as archived there is no way for user to un-archive it which leads to all future failed messages getting stuck as they cant be retried. 

Created a new Restore feature https://github.com/Particular/ServicePulse/issues/241

@gaurav0106 It looks like you can avoid this problem in the future by archiving messages individually or by pausing your endpoint when you want to archive groups of messages from an endpoint that still is producing errors.

**Comment by gaurav0106** [comment]
@petersgiles Sure, that's what I have told everyone in the team to archive individual messages instead of the whole group which works.

But since the button to Archive Group is still there someone might just click it (thinking of modifying service pulse to hide it for now)

Pausing endpoint will not work as I intermittently face transaction enlisting issues due to long running DTC. Since the error type remains the same and keeps happening a few times daily, my concern is that if someone archives this error group then all future messages cannot be retried whether individually or as a group and I have no way of un-archiving the group.

**Comment by petersgiles** [comment]
@gaurav0106 

If you are using a standard install. You can unzip the contents of the attached zip into `C:\Program Files (x86)\Particular Software\ServicePulse\app\js\failed_messages`

It will override the standard failed messages page...it you need to roll back just remove it.

Essentially I've removed the archive button for you

[failed_messages.zip](https://github.com/Particular/ServicePulse/files/77973/failed_messages.zip)

**Comment by petersgiles** [comment]
@gaurav0106 did this solve your problem?

**Comment by gaurav0106** [comment]
Haven't tried yet but am sure it will. Have a higher priority issue to get the service control working as without it nothing shows up in the error tab of Service Pulse
