### ISSUE TITLE
Add the ability to Restore messages from an Archived State

### ISSUE THREAD

**Issue by petersgiles** [Particular/ServicePulse#241]
Sometimes customers archive messages they didn't mean to. There needs to be a way to reverse the archive action.

@sergioc any thoughts on how this might work?

related to: https://github.com/Particular/ServiceInsight/issues/506

**Comment by sergioc** [comment]
@pete as a simple and possibly effective solution, I think we could show an on/off toggle for an archived messages view for each of the failed messages tabs (Error groups and Messages).

When toggled on, SP only shows messages or message groups that were archived, and the action to unarchive next to each item.

**Comment by sergioc** [comment]
Another option is to add 2 new tabs "Archived messages" and "Archived error groups".

**Comment by petersgiles** [comment]
I like the second option or at least the notion that this would appear in another place. I would hate to clutter up the current page...it already feels like its doing too much.

**Comment by sergioc** [comment]
I think the first option has potential to add little clutter as well:

![screenshot 2016-01-05 11 37 16](https://cloud.githubusercontent.com/assets/493451/12107716/5085bfd8-b3a1-11e5-837c-9460dc040c4a.png)

**Comment by petersgiles** [comment]
When you described option 1 I thought you meant that the existing buttons would still be visible.

Using a toggle like that is clean but it is effectively a navigation to a completely different view and therefore more like how I imagined option 2. And because it is pretty much a fresh view I'd be inclined to just navigate to it from the sidebar as there is no related context to the tasks you would perform on the failed messages screen.

**Comment by sergioc** [comment]
Placing on the sidebar is another valid option, though you'd be cluttering it with a new link that is possibly rarely used, but would then permanently show on any view.

How likely are you to jump directly to the Archived messages view from another screen which doesn't relate to failed messages?

**Comment by petersgiles** [comment]
I think its the kind of thing, as an ops person, I would want to go to directly. The scenario I'm imagining would be something like I've just archived a bunch of messages related to database connectivity errors and then the DBA phones up and says OK you're good to replay all those now. 

But I just archived them, so I'd go to the archive screen look at my archive history and restore the relevant messages from the archive screen.

Then I'd navigate to the failed messages screen so I could review them as failed messages and make a choice about what to do as I normally would

**Comment by sergioc** [comment]
> I think its the kind of thing, as an ops person, I would want to go to directly. The scenario I'm imagining would be something like I've just archived a bunch of messages related to database connectivity errors and then the DBA phones up and says OK you're good to replay all those now. 

> But I just archived them, so I'd go to the archive screen look at my archive history and restore the relevant messages from the archive screen.

> Then I'd navigate to the failed messages screen so I could review them as failed messages and make a choice about what to do as I normally would

That's a use case for this issue. But how often would this happen?

**Comment by petersgiles** [comment]
Depends on how many times your OPS guys decide to make half baked decisions I guess.

I'm thinking the frequency would be rare but when you do need to fix it you would want to be a single easily identifiable click away from a clean interface purpose built for correcting the mistake

**Comment by sergioc** [comment]
@petersgiles the single easily identifiable click for a given action is the ideal for all types of actions, not just this one in particular.

If the frequency is rare, this a good example where the 80/20 rule applies, so I think option 2 above sounds like the best candidate solution to resolve this problem.

**Comment by petersgiles** [comment]
So you are saying all on one page but with 4 tabs

**Comment by sergioc** [comment]
honestly, with the small amount of features we currently have, it doesn't make a lot of difference to use tabs or side nav. from a clutter perspective. We can always change later whatever we pick now.

**Comment by petersgiles** [comment]
agreed
function over form with this one
