### ISSUE TITLE
Confirmation should be required to archive messages

### ISSUE THREAD

**Issue by DavidBoike** [Particular/ServicePulse#243]
## Email from customer

> We had an issue where a group of messages got archived by accident. The user meant to hit “retry” but was using a touch screen and hit “archive” instead. As you can assume this caused a bit of an issue.
 
> I was wondering if it would be possible to put a confirmation type window that pops up when you archive a group or batch of messages. From a business perspective, the archive functionality is something we almost never use and we treat this the same way as a “delete”. On the other hand we do retries all the time and there isn’t much of an adverse effect if we hit this button by accident vs hitting the archive button on accident.
 
> Another thought or nice feature would be a “reverse” type button that shows up on that “Latest Events” stream that shows up. Maybe you only get a couple minutes and it only shows up on “archived” messages as this is the only type of actions that I could see someone wanting to reverse.

The last paragraph would speak to a [Google Undo Send / Buyers Remorse Policy](http://www.make-awesome.com/2015/06/how-to-build-gmails-undo-send-feature/) functionality. We also have an existing issue for [restoring messages from an archived state](https://github.com/Particular/ServicePulse/issues/241). But it really shouldn't be that easy to archive messages accidentally in the first place.

A simple JavaScript confirm() would probably do the trick.

related to: https://github.com/Particular/ServicePulse/issues/241

**Comment by johnsimons** [comment]
I wonder if addind better support for touch screens is actually the answer

**Comment by petersgiles** [comment]
@johnsimons better touch and gesture support relates to: https://github.com/Particular/PlatformDevelopment/issues/282

Also this is a starting point for our discussion on things to be aware of with modern apps https://www.google.com/design/spec/material-design/introduction.html

If the customer is desperate to do something while we argue it out a workaround is here https://github.com/Particular/ServicePulse/issues/240#issuecomment-168885443

**Comment by DavidBoike** [comment]
@petersgiles Since #246 was merged we can close this?

**Comment by petersgiles** [comment]
Yes
