### ISSUE TITLE
Failed messages sorted by time sent - ascending

### ISSUE THREAD

**Issue by anetteha** [Particular/ServicePulse#245]
Now users can sort failed messages by 'time sent' and 'message type' using the drop down button at the top of the failed messages tab.

![sort](https://cloud.githubusercontent.com/assets/1644481/12633981/f2ae17ee-c5c9-11e5-87cd-af8ecaa8acf5.PNG)

---

When sorting messages by time sent, they are shown descending. If you can add functionality for showing the messages ascending as well, this would make our ops life a little bit easier.

**Comment by petersgiles** [comment]
relates to: https://github.com/Particular/PlatformDevelopment/issues/282
