### ISSUE TITLE
Remove Open in ServiceInsight Button from Failed Messages Screen

### ISSUE THREAD

**Issue by petersgiles** [Particular/ServicePulse#249]
Reasons
- redundant copy id to clipboard then goto insight
- deployment issue pulse prod insight dev
- uses screen real estate for little value
- confusing to customer who hasn't got insight installed or licensed

**Comment by johnsimons** [comment]
@petersgiles I am not against, but I reckon this should be discussed with @udidahan and @dannycohen since it was introduced as part of the platform and all working together.

**Comment by petersgiles** [comment]
@johnsimons that's pretty much what this PR will be about I guess.

**Comment by WojcikMike** [comment]
For now we decided to leave the button intact
