### ISSUE TITLE
Improve failed messages navigation from activated group state

### ISSUE THREAD

**Issue by sergioc** [Particular/ServicePulse#253]
We currently have a very strange way of of indicating a failed messages group is activated and is being browsed. When inside a group, the only indication of which group is being browsed is in the title of the message list container:

![2016-02-01 at 11 35](https://cloud.githubusercontent.com/assets/493451/12708895/09e1a8f2-c8d8-11e5-951e-2a8f2c3503d3.png)

This is not sufficient to make it clear a group is being browsed, because:

- the title is not emphasized
- the groups/messages tabs are still visible and used to establish parent/child navigation (definitely not adequate
- we have crumble bar which would be a superior solution, but is left totally unused here

All this gives the impression that the user didn't navigate inside a failed messages group

A better solution is to:

- hide "Error groups" and "Messages" tabs when browsing inside a group
- change title of message list to "X failed messages in group"
- emphasize the title of message list
- place the active group name in crumble bar nav and emphasize it there
- make crumble bar links blue to better indicate they're clickable

![screenshot 2016-02-01 11 53 36](https://cloud.githubusercontent.com/assets/493451/12709074/98b40e60-c8da-11e5-8169-6f20d5380ea6.png)

**Comment by johnsimons** [comment]
On top of this, I would also, have the repeated actions that can be performed against a group, they are retry, archive, this links to #280

**Comment by sergioc** [comment]
@johnsimons :+1:
