### ISSUE TITLE
Endpoint Overview last hearbeat received incorrect

### ISSUE THREAD

**Issue by petersgiles** [Particular/ServicePulse#256]
![screenshot 2016-02-05 09 50 10](https://cloud.githubusercontent.com/assets/1644481/12832645/54828ec0-cbef-11e5-868f-76ed24b22dab.png)

The time that the first heartbeat is detected remains unchanged in the active endpoints list.

This time should be updated when a new heartbeat arrives

**Comment by johnsimons** [comment]
U mean it does not auto-refresh ?
Or it does not update at all even after F5 ?

**Comment by petersgiles** [comment]
@johnsimons  it does auto refresh, it does update on f5. it doesn't update the time it auto refreshed correctly. see PR for fix, you're welcome to review
