### ISSUE TITLE
Number formatting

### ISSUE THREAD

**Issue by ramonsmits** [Particular/ServicePulse#261]
Noticed that not all numbers are being formatted:

![capture-number-formatting](https://cloud.githubusercontent.com/assets/152998/12947174/d97e7176-cff9-11e5-97fa-4ea2fe3b5b68.PNG)

Would be nice if numbers would be containing decimal separators for easy reading.

**Comment by sergioc** [comment]
@ramon - how much detail do you need from that indicator? Is it important for you to know the exact number or to have an idea there's a huge amount of messages? If only an idea is needed, then it may not be necessary to take action here.

The reason I ask is because adding separators is tricky. The implementation needs to take into account that In the US commas are used to indicate thousands separators, while in the EU periods are used instead. Not sure about other countries, so ideally it should just try to get the info from the client system's locale settings.

**Comment by mauroservienti** [comment]
> The reason I ask is because adding separators is tricky. The implementation needs to take into account that In the US commas are used to indicate thousands separators, while in the EU periods are used instead. Not sure about other countries, so ideally it should just try to get the info from the client system's locale settings.

@sergioc I'd find hard to define tricky the `globalization` process of an application, I'd expect it to be given. We need to fix this.

**Comment by sergioc** [comment]
@mauroservienti right, but let's make sure we don't show commas as thousands separators for EU users. IMO unless we can easily account for the different numbering formats across the world, this is a nice to have feature.

**Comment by mauroservienti** [comment]
we need to provide config options to users so that they can switch cultures.

**Comment by petersgiles** [comment]
That should be already in the browser...we just have to pay attention to it

**Comment by sergioc** [comment]
> we need to provide config options to users so that they can switch cultures.

And where would we store those preferences? :)

> That should be already in the browser...we just have to pay attention to it

again, If we can get the display to adapt automatically, that would be ideal.

**Comment by ramonsmits** [comment]
Yes, its globalization but as we use English so should focus on US but yes. Formatting is already available and there are javascript libraries available to if we want to make it more fancy.

But this shows how polished the product is. It is not only about this number. It is about all numbers.

**Comment by ramonsmits** [comment]
First, target a specific culture or the browser default. Then in the future you could choose to make it configurable.

**Comment by sergioc** [comment]
> but as we use English so should focus on US

We have a lot of British English users as well. If I'd see one comma separator there, I'd immediately think something is wrong or is weird because I wouldn't expect a count badge to have decimal numbers.

I'm not disagreeing we shouldn't include separators, I'm saying we need to do it right.

**Comment by mauroservienti** [comment]
Globalization rules are there to allow us to do it right without reinventing the wheel.

* Pick the default locale from the browser settings
* Allow the user to change the locale to a desired one
* Store the local in ServiceControl or in a cookie in the browser or in the isolated storage

The same should be applied to dates and times

> But this shows how polished the product is. It is not only about this number. It is about all numbers.

Exactly, it is about perception of quality other than usability.

**Comment by ramonsmits** [comment]
Well, most IT environments use the default and that is en-US also in the UK.

The culture selected in the browser is often for language. Number formatting is often fixed. There are not that many sites that do formatting based on selected language.

Not that it means that we should not do it but it is really, really hard, how are you going to select culture in the UI? By using a flag? Country selector? That doesn't make sense as I prefer English with NL formatting or else US formatting.

For this reason you very often see a "format selector" that is independent from the language.

What templating framework are we currently using? There must already be a formatting option available.

**Comment by WojcikMike** [comment]
We are using angularjs which has formatting for numbers and it is fairly easy. It uses number formatting default to US (Coma as a tousand separator, Dot for decimal separator). You can change the default number formatting by referencing particular js file check [here](http://stackoverflow.com/questions/23409939/angular-js-decimal-numbers-in-european-notation)

From what I saw currently we would need to introduce it to dashboard and menu. As this are the only screens that present numbers.

**Comment by WojcikMike** [comment]
Fixed as part of #362
