### ISSUE TITLE
Number alignment in the failed message grouping list

### ISSUE THREAD

**Issue by mauroservienti** [Particular/ServicePulse#263]
`Count` should be right aligned.

![image](https://cloud.githubusercontent.com/assets/1325611/12970026/79d96ed4-d089-11e5-98dc-649e7df03cae.png)

As I probably get a question about globalisation. We target English so currently we use LTR. RTL/LTR is managed via CSS.

**Comment by sergioc** [comment]
the other columns are not right aligned, why should this one be?

**Comment by mauroservienti** [comment]
it is a number and numbers are not left aligned in a left to right sheet but right aligned by default. And when the list contains very different numbers is really hard to differentiate them:

```
1
12000
234
345765
1237654
```

Human beings are used to:

```
       1
   12000
     234
  345765
 1237654
```

(hope that formatting is persisted as I like :smile: )

**Comment by sergioc** [comment]
> (hope that formatting is persisted as I like :smile: )

OK, you just gave away all of it, it's a personal preference :P

Numbers are not different from words on what concerns reading paths when using western languages. You always read from left to right. Right-aligning in this case will make your reading path zig-zag, which will slow you down, especially when doing quick scanning. In addition, right aligning that column alone would make the layout less harmonious than it is.

**Comment by mauroservienti** [comment]
I completely disagree :) we are trained from the very beginning that numbers are right aligned, when doing calculation must be right aligned otherwise you can do anything, accountants and finance people are all used to right aligned numbers, on every receipt or invoice numbers are right aligned, they are right aligned by default on Google Sheet and Excel as well.

And they are right aligned exactly because it is much easier to read them, to manage and do calculation.

**Comment by ramonsmits** [comment]
Grids are read from top to bottom. Numbers in grids should be right aligned. As it seemed I also created that issue and that is closed I wanted to add the the LTR/RTL comment in this description.

**Comment by ramonsmits** [comment]
This is especially important when numbers are formatted.



```
1
12.000
234
345.765
1.237.654
```

Human beings are used to:

```
        1
   12.000
      234
  345.765
1.237.654
```
