### ISSUE TITLE
Alignment of numbers should be to the right

### ISSUE THREAD

**Issue by ramonsmits** [Particular/ServicePulse#268]
![image](https://cloud.githubusercontent.com/assets/152998/12974364/99ae3918-d0b3-11e5-8618-816559a293ba.png)

As I probably get a question about globalisation. We target English so currently we use LTR. RTL/LTR is managed via CSS.

**Comment by sergioc** [comment]
Duplicate of https://github.com/Particular/ServicePulse/issues/263, closing.
