### ISSUE TITLE
Retry icon is confusing, looks like refresh

### ISSUE THREAD

**Issue by ramonsmits** [Particular/ServicePulse#273]
I didn't know that it was the retry icon. The first thought was that it is to refresh the group statistics in case results are stale.

![image](https://cloud.githubusercontent.com/assets/152998/12977231/ddebd430-d0c9-11e5-8e25-76ea8e74ed77.png)

I now understand it but I think a counter clock wise arrow would make more sense to me. Maybe just using a Play button might make more sense or the combination like the following:

![image](https://cdn1.iconfinder.com/data/icons/squared/64/replay-128.png)

**Comment by petersgiles** [comment]
https://github.com/Particular/ServicePulse/issues/264

**Comment by petersgiles** [comment]
not using icon anymore

**Comment by ramonsmits** [comment]
It returned

![image](https://cloud.githubusercontent.com/assets/152998/21427058/af74f16e-c852-11e6-9bf8-a0616118c5a0.png)

**Comment by WilliamBZA** [comment]
@ramonsmits do you have a suggestion of a better icon we could use?

**Comment by WojcikMike** [comment]
We could go with: http://fontawesome.io/icon/repeat/

Which is similar to Ramons proposition in his [original comment](https://github.com/Particular/ServicePulse/issues/273#issue-132971985)

**Comment by sergioc** [comment]
Agreed. And it looks good in small sizes.
