### ISSUE TITLE
Add badges to menu with totals

### ISSUE THREAD

**Issue by ramonsmits** [Particular/ServicePulse#277]
![image](https://cloud.githubusercontent.com/assets/152998/12983040/c8ba8804-d0e7-11e5-8b4f-0a6f47a2420a.png)

Show badges in menu with totals:

- Endpoints {total monitored down}
- Failed messages {failed message count} / {error groups count}
- Custom checks {failing check count}

This should auto update and go stale (using a question mark) if the data cannot be updated.

**Comment by petersgiles** [comment]
related to https://github.com/Particular/ServicePulse/issues/251
