### ISSUE TITLE
Retry full group button should also be present on details page

### ISSUE THREAD

**Issue by ramonsmits** [Particular/ServicePulse#280]
When you have selected a error group you see an unknown collection of messages part of that error group. If the application operator would decide to retry the group, it first has to go back, scroll to the correct row and click the refresh button.

The operator should be able to replay the failed messages from the details page.

**Comment by petersgiles** [comment]
@ramonsmits Can you explain this one with a few images please?

**Comment by ramonsmits** [comment]
![image](https://cloud.githubusercontent.com/assets/152998/13113261/9b53ee4a-d58e-11e5-890c-1e516e2e4140.png)

The retry group button is missing here. I can only retry by selecting messages and then press *Retry X selected*

Just having a "Retry All" would be nice.

**Comment by ramonsmits** [comment]
Besides that, the image indicates that the version labels don't collaps when the screen width is not enough. That is a bonus point ;-)

**Comment by petersgiles** [comment]
I'm not sure this makes sense on this screen. Would you prefer a select all visible checkbox?

**Comment by ramonsmits** [comment]
@petersgiles A select all always makes sense. Still, that would require two clicks and I don't like clicking. 

Having a select all/none like in most grids would be very nice.

![image](https://cloud.githubusercontent.com/assets/152998/13245341/b9934a90-da0c-11e5-9630-cdf7ae064eda.png)

**Comment by petersgiles** [comment]
@ramonsmits well the first rule of ServicePulse is don't talk about the clicks. 

I have thought about a retry/archive on each row as well. I don't have any plans to do anything about this for 1.4.0 there's enough in there already. I do want to make the retries better though and I can see how this could enhance the experience.

**Comment by petersgiles** [comment]
We actually took care of this when we fixed a few other things in 1.4.0
