### ISSUE TITLE
Lost connection to SC - when browser idle over night

### ISSUE THREAD

**Issue by christoffer-lundqvist** [Particular/ServicePulse#282]
Service Pulse UI looks a bit strange when browser is idle over night. The Pulse UI reports that is has lost connection to SC.

I've checked our SC logs, no failure reported in logs what I can see.
Attached SC logs and Pulse screenshot.
![service pulse when idle for a while](https://cloud.githubusercontent.com/assets/16411065/13002522/642b05ac-d16f-11e5-812f-8b1777889bd4.jpg)

[log.0.txt](https://github.com/Particular/ServicePulse/files/127707/log.0.txt)
[logfile.txt](https://github.com/Particular/ServicePulse/files/127708/logfile.txt)

**Comment by petersgiles** [comment]
relates to https://github.com/Particular/ServicePulse/issues/251
