### ISSUE TITLE
Performance issue when many failed messages

### ISSUE THREAD

**Issue by anetteha** [Particular/ServicePulse#286]
We have one specific Message type which fails a lot over time. 
There are 524 Messages waiting to be handled now.
To view the latest one, we need to scroll. I understand an ascending sort of this view is underway.
When we scroll past approximately 50 messages, Service Pulse hangs, CPU and RAM usage peaks.

The resources are released when the browser is closed.

![snipimage](https://cloud.githubusercontent.com/assets/467227/13074914/eac934d6-d4a7-11e5-97be-6502962b03ed.JPG)

**Comment by petersgiles** [comment]
@anetteha 

What browser are you using?

Can you please send a copy of your Raven Database to peter.giles@particular.net or if it is too big for email we can arrange a place to share like dropbox or google drive. 

Here are some articles that should help you do that
- http://docs.particular.net/servicecontrol/db-compaction
- http://docs.particular.net/servicecontrol/backup-sc-database

Can you tell me what version of ServicePulse you are using? We introduced improvements to the sorting in version 1.3.7 see the releases here https://github.com/Particular/ServicePulse/releases 

You can also follow our release announcements in these places
- https://twitter.com/ParticularNews 
- https://groups.google.com/forum/#!forum/particularsoftware 
- The email address of your organisation's primary contact if you are licensed

**Comment by mauroservienti** [comment]
@petersgiles isn't the default sort in the failed messages view descending? last failed first?

**Comment by anetteha** [comment]
Browser; Internet Explorer 11
ServicePulse v 1.2.1
Unfortunately we cannot send you a ravenDB dump. It is in a production environment, and contains sensitive personal information.

**Comment by WilliamBZA** [comment]
@anetteha are you able to upgrade ServicePulse and ServiceControl to the latest versions? As @petersgiles said, there have been significant improvements made since version 1.2.1 of ServicePulse and a number of performance improvements in ServiceControl too.

**Comment by petersgiles** [comment]
@anetteha as @WilliamBZA suggests upgrading both ServicePulse and ServiceControl will give you the benefits of our continual improvement to our products. You can get them here.
- http://particular.net/start-platform-download
- https://github.com/Particular/ServicePulse/releases
- https://github.com/Particular/ServiceControl/releases

We do release updates regularly and it is worth taking the time to put them into your environment

I will attempt to emulate the issue you are having with some mocked up messages with ServiceControl 1.9.0 and ServicePulse 1.3.8 to see if I can observe any similar behaiours.

In the meantime can you also try Chrome or Firefox and see if you experience the same issue

**Comment by petersgiles** [comment]
@anetteha Using ServiceControl 1.9.0 and ServicePulse 1.3.8 I have reviewed the failed messages screen in Firefox, Chrome, IE 11 and Microsoft Edge. My test sample included a group of 350 failed messages. While there was a bit of ugly flickering in MS Edge the interface performed as expected and didn't show any signs of the problems you described.

I still think your best course of action is to upgrade to the latest versions of these products. If you are able to reproduce the behavior after upgrading we can review your particular circumstances with you.
