### ISSUE TITLE
Login screen

### ISSUE THREAD

**Issue by johnsimons** [Particular/ServicePulse#3]
See balsamic for mockup - https://particular.mybalsamiq.com/projects/operations/10.%20Login

We need to work out the following:
- Where do we store user accounts (some DB, text file, ...)
- Do we provide AD integration
- Is there different user roles
- We need screens to manage users

Is this required for v1?

**Comment by ramonsmits** [comment]
Help us design authorization for ServicePulse and ServiceControl. [We'd appreciate your feedback in our community discussion on our forum](https://discuss.particular.net/t/we-need-your-input-authorization-is-coming-to-servicepulse-and-servicecontrol/4648), on this issue, or privately via <support@particular.net>
