### ISSUE TITLE
Move heartbeats "Configuration" section to the Heartbeats tab

### ISSUE THREAD

**Issue by sergioc** [Particular/ServicePulse#300]
It seems like the "Endpoints overview" and "Configuration" screens have a duplicate purpose, making endpoint management and analysis confusing, and display redundant info.

**Comment by WojcikMike** [comment]
So those screen display slightly different information. On Configuration screen it shows you all available endpoints allowing user to mark which one of them should be monitored. 

On Endpoint Overview one see only monitored endpoints displaying them in active/inactive tabs (the one that reports heartbeats regularly/the ones that doesn't have heartbeat). 

I am not saying that screens should not be merged, but their purpose is different. So we would have to figure out how to make it work on 1 screen
