### ISSUE TITLE
Archiving messages doesn't work

### ISSUE THREAD

**Issue by dsaf** [Particular/ServicePulse#305]
![image](https://cloud.githubusercontent.com/assets/3845650/13923751/cc94fbf2-ef79-11e5-90d0-d4b3c54ea2b0.png)

![image](https://cloud.githubusercontent.com/assets/3845650/13923781/dfaf8202-ef79-11e5-9b73-b0490675be48.png)

Yet the messages are still there.

SC: v. 1.8.3
SP: v. 1.3.7

All I see in the log is this:

> 2016-03-21 15:31:11.0818|26|Info|ServiceControl.EventLog.GenericAuditHandler|Event: FailedMessageGroupArchived emitted

**Comment by WilliamBZA** [comment]
@dsaf Can you upgrade to the latest versions of Service Control and Service Pulse and see if the same behavior occurs?

**Comment by dsaf** [comment]
@WilliamBZA Is there a known fix or it's just a blind experiment? Thank you.

**Comment by dsaf** [comment]
I will have to try, thanks.

**Comment by johnsimons** [comment]
@dsaf we are constantly upgrading these products and fixing issues with them.
There has been quite a few issues related to retries and archiving fixed with ServiceControl in later versions, so it is important to try to stay up to date with the most recent version.

Let us know if the issue persists with the later versions

**Comment by dsaf** [comment]
@johnsimons Fair enough, I will try upgrading.

**Comment by petersgiles** [comment]
@dsaf Did upgrading ServicePulse and ServiceControl fix your issue?

**Comment by dsaf** [comment]
@petersgiles I did not have a chance yet unfortunately. Also I wanted to wait and see what gets included into more recent releases. Would you like me to close this issue and re-open later if needed?

**Comment by petersgiles** [comment]
@dsaf Yes if it's not something you want to pursue right now lets close it
