### ISSUE TITLE
Wrong info displayed for Azure worker role

### ISSUE THREAD

**Issue by yvesgoeleven** [Particular/ServicePulse#309]
I visited a customer yesterday, and they reported an issue between ServicePulse & the azure role host.

Service pulse displays the machine name instead of the role instance id specified by the azure role host. 

![pulse-info](https://cloud.githubusercontent.com/assets/471354/14012200/75aa7b82-f1a4-11e5-859f-e8b0d77a6102.png)

The machine name is pretty useless in azure as machines get (re) provisioned for a variety of reasons (upgrades, failovers, etc..)

I'm raising the issue here as it was detected in pulse, but I realize the problem could lay anywhere in the azure host, service control or in pulse.

I have already looked into the azure role entrypoint, to the best of my knowledge it sets up the information in the appropriate way:

https://github.com/Particular/NServiceBus.Host.AzureCloudService/blob/master/src/NServiceBus.Hosting.Azure/GenericHost.cs#L131

Is this still how it supposed to be done, or did we miss some change?

**Comment by petersgiles** [comment]
AFAIK there's been no change, the quickest way to check is to compare 1.3.8 with 1.4.1, really ServiceControl just gives ServicePulse the data to display. ServicePulse does very little with it and certainly has no special display rules for Azure Hosts

cc/ @Particular/servicecontrol-maintainers

**Comment by ramonsmits** [comment]
Workaround mentioned by @boblangley 

```c#
var displayName = cloudservicename + "_" + roleinstanceid;
configuration.GetSettings().Set("NServiceBus.HostInformation.DisplayName", displayName);
```

**Comment by MarcinHoppe** [comment]
Connects to Particular/NServiceBus.Host.AzureCloudService#49

**Comment by johnsimons** [comment]
@ramonsmits @boblangley This sounds like it was an issue with the host and if so this can be closed?

**Comment by SeanFeldman** [comment]
Whoever it was, RIP Cloud Services
