### ISSUE TITLE
Confirmation messages should be unique and more detailed about what's exactly affected

### ISSUE THREAD

**Issue by sergioc** [Particular/ServicePulse#313]
The current confirmation messages are too generic

![screenshot 2016-03-31 14 48 45](https://cloud.githubusercontent.com/assets/493451/14176139/caa585a4-f74f-11e5-9f82-06e0a8840b7d.png)

In this example, the title should indicate what's being done exactly (Retry messages) and which items are affected exactly (number of messages)

CC // @mauroservienti

**Comment by WojcikMike** [comment]
As a part of #364 I exposed a way to modify title of the modal so than we can fix the title. Updating the message could be easily.
