### ISSUE TITLE
“All failed messages” view list doesn’t update when new messages come through while the view is active

### ISSUE THREAD

**Issue by sergioc** [Particular/ServicePulse#315]
CC // @mauroservienti

**Comment by petersgiles** [comment]
The solution to this requires this https://github.com/Particular/PlatformDevelopment/issues/635 to be done.

**Comment by sergioc** [comment]
Even though the count on the "All failed messages" tab updates?

**Comment by petersgiles** [comment]
@sergioc yep, I have to fake so much stuff so some things work and others don't. Fundamentally the api currently doesn't support what you want to do. Until we fix the API by doing this https://github.com/Particular/PlatformDevelopment/issues/635 it's not going to get any better.

**Comment by WilliamBZA** [comment]
We should verify if this is still a problem

**Comment by WojcikMike** [comment]
I checked it on the latest version and it works as inteded (the data shows automatically)
