### ISSUE TITLE
Better label for the exception message for Failed Message items

### ISSUE THREAD

**Issue by boblangley** [Particular/ServicePulse#319]
![image](https://cloud.githubusercontent.com/assets/2546913/14222307/0f22c762-f824-11e5-97ef-235e4018556d.png)

It is not immediately clear that this is the Exception message. We should either label it as such and keep it visible or give it a tab similar to the other "Show x" options with it selected as the default.

**Comment by sergioc** [comment]
We can fix this via https://github.com/Particular/ServicePulse/issues/308
