### ISSUE TITLE
Clicking the sub-fields of a failed messages should not change the message selection.

### ISSUE THREAD

**Issue by boblangley** [Particular/ServicePulse#320]
![image](https://cloud.githubusercontent.com/assets/2546913/14222338/64bbe2b2-f824-11e5-9df7-bbd3b861dd6e.png)

When I click the field to copy the value the message is selected or unselected. Placing the carrot inside those fields should not change the selection status of the message.

**Comment by petersgiles** [comment]
@boblangley there is an eatClick and isolateClick attribute we could put on each of those panels to prevent this. I think the isolateClick is the one we want
