### ISSUE TITLE
Replace redundant StackTrace header field in Failed Message with button to show tab

### ISSUE THREAD

**Issue by boblangley** [Particular/ServicePulse#322]
![image](https://cloud.githubusercontent.com/assets/2546913/14222435/88d160ae-f825-11e5-9167-830e7f8eeb73.png)

Since we already have a dedicated tab for StackTrace, can we instead just show the button to switch to the tab?

**Comment by petersgiles** [comment]
There's an issue @sergioc has raised last week to redesign this experience

**Comment by adamralph** [comment]
Marked as duplicate.
