### ISSUE TITLE
Failed message item state after archive/retry is too subtle

### ISSUE THREAD

**Issue by boblangley** [Particular/ServicePulse#323]
![image](https://cloud.githubusercontent.com/assets/2546913/14222469/ef223e28-f825-11e5-9b8d-59b8dede09a5.png)

While the label is there indicate the state has changed I was confused at first. I expected the item to disappear and with the checkbox still showing it caused me a short period of confusion. We should find a better way to show the change of state.

Some suggestions (not mutually exclusive/inclusive):

* Collapse the box and include an X to clear the item
* Change the background color or "mute" the entire item
* Remove the checkbox

**Comment by sergioc** [comment]
We probably want the same behavior we currently have when taking action on a group in the Message Groups view.

**Comment by WojcikMike** [comment]
Solved in #364 Now the message after getting the label is being removed from the list. And either will return if it fails again or one could find it in pending retry screen, 

@boblangley please reopen if you disagree
