### ISSUE TITLE
Muting custom checks is confusing

### ISSUE THREAD

**Issue by boblangley** [Particular/ServicePulse#324]
![image](https://cloud.githubusercontent.com/assets/2546913/14222553/c6617f84-f826-11e5-9cd8-bb2a11cb84ca.png)

I clicked the "Mute" button but there is no visual que that the check is now muted. Can I unmute it?

![image](https://cloud.githubusercontent.com/assets/2546913/14222570/de130e7c-f826-11e5-8ace-7096b1657212.png)

This is the log history after muting. Why does the event show up after the mute? Which custom check was muted?

**Comment by WojcikMike** [comment]
@boblangley it seems that when you click Mute it technically do delete on that event. 

For custom events (1 time on startup) that would delete the event and you will never see it (unless you restart a service). For periodic checks it deletes the event but it will be once again there when check report it's status. 

So basically the feature is broken. I wonder if we should allow for muting custom checks at all. 

@Particular/servicepulse-maintainers we need to decide on this, either this need to be fixed to work as expected or it should be removed.

**Comment by WojcikMike** [comment]
The current functionality works as documented. To clarify it a bit, the mute button was renamed to  dismiss.
