### ISSUE TITLE
Separate data inside failed message time stamp

### ISSUE THREAD

**Issue by sergioc** [Particular/ServicePulse#325]
![2016-04-04 at 18 17](https://cloud.githubusercontent.com/assets/493451/14254798/a3baa65a-fa91-11e5-94fc-5583bb36534b.png)

In the metadata element above you can read 3 different types of metadata in one long sentence, which makes it hard to read. This can be presented better by chunking the metadata like this:

- Failed:
- Endpoint:
- Machine:

**Comment by WojcikMike** [comment]
@sergioc your proposition would be easier to ready but also would take more space.

What if we would go with:
Failed:   5 minutes ago    |    Endpoint:   SmoteTest.Server   |   Machine:   RAMON-HOME

In that case:
* we keep the same information 
* the same amount of place taken
* easier to make responsive (replace labels with icons for example)

What do you think?

**Comment by sergioc** [comment]
@WojcikMike my proposal is just to chunk. I didn't propose a specific layout.

In any case, I agree the ideal is to keep as much as possible in one line.

**Comment by sergioc** [comment]
I do not agree with replacing labels with icons on mobile, though, especially not on mobile where you lose the ability to hover on icons to get tooltips.

**Comment by WojcikMike** [comment]
This issue is solved as a part of #364

**Comment by WojcikMike** [comment]
@sergioc please reopen if you think that we should do more in that matter
