### ISSUE TITLE
Service Control URL without Trailing Slash 404s

### ISSUE THREAD

**Issue by colin-higgins** [Particular/ServicePulse#326]
## Problem
If the ServiceControl URL in app.constants does not have a trailing slash:
The concatenation for requests throughout ServicePulse results in 404s.

## Fix
When loading the URL, add the trailing slash if it is missing

**Comment by petersgiles** [comment]
That's what this code is for https://github.com/Particular/ServicePulse/blob/master/src/ServicePulse.Host/app/js/services/services.uri.js

And these tests https://github.com/Particular/ServicePulse/blob/master/src/ServicePulse.Host.Tests/tests/js/services/services.spec.js

Do we need to add a specific scenario to the tests?

**Comment by petersgiles** [comment]
Hmmm weird

![trailing slash](https://cloud.githubusercontent.com/assets/1644481/14371188/8c6fc9b4-fd78-11e5-87f6-46edc67567df.PNG)

**Comment by colin-higgins** [comment]
Is uri.join definitely being used for every concatenation?

**Comment by petersgiles** [comment]
I certainly hope so, can you dig around and find the call that's failing for you?

**Comment by petersgiles** [comment]
looks like there's been a bug with this since 1.4.0. the immediate fix is to have a trailing slash on the url.
i

**Comment by petersgiles** [comment]
It looks like the urls in the routes don't work when extracted to IIS if the trailing slash is missing

**Comment by petersgiles** [comment]
This needs to become
``` C#
templateUrl: 'js/views/dashboard/dashboard.html',
```
that
``` C#
 templateUrl: '/js/views/dashboard/dashboard.html',
```
but it reverts to absolute urls which hurts people who extract to sub directories of IIS


we could add another config param to mark the deployment as relative and then construct a different url.

@colin-higgins what do you think?

**Comment by colin-higgins** [comment]
why something like this pseudo code?
```
if last character of uri is not '/' 
    then add '/'
concatenate uri and relative url
replace all instances of '//' with '/'
```

**Comment by petersgiles** [comment]
yeah that might do it.

I think the whole thing needs to be setup once in the shared data factory. The uri service was a bit of a hack I put together before I looked at making a place to store global variable. I never really liked it but it got the job done.

**Comment by adamralph** [comment]
Moving back to backlog after discussing with @colin-higgins

**Comment by johnsimons** [comment]
@colin-higgins @adamralph so did anyone updated the desk case and gave the answer to the customer ?

**Comment by noctovis** [comment]
I have the exact same issue right now as we're trying to setup SP under IIS. We have different ServiceControl instances per environment, so I have no choice but setting up a SP instance per environment too. Manually modifying the route files and adding that slash hasn't helped either. Also,  modifying the code would make upgrading to new versions terribly hazardous. I keep getting 406 errors and the generic "Route change error"-popup. Any idea if and when this issue will be fixed? Thanks in advance!

**Comment by adamralph** [comment]
Hi @noctovis, thanks for chiming in.

We're treating this as a critical bug and currently working on a fix, to be released ASAP.

**Comment by timbussmann** [comment]
@colin-higgins does this issue regarding the 404 still exists? didn't see any 404s with latest master.

@noctovis I raised an issue about the 406 when hosting in IIS here: https://github.com/Particular/ServicePulse/issues/334

**Comment by johnsimons** [comment]
@colin-higgins @timbussmann should this now be closed ?
