### ISSUE TITLE
Allow grouping of errors by both Endpoint and ExceptionType

### ISSUE THREAD

**Issue by indualagarsamy** [Particular/ServicePulse#330]
Currently, SP allows grouping of errors only by ExceptionType.
However some teams prioritize the errors based on the Endpoint as high priority or low priority error messages that need to be resolved when passing the information to the development team. Currently not having this feature makes it a lot more work for the DevOps team.

Requested by a customer.

**Comment by petersgiles** [comment]
The solution to this requires this https://github.com/Particular/PlatformDevelopment/issues/635 to be done.

**Comment by johnsimons** [comment]
@Particular/servicepulse-maintainers ServiceControl v1.24 has added [MessageType groups for failure messages](https://github.com/Particular/ServiceControl/pull/781), so from a ServicePulse perspective, this can now be added.
For more info ping @boblangley.

**Comment by ramonsmits** [comment]
In https://github.com/Particular/ServiceControl/issues/842 I mentioned behavior I didn't expect.

![image](https://cloud.githubusercontent.com/assets/152998/20257522/68aee166-aa4a-11e6-82ca-b9ada9dc4431.png)

Pulse shows grouping on exception while I expected a group not to contain messages from different logical endpoints.

This issue seems to change that behavior but not sure. Looking at the image would this result in 2 groups?

**Comment by ramonsmits** [comment]
Also noticed this, tested the same with V5 and now I got two groups for the same handler:

![image](https://cloud.githubusercontent.com/assets/152998/20258296/50f0873c-aa4f-11e6-84ab-580b89d892a6.png)

Although seeing this is sort of understandable as the method signature is different its not what I expected as the handler is 'the same'.

**Comment by sergioc** [comment]
You could have the option of "group by endpoint and exception" in addition to "group by exception". So the user can choose which view is more useful.

**Comment by johnsimons** [comment]
I find it difficult to come up with the reason for a user to replay failed messages of the same type for a single endpoint instead of all. But it could be that the user rolls out a fix for a single endpoint and wants to test it in isolation ? Would that be the scenario we are missing ?

**Comment by johnsimons** [comment]
I think maybe we need to go back and revisit the intention of the groupings, @janovesk you were involved in this, maybe you can refresh everyone's minds on the initial intent ?

**Comment by ramonsmits** [comment]
@johnsimons I think what you are saying is probably true for most technical exceptions like deadlocks and timeouts within a system but the current view doesn't give you an idea how many endpoints are affected.

Maybe this is not the way to give that insight and we need a different feature for that.

**Comment by janovesk** [comment]
So you have the same message handler in two logical distinct endpoints @ramonsmits ? I guess that would be possible, but fairly uncommon? What kind of business scenario would that be for?

**Comment by janovesk** [comment]
The original thought for the groupings was to give a better entry point than showing just a long list of failed messages. Grouping by the message handler and type was the suggestions we came up with as a generally good idea. The infrastructure to have several types of groupings is there, though, so we can add more. 

By endpoint might be a reasonable one to implement. Retry everything on a particular endpoint seems pretty broad, though?

**Comment by WojcikMike** [comment]
Actually it is present in the latest version of ServicePulse (checked in 1.12)
