### ISSUE TITLE
Ability to export the failed message information

### ISSUE THREAD

**Issue by indualagarsamy** [Particular/ServicePulse#332]
At the moment, DevOps will have to take the information from ServicePulse for the failed message and copy it to Excel or other tool. 
An Export functionality where the information from the failed message page can be exported will help DevOps to capture the information and then create separate issues and prioritize internally.

**Comment by sergioc** [comment]
@indualagarsamy what kind of export format are you thinking about?

**Comment by kevin-whalley-gc** [comment]
Hi @sergioc,

I currently have my DevOps group generating a spreadsheet of


Priority | Endpoint | # of Messages in Failed Message Group | Message Type (that failed) | Title of Group | Rate of Change in # of Messages Failed (day to day)

I think all users of SP could benefit from at least

Endpoint | # of Messages in Failed Message Group | Message Type (that failed) | Title of Group

**Comment by indualagarsamy** [comment]
@sergioc - I think a .CSV format export would be good.

**Comment by johnsimons** [comment]
So what exactly are we talking about exporting ?
Is it:
- A single message
- A group of messages
- Selected messages
- The groups list

**Comment by johnsimons** [comment]
We should probably have a look at Raygun and see what they provide for inspiration 😉

**Comment by petersgiles** [comment]
@kevin-whalley-gc using the raw data for analysis is not really a monitoring problem, what your suggesting is bleeding over into spending more time with the data to analyze trends etc. Also like @johnsimons indicates its is difficult to capture all user's needs in a generic tool. The best we 

You can query ServiceControl directly using the api we provide here `http://localhost:33333/api` using a tool like [Postman ](https://www.getpostman.com/) or Excel

**Comment by indualagarsamy** [comment]
@petersgiles - while we can't capture all the users' needs, we should be able to grab basic information from our failed messages screen? I am not sure why an export function should be hard. I am curious as to what Raygun does as @johnsimons suggested.
Also the SC API isn't public and is subject to change based on our implementation changes.

**Comment by petersgiles** [comment]
@indualagarsamy my preference would be to provide a separate purpose built querying tool or API that does the export or the integration with 3rd party apps like Raygun, SCOM or any number of product dev ops already use out there.

I don't see us delivering anything but a Mickey Mouse solution by overloading the messages screens with export functions

**Comment by sergioc** [comment]
@petersgiles many tools with UIs provide export functions for users to process the data in other tools that work better in a different context or are better equipped to process the data according to the user's needs. Since SP is about making it easy for the user to access monitoring tools, I wonder if splitting up export functionality or using the API would be the most user friendly option without know more about the problem.

**Comment by sergioc** [comment]
@kevin-whalley-gc considering that the all data could potentially be made visible in the UI itself, why would you need that data exported in the first place?

**Comment by indualagarsamy** [comment]
@sergioc - Based on what I know, information is collected by DevOps so it can be turned into appropriate support incidents for whatever system that's in use for triage.

**Comment by indualagarsamy** [comment]
@petersgiles - You're right.  I agree that there are several possible solutions out there. We'll still need to outline the best way a user can "export" the information from Pulse/SC to whatever system they have in use. It doesn't have to be a button that dishes out .csv files.

**Comment by kevin-whalley-gc** [comment]
@sergioc, it would be great if that information was present in the UI. I respectfully disagree that the condensed set of fields I suggested requires Particular to perform analysis - the intent is that it can be used by others (manually or automated) to perform analysis, which is key to effective monitoring.

**Comment by sergioc** [comment]
> I respectfully disagree that the condensed set of fields I suggested requires Particular to perform analysis

@kevin-whalley-gc are you saying you'd prefer to do the analysis yourself using external tools?
