### ISSUE TITLE
Route Change Error when hosting in IIS

### ISSUE THREAD

**Issue by timbussmann** [Particular/ServicePulse#334]
When hosting ServicePulse in IIS, the page fails to load with a "Route Change Error". 

This issue was described by @noctovis here https://github.com/Particular/ServicePulse/issues/326#issuecomment-214860543:

> I have the exact same issue right now as we're trying to setup SP under IIS. We have different ServiceControl instances per environment, so I have no choice but setting up a SP instance per environment too. Manually modifying the route files and adding that slash hasn't helped either. Also, modifying the code would make upgrading to new versions terribly hazardous. I keep getting 406 errors and the generic "Route change error"-popup. Any idea if and when this issue will be fixed? Thanks in advance!

by inspecting the requests shows that requesting views via xhr returns a HTTP 406 Error from IIS. A fist ~~investigation~~ google search indicates that this is an issue with headers set by angular (e.g. ` $httpProvider.defaults.headers[...]`, see http://stackoverflow.com/questions/33718861/angularjs-on-iis-406-error. Removing these headers indeed resolves the issue and loads the page correctly with IIS.

**Comment by timbussmann** [comment]
@noctovis the fix has been released with version 1.5.2, I hope this resolves your issues with hosting ServicePulse in IIS!

**Comment by noctovis** [comment]
@timbussmann I just tested it and it's working perfectly! Thanks for the quick help!
