### ISSUE TITLE
Static Content Not Minimized for IIS

### ISSUE THREAD

**Issue by colin-higgins** [Particular/ServicePulse#337]
When extracting the embedded resource content from ServicePulse.Host.exe it is not minimized.

**Comment by CRuppert** [comment]
This is useful though. For instance, we have multiple environments. Being able to add links, in the nav, and add add to the scope, like $scope.environment to navigate between different instances is incredibly useful. 

Our company would be sad if this went away. 
Unless multiple environment/instances of ServiceControl are supported inside of ServicePulse.

**Comment by colin-higgins** [comment]
I suppose it would make sense to have it as an option then, though it is low impact either way.

**Comment by WilliamBZA** [comment]
The content is minified now. Closing.
