### ISSUE TITLE
Archive group doesn't archive every message

### ISSUE THREAD

**Issue by pablocastilla** [Particular/ServicePulse#339]
Hi!

I am trying to archive 730 messages but if I click "archive group" it only archives a few of them, around 100 or so.

Thanks

**Comment by johnsimons** [comment]
That is strange @pablocastilla, I have a slight suspicion that could be the indexes in Raven playing up and we need to reset them.
I'll find out what index you need to reset.

**Comment by cjoergensen** [comment]
@pablocastilla  @johnsimons  I've had the similar experience. The issue was solved when we upgraded ServiceControl to a newer version, which properly triggered a refresh of the RavenDB Indexes.

**Comment by johnsimons** [comment]
@cjoergensen @pablocastilla this one is a really annoying issue, it seems the raven indexes in esent get confused and things stop working properly and the only remedy is to trigger a re-index.
The biggest issue is that is really hard to diagnose which index is corrupted.
I wonder if we should recreate indexes on every installation of the product ? This obviously impacts responsiveness of the system with lots of data when it starts up, and it can take a while for the indexes to catch up.

At this stage I have no idea how to proceed, I wonder if an upgrade to raven v3 would address this issue ?

@mauroservienti thoughts ?

**Comment by mauroservienti** [comment]
this is really strange @johnsimons, how can we show the correct number of items in Pulse when querying the group but at archive time we have another number. Are we using the same index for both operations?

**Comment by mauroservienti** [comment]
@johnsimons is it possible that in the [archive query](https://github.com/Particular/ServiceControl/blob/master/src/ServiceControl/Recoverability/Grouping/Archiving/ArchiveAllInGroupHandler.cs#L23) we're missing stuff?

Do I read it correctly if I say that we archive failed messages only if the status is `Unresolved`, meaning that if something has been retried once, but failed again, it won't be archived?

**Comment by johnsimons** [comment]
@mauroservienti 

> Are we using the same index for both operations?

no, we are not

> Do I read it correctly if I say that we archive failed messages only if the status is Unresolved

Yes that is correct

> meaning that if something has been retried once, but failed again, it won't be archived?

no that is not true, the message gets reset to unresolved again

**Comment by WojcikMike** [comment]
@johnsimons regarding
> Are we using the same index for both operations?
> no, we are not

Should we? Now when 1 index is corrupted we get mismatch of information (number of messages and actual retry all functionalities). While when using 1 index we at least don't cause confusion. The underlying problem would still be present

**Comment by johnsimons** [comment]
@WojcikMike it is not possible, we use facets to do the stats and then a normal query for the rest and those can easily get out of sync

**Comment by harumph** [comment]
> I'll find out what index you need to reset.

@johnsimons Any progress on this?

I am experiencing this issue too, I wanted to try out resetting:

* http://localhost:33333/storage/indexes/FailureGroupsViewIndex
* http://localhost:33333/storage/indexes/FailedMessageViewIndex
* http://localhost:33333/storage/indexes/FailedMessages%2fByGroup

Should I try and reset any of the others?

I'm on ServicePulse v1.6.6 and ServiceControl v1.22.0

**Comment by WilliamBZA** [comment]
@harumph The indexes you need to reset depends on the views that are stale.

It's not a bad idea to start with the `FailureGroupsViewIndex` and see where that takes you.

Is there a reason you are not able to update SP and SC to their latest versions?

**Comment by harumph** [comment]
@WilliamBZA Thanks, I should be able to try it today.

No specific reason for not upgrading, just waiting for the green light to do it. It has been on the backlog for a while.

**Comment by WilliamBZA** [comment]
@harumph Let me know how it goes.

I hope you get the green light soon: We've added a whole bunch of improvements and enhancements in the latest few versions 😄 I highly recommend staying current if possible.

**Comment by harumph** [comment]
@WilliamBZA I only get the maintenance window today, reindexing helped.

It took about 15 minutes for the indexes to get repopulated but its working like a charm at the moment.

**Comment by WilliamBZA** [comment]
Glad to hear it @harumph. Let's hope Raven can keep up with your workload this time...

**Comment by WilliamBZA** [comment]
Closing this as it seems to have been handled by the index reset.
