### ISSUE TITLE
Timeouts and timeoutsdispatcher appear in the endpoint overview

### ISSUE THREAD

**Issue by pablocastilla** [Particular/ServicePulse#340]
Hi!

Timeouts and timeoutsdispatcher appear in the endpoint overview, but they don't generate heartbeats so always stay "in red"

I think they should appear there.

**Comment by johnsimons** [comment]
So the only way I see this happening is because a timeout failed and was sent to the error queue and then ServiceControl picks it up and registers that as an endpoint.
@pablocastilla do you think that is what happened ?

**Comment by pablocastilla** [comment]
That's exactly what's happening :)

**Comment by johnsimons** [comment]
In that case this is more a ServiceControl issue, I'll move it to ServiceControl repo.
