### ISSUE TITLE
Issues with error messages grouping in SP

### ISSUE THREAD

**Issue by seanfarmar** [Particular/ServicePulse#341]
Feedback from a client (Swiftness) I got in a meeting with them:
1. The Grouping in Pulse does not work so well .

For example : bad grouping 1, bad grouping 2
1. We suggest to set “Messages Count Of Retry” And “Retry Every X Seconds/Minute” in settings options .
2. We suggest to build new button to “Cancel Retry” .
3. The Archive option in pulse does not work so well.

For example we press “Archive all messages” , and after that we get new exceptions , we press “Retry all failed messages” and then suddenly all the old messages we archives come back.

We suggest also to make new “Archive messages” button that archive all the current messages and not the message type .

![bad grouping 1](https://cloud.githubusercontent.com/assets/125256/15042433/bca2dd12-12bb-11e6-8280-c96331420781.PNG)
![bad grouping 2](https://cloud.githubusercontent.com/assets/125256/15042432/bca2ad92-12bb-11e6-8518-374eac3121f7.PNG)

**Comment by noamtzu** [comment]
Thank you sean.

**Comment by johnsimons** [comment]
> For example we press “Archive all messages” , and after that we get new exceptions , we press “Retry all failed messages” and then suddenly all the old messages we archives come back.

This sound like this bug we fixed - https://github.com/Particular/ServiceControl/releases/tag/1.6.3

**Comment by johnsimons** [comment]
The rest of this issue is quite hard to work out exactly what is wrong and what is recommended instead

**Comment by WilliamBZA** [comment]
I'm going to close this issue @seanfarmar 

1. Archive feature should be more reliable now that Raven has been upgraded
2. It is not possible to cancel retries at all
3. Retry Every X Seconds/Minute and Messages Count of Retry would require a major overhaul to the retry pipeline.

If you feel that any of these features are still valuable, I suggest we open a platdev issue and drive it through one of the bucket squads.
