### ISSUE TITLE
Update available notification, mismatch

### ISSUE THREAD

**Issue by johnsimons** [Particular/ServicePulse#342]
The following 2 notification messages should display the same text:
![image](https://cloud.githubusercontent.com/assets/122651/15100889/a7b6a13a-15c3-11e6-98d9-d190c6ead057.png)

I propose we update ServicePulse text to say "(Upgrade to v1.14.0)" same as ServiceControl Management Utility.

This was raised by a user.

**Comment by WojcikMike** [comment]
Fix was deployed with version 1.6.6.
