### ISSUE TITLE
Support .NET Core

### ISSUE THREAD

**Issue by WilliamBZA** [Particular/ServicePulse#348]
ServicePulse can be deployed separately to ServiceControl and thus has a different set of blockers preventing the adoption of .NET Core.

Since Nancy is [also close to supporting Core](https://github.com/NancyFx/Nancy/issues/2220), we are well placed to support it with relatively low friction.

Since Pulse will be the _only_ product of ours that supports .NET Core, the benefit provided is low so this should be low priority too.
- [ ] Investigate blockers

**Comment by johnsimons** [comment]
@WilliamBZA ServicePulse can be easily deployed on any non Windows system, all you need is a webserver to host for the files.
Not sure I see the value here.

**Comment by WojcikMike** [comment]
I agree with @johnsimons as ServicePulse is a SPA application without any backend we can host it on any webserver that supports html+js

**Comment by WilliamBZA** [comment]
Of course, that's exactly why I say this will be low friction! But there's more to it than just hosting the files on a webserver. The design of including transformation of config files as part of the setup project makes this hard for users. There's manual work involved and there will be bugs with "why is my version incorrect".

My suggestion is to spend some time making the deployment process cross-platform too, so that we have a complete solution - not just a workaround. Like I said, low priority, but brushing it off as "it's just html and js" is not good enough unfortunately.

**Comment by levimatheri** [comment]
Any progress on this? @kbaley @WilliamBZA

**Comment by HEskandari** [comment]
@levimatheri ServicePulse can run on Linux as a SPA application. In fact, we have docker images for it for both [linux](https://hub.docker.com/r/particular/servicepulse/) and [windows](https://hub.docker.com/r/particular/servicepulse-windows) on Docker Hub. Would that work for you?

**Comment by levimatheri** [comment]
Nice 👍🏽 yes that works. Thank you

**Comment by WojcikMike** [comment]
Should we then close this issue?

**Comment by WilliamBZA** [comment]
Yes, closing.
