### ISSUE TITLE
NoIE redirect doesn't work with IIS hosting in a sub directory

### ISSUE THREAD

**Issue by rlaveycal** [Particular/ServicePulse#354]
## Who's affected

Any users using Internet Explorer less than version 9 and is running ServicePulse within a sub directory

## Symptoms

If the browser is an unsupported version of Internet Explorer and ServicePulse is hosted within a sub directory, the browser will be redirected to the root directory looking for a file `NoIE.html` in the root.

## Original bug report

The browser check in Index.html
```html
    <!--[if lt IE 9 ]>
        <script type="text/javascript">
            window.location = '/NoIE.html';
        </script>
    <![endif]-->
```

assumes that pulse is in the root folder. It needs changing to be a relative url
```javascript
            window.location.href = 'NoIE.html';
```

**Comment by WilliamBZA** [comment]
Thanks @rlaveycal. I've made the change and submitted a PR. Just waiting for another set of eyes to confirm.

**Comment by WilliamBZA** [comment]
@rlaveycal ServicePulse version `1.6.2` has just been released and should resolve this.
