### ISSUE TITLE
Only show endpoint instance name when more than one instance exists

### ISSUE THREAD

**Issue by boblangley** [Particular/ServicePulse#357]
For heartbeats, only show the instance portion of the name (e.g. endpoint@instance) when more than one instance exists.

**Comment by WojcikMike** [comment]
@boblangley when I tested it on my environment 2 instances of the same endpoint using RabbitMQ as a transport (shared queue) on the list of endpoints I can't see 2 endpoints, and only 1 endpoint is being returned from Service Control. 

So i think we need to capture it on SC level and then return it. At that point we should display it in a proper way.

**Comment by sergioc** [comment]
@boblangley aren't there any situations where it's useful to know the instance name even if there's only one instance for that endpoint?

E.g. quickly determining what to look for if an instance has an issue, based on whether all endpoints on that instance aren't sending heartbeats or only one endpoint is giving problems?

**Comment by boblangley** [comment]
@WojcikMike Were the 2 instances installed to different folder paths? If not then the Core / SC treats them as the same instance.

**Comment by boblangley** [comment]
@sergioc `Instances` are physical instances of a logical `Endpoint`. What you describe seems like a "machine level" view of our endpoints. Perhaps a different view would be helpful for that?

Users on Azure cloud services for instance do not care about the machine it is running on. At best they want to know the instance, and if they are not scaling out then it is less useful. Perhaps this should be considered as an option? This request came indirectly from a customer on Azure.

At any rate we should wait to decide until after https://github.com/Particular/PlatformDevelopment/issues/782 is done.

**Comment by WojcikMike** [comment]
>@WojcikMike Were the 2 instances installed to different folder paths? If not then the Core / SC treats them as the same instance.

@boblangley thanks for that information I was able to test it on my environment. At the moment we display:

![image](https://cloud.githubusercontent.com/assets/604826/15799095/caff3f6a-2a51-11e6-8c68-873c1ad8fe2c.png)

So without a doubt we need instance information displayed if present. What should be the format of such name I am not sure. However I can't see and instance information returned from SC. My current result of calling: /api/endpoints returns this info (RabbitMQ transport):

{"id":"474be432-69ef-5cd2-6028-3d3fd5f405c7","name":"Samples.PubSub.Subscriber2","host_display_name":"MWOJCIK","monitored":true,"monitor_heartbeat":true,"license_status":"unknown","heartbeat_information":{"last_report_at":"2016-06-04T10:36:56.1124378Z","reported_status":"beating"},"is_sending_heartbeats":true},
{"id":"327043c6-15b5-5bf3-65a1-52209ea059ab","name":"Samples.PubSub.Subscriber2","host_display_name":"MWOJCIK","monitored":true,"monitor_heartbeat":true,"license_status":"unknown","heartbeat_information":{"last_report_at":"2016-06-04T10:36:49.4867192Z","reported_status":"beating"},"is_sending_heartbeats":true}

And it also goes back to every other aspect of displaying endpoint (failed message also have only information "Samples.PubSub.Subscriber2" without any indication about instance). 

I understand that most likely people will deploy endpoint instances to different boxes, so information:
endpointName@machine is sufficient. But in terms installing instances to the same box it is not clear

**Comment by WilliamBZA** [comment]
Will be released in 1.35.2
