### ISSUE TITLE
Revisit buttons/links styling and semantics

### ISSUE THREAD

**Issue by ramonsmits** [Particular/ServicePulse#360]
![image](https://cloud.githubusercontent.com/assets/152998/16158250/bb5d3254-34bc-11e6-8cde-8aee27e0e3b4.png)
- [ ] Change current view buttons to be direct links (and style the links to look identical to the current)
- [ ] Improve consistency for UI action elements (e.g. buttons that look like links)

**Comment by sergioc** [comment]
@ramonsmits why?

**Comment by WojcikMike** [comment]
## Semantics
From a semantic perspective those two "actions" represent some thing that happens. Links (anchors) should be used to refer to content like: more details, article or as in this case show messages.

When buttons should be used for any action like: submit, delete, save/update, retry etc.

So for me View Messages should be an <a> element that would allow you to open messages in a new tab, while Retry and Archive a <button>

## Look
Now beside semantic there is also a visual aspect. In our case all 3 elements are in fact buttons :) but they don't look like ones but rather resemble links. How should they look I am not entirely sure, I would lean towards keepin buttons looking somehow like buttons and links to look like links. In which case people using the app will better understand what the application does.

**Comment by sergioc** [comment]
@WojcikMike there's no prescribed actions to use for a button or a link.

Choosing between links or buttons is generally based on how you want to distinguish primary actions (e.g. calls to action, default actions) from secondary (least used actions or actions we don't want to encourage), contrast between possible actions (if all actions were represented by buttons, then it would a pain to locate and differentiate because the page would look too uniform) and aesthetics (if all actions were represented by buttons, then the page would look heavy and unappealing).

**Comment by WojcikMike** [comment]
@sergioc I usually assume that link can be clicked without causing any harm or change, while button cause an action. But I am no expert in therms of UX and a lot of web pages don't follow my rule either way.

**Comment by sergioc** [comment]
@ramonsmits given the latest changes in SP, do you think your concern is still applicable?

**Comment by ramonsmits** [comment]
@sergioc Yes, still applicable. The following screenshots are taken from the current version.

![image](https://cloud.githubusercontent.com/assets/152998/25937108/bd446784-362a-11e7-9eef-55f09c79a62c.png)

![image](https://cloud.githubusercontent.com/assets/152998/25937137/d1005918-362a-11e7-8c6e-50ec5496a58a.png)


Also note:
- The different styles in casing
- Different icon styles for retry operation

**Comment by sergioc** [comment]
> Different icon styles for retry operation

Makes sense.

> Different styles in casing

I don't understand what do you mean.

> Different button styles

I don't see a problem with that other than being a style nitpick. A border-less button can be just as effective to signify it produces an action, as long as the label's semantics are correct. Several websites and apps use that pattern and/or mix and match. We don't have evidence it's causing problems for us specifically.

**Comment by sergioc** [comment]
Closing for the reasons presented previously. @ramonsmits please re-open if you feel strongly against this.
