### ISSUE TITLE
Add linting to build tools to enforce consistency in JS

### ISSUE THREAD

**Issue by WilliamBZA** [Particular/ServicePulse#368]
There is some inconsistency in the way JS is written in different places (optional ;, linebreaks, etc)

Adding a linter (e.g. JSHint or JSLint) would help with the consistency by performing static analysis on the JS code and raising warnings where the code does not match.

There are three steps to this process:
1. Add the linter of choice
2. Decide which rules should be applied in the static analysis
3. Fix the codebase where rules are already broken

I propose that the first 2 steps get done as part of this issue, and the third gets tackled as it's own issue once we have an idea of how many rules are being violated.

@Particular/servicepulse-maintainers What do you think? I also think the first 2 steps are small enough to be done under maintainer budget.

**Comment by WojcikMike** [comment]
:+1: for what you just wrote. I installed once: https://visualstudiogallery.msdn.microsoft.com/ede12aa8-0f80-4e6f-b15c-7a8b3499370e 

But then I was down to deciding on the rules so I gave up for now. But we should do it.

**Comment by kbaley** [comment]
Agreed. When this is done, is it possible to have the build break if the static analysis fails?

**Comment by WilliamBZA** [comment]
> When this is done, is it possible to have the build break if the static analysis fails?

I think that's the end-goal. Shorten the feedback cycle.

**Comment by WojcikMike** [comment]
The linter was added some time ago, and all errors were fixed. Now however it was not added to the builder so we currently have 2 errors. I will fix them and add the lint to be part of build infra to not let the code

**Comment by WojcikMike** [comment]
Done as part of: https://github.com/Particular/ServicePulse/pull/1075
