### ISSUE TITLE
Should we upgrade to ES6?

### ISSUE THREAD

**Issue by WilliamBZA** [Particular/ServicePulse#369]
ES6 has a lot of really nice features that make coding in it a pleasure.

This issue is a marker for a discussion around whether there is value in upgrading. I will post a quick pros on cons list as the first reply.

Note that this issue is not in progress yet. Just adding it while it's on my mind.

**Comment by WilliamBZA** [comment]
Pros:

* Classes would make our controllers smaller and neater
* Arrow functions would make our controllers neater
* Modules would make our dependencies much and more explicit

Cons:

* Extra build step
* Can't just include all the files in the installed
* Changes to the development experience
* Angular looks super hacky when using ES6. It's doable, but is non-obvious in some places

**Comment by WojcikMike** [comment]
Without giving it to much though, what do you mean by:
> Can't just include all the files in the installer

**Comment by WojcikMike** [comment]
With regards to:
> Angular looks super hacky when using ES6. It's doable, but is non-obvious in some places

What if we consider ditching Angular in favor of a framework that will not be abandoned in few months ;)

**Comment by kbaley** [comment]
> What if we consider ditching Angular in favor of a framework that will not be abandoned in few months ;)

Choosing a framework is a crap shoot at the best of times. And it seems even more so in JavaScript. I'm surprised Angular is hacky in ES6 though, or is that just version 1.2?

As for switching to ES6, I admit I haven't been following it as much as I should be. Do we have an idea of what the effort would be to switch? Or can we do some sort of timeboxed prototype to help determine this?

**Comment by WilliamBZA** [comment]
> As for switching to ES6, I admit I haven't been following it as much as I should be. Do we have an idea of what the effort would be to switch? Or can we do some sort of timeboxed prototype to help determine this?

Let's discuss that when this item gets moved into progress.

**Comment by johnsimons** [comment]
ES6 + TypeScript is now in use
