### ISSUE TITLE
Add package manager to web libraries

### ISSUE THREAD

**Issue by WojcikMike** [Particular/ServicePulse#370]
At this moment we are using Nuget to manage dependencies. However for web frameworks we don't have anything. So for upgrading angular, jquery or any other web library we have ot do it manually. 

I think we should introduce something like bower, so that we can update used libraries easily.

@Particular/servicepulse-maintainers what do you think?

**Comment by WilliamBZA** [comment]
:100: :+1:

**Comment by kbaley** [comment]
What @WilliamBZA said

**Comment by WojcikMike** [comment]
Done
