### ISSUE TITLE
Create user stories for Pulse features to drive development

### ISSUE THREAD

**Issue by WilliamBZA** [Particular/ServicePulse#376]
This is an important step in driving the direction of the product. Coming up with a cohesive set of user stories that map to both required and mission functionality will help make sure that the correct features are being prioritized and each feature implemented is in line with the vision of the product.

/cc @Particular/servicepulse-maintainers

**Comment by sergioc** [comment]
Closing given that product dev mostly takes place outside the sphere of maintainers responsibility.
