### ISSUE TITLE
Update License Agreement

### ISSUE THREAD

**Issue by indualagarsamy** [Particular/ServicePulse#385]
Related to https://github.com/Particular/NServiceBus/pull/4280, we are working to change the license agreement and privacy policy to be compliant. 

Once we have the right text, the ServicePulse Installer will need to reflect that.

cc / @kbaley

**Comment by indualagarsamy** [comment]
The correct link to the evaluation license agreement is here:
https://docs.google.com/document/d/1ulv4Q0jIe8CZZt3p97Y_jLFEFWigL5dtWd3fLCXRqAw/edit#

**Comment by gbiellem** [comment]
@indualagarsamy I'll update it. Same question as in SC - When do you want this released?
