### ISSUE TITLE
Configuration screen is unclear

### ISSUE THREAD

**Issue by mikeminutillo** [Particular/ServicePulse#392]
The configuration screen contains a list of endpoints with an On/Off toggle. It does not state what those On/Off toggles actually turn on or off. 

This is changing whether an endpoint is monitored but that isn't very clear. Maybe we should add some text explaining what the buttons do. 

---

See [this google group discussion](https://groups.google.com/forum/#!topic/particularsoftware/x9j3U4qjgb4) for evidence of this lack of clarity.

**Comment by mikeminutillo** [comment]
![image](https://cloud.githubusercontent.com/assets/124014/21900586/4a16cd42-d8ec-11e6-9eb9-febc73aa5ec0.png)

**Comment by sergioc** [comment]
@mikeminutillo there's https://github.com/Particular/ServicePulse/issues/300 already open. We're already aware of the confusing purposes. Merge #392 with #300 and dissect the problem in one issue?

**Comment by WojcikMike** [comment]
I think that making this toggle more descriptive might be way faster than solving #300 issue

**Comment by sergioc** [comment]
@WojcikMike agreed. Adding column headers is even simpler.
