### ISSUE TITLE
Linking to specific error group

### ISSUE THREAD

**Issue by stimms** [Particular/ServicePulse#394]
It would be great if going into an error group would update the url with a unique identifier so we could link people to the group of errors.

**Comment by WilliamBZA** [comment]
Thanks @stimms. That's a great idea! I'm not sure when we'll get to it, but I'll make sure we don't forget about it.

**Comment by WilliamBZA** [comment]
PR created. Awaiting review. Once reviewed a release should come out shortly.

Thanks again for the input @stimms!

**Comment by WilliamBZA** [comment]
Released! [1.7.1](https://github.com/Particular/ServicePulse/releases/tag/1.7.1) adds this feature.

Thanks again for the feedback @stimms!

**Comment by stimms** [comment]
Woo, I'll update tonight. Thanks for being so accommodating.
