### ISSUE TITLE
Inconsistent message counts

### ISSUE THREAD

**Issue by stimms** [Particular/ServicePulse#396]
When retrying a group of messages the message counts do not update in a consistent fashion. 

In this screen capture a group with several hundred messages was retried (before recording begins, sorry). The count in the Failed Messages menu item was updated. However The count of messages in the group was not, it still claims 193 messages. Clicking into the group continues to show the incorrect count despite there being only a single message matching the group. 

![mismatch](https://cloud.githubusercontent.com/assets/153912/22371972/9a0777ea-e457-11e6-8f1b-db8333d78c4e.gif)

**Comment by stimms** [comment]
ServicePulse v1.7.0  •  ServiceControl v1.33.0

**Comment by WilliamBZA** [comment]
I think this is related to #397, so I'm closing this one until we resolve the bigger issue.
