### ISSUE TITLE
Groups do not appear to be fully archived

### ISSUE THREAD

**Issue by stimms** [Particular/ServicePulse#397]
This may be the same issue as #396 but it is just different enough that I'm not sure. 

![incorrect group retry](https://cloud.githubusercontent.com/assets/153912/22375350/e4f3ae04-e466-11e6-8743-6ac9ac7f329c.gif)

As you can see archiving the group does not seem to archive all members of the group. However clicking into that group shows no messages. Archiving it again has no effect and now we have this Heisen-group with has both 192 messages and 0 messages in it.

**Comment by WilliamBZA** [comment]
@stimms Can you confirm the versions of SP and SC that you're using?

**Comment by stimms** [comment]
Sorry, ServicePulse v1.7.0  •  ServiceControl v1.33.0

**Comment by WilliamBZA** [comment]
Damn 😄. Let me see what I can find for you.

**Comment by WilliamBZA** [comment]
@stimms Can you enable the Raven Studio and check if you have any stale indexes? https://docs.particular.net/servicecontrol/use-ravendb-studio

**Comment by WilliamBZA** [comment]
It could also be raven db thinking that indexes are up to date when they actually aren't. If you have no stale indexes I'll give you a potential workaround for now.

**Comment by stimms** [comment]
I was able to find some time to open up raven db studio today and have a poke about. I wasn't sure what a stale index would look like so I followed the instructions at https://docs.particular.net/servicepulse/troubleshooting to reset it. Upon restart all my failed message groups seem to have disappeared. I imagine the indexing will happen in the background and it is just a question of being patient.

**Comment by WilliamBZA** [comment]
@stimms that is correct. Raven has an annoying habit of being "potentially consistent" instead of eventually. In some cases it marks indexes as non-stale, when they are still, in fact, stale. This means the values never update and the values we display are inconsistent and incorrect.

This could stem from how we use Raven, as we've definitely seen less of this happening in the newer features we implement (we tend to rely less on indexes where possible) but still have cases where this happens.

Did this also resolve #396?

**Comment by stimms** [comment]
I left raven for 12 hours to see if there was any improvement in the index. However it still shows as stale. The collection over which it is indexing is a mere 2000 documents and the machine is certainly not very busy. I would have expected this to have been reindex long ago. In the logs I do see this warning 

![image](https://cloud.githubusercontent.com/assets/153912/22593077/1e5b8bb2-e9da-11e6-9905-8acd7b55625c.png)

I tried creating a new index using the same definition as failed message groups but that also remains stale. 
![image](https://cloud.githubusercontent.com/assets/153912/22593210/bc5b0694-e9da-11e6-979a-d8a699206d66.png)

At the moment I'm considering just leaving it over the weekend but because the collection of documents is so small I can't imagine that more time is all that is needed to correct this. 

Also for future reference the staleness of index can be found by clicking into the index and looking under the results pane
![image](https://cloud.githubusercontent.com/assets/153912/22592446/0c69999c-e9d7-11e6-800c-8fe4490314e7.png)

**Comment by WilliamBZA** [comment]
@stimms Is there a way that you could forward us the raven database so that we can inspect it? You can send it to support@particular.net.

**Comment by WilliamBZA** [comment]
As a note: this could be similar to this issue: https://github.com/Particular/ServicePulse/issues/339

**Comment by stimms** [comment]
Our database is quite large 50+gig and contains data I don't think we could let out of our grasp. What we ended up doing was standing up a new instance of service control on the same hardware and giving the existing one fake queues to watch for audit and error. This allows us to keep the instance and messages from it available for investigation and the fresh database isn't currently corrupt. I'm thinking we may have run out of disk space at some point and ravendb didn't react well to that.

**Comment by WilliamBZA** [comment]
That's pretty big.

After pointing it at the fake queues, was SC ever able to stabilize and catch up on those indexes?

**Comment by stimms** [comment]
I gave it 72 hours and it didn't update. The collection was only a couple of hundred failed messages so there must have been something more seriously busted about raven in this case. I'd chalk this up to RavenDB's sketchy definition of ACID. I'd be happy to close this issue as being localized to my environment.

**Comment by WilliamBZA** [comment]
@stimms Would it help if we got on a video call and took a look at the environment and problem? If that's possible (depending on the sensitivity of the client and data), send a mail through to the support mail for my attention, and I'll make sure we get a slot scheduled.

If it's not possible, feel free to close this. Although I'd much rather prefer us actually finding out what is going wrong so that we can fix it for you (and for others too).

**Comment by WilliamBZA** [comment]
I'm guessing you're quite busy so a support ticket is a bit tricky at the moment. I'm closing this for now, but would still love the chance to get a look at your environment when you get a chance.
