### ISSUE TITLE
Format messagebody for easier readability

### ISSUE THREAD

**Issue by knordum** [Particular/ServicePulse#398]
When viewing the messagebody in ServicePulse it would be nice to have the option to turn on "pretty- print" for easier reading of the message. Should support both xml and json.

**Comment by WilliamBZA** [comment]
That's a nice suggestion @knordum. We'd have a bit of difficulty if the messages come through serialized in anything other than XML or Json. Let me think about it for a bit.

**Comment by WilliamBZA** [comment]
Should be something we can do. Good idea.
