### ISSUE TITLE
Improve URL structure for failed messages screen

### ISSUE THREAD

**Issue by WojcikMike** [Particular/ServicePulse#402]
Relates to: 
 * #399 
 * #381 

There is a need to analyze and possibly modify the URL paths to the different failed message screens.

Previously our URL's looked as follows:

- `/failedMessages` - failed messages screen
- `/failedMessages/{{id}}` - one message screen

Becasue @WilliamBZA made a [PR (#399)](https://github.com/Particular/ServicePulse/pull/389) to provide deep linking groups he used "our" url path, so currently it looks like this:

- `/failedMessages` - failed messages screen
- `/failedMessages/{{id}}` - failed messages screen with a group of given id selected

Which means that we lacked URL for this feature. Now because on our page we show a bit more than only failed message (as it can also be archived message, or successful processed message) @WojcikMike decided to go with the following path for individual message URL paths in [PR (#381)](https://github.com/Particular/ServicePulse/pull/381):

- `/message/{{id}}`

However, URLs often are segmented to mimic navigation. From this perspective, `/failedMessages` is parent of both groups and individual messages. So @sergioc argues that both children should be nested under the parent to mimic the nav structure. Also avoid using two words in "oneWord" to improve legibility of the URL, as well as caps. So  use this structure in the end:

- `/failed-messages` (default view) or alternative show directly `/failed-messages/groups`
- `/failed-messages/groups/{{group.id}}`
- `/failed-messages/message/{{message.id}}`

**Comment by sergioc** [comment]
@Particular/servicecontrol-maintainers please comment.

**Comment by mikeminutillo** [comment]
Whatever we decide, I would like to see it happen before the initial release of this feature. I don't want to release a feature to support deep linking and follow it up with a new deep linking scheme.

Just to throw another option out there, one of the things we did when adding the grouping was to include the capability name *Recoverability* in the urls. So it would be:

- `/recoverability/groups`
- `/recoverability/groups/{{group.id}}`
- `/recoverability/message/{{message.id}}`

This has the slight downside that *Recoverability* is not actually a word :(

**Comment by sergioc** [comment]
> This has the slight downside that Recoverability is not actually a word

nor does it represent what those pages contain.

**Comment by WojcikMike** [comment]
Today we had a call with Sergio and we agreed to use the following url scheme:
* /failed-messages/groups
* /failed-messages/groups/{{id}}
* /failed-messages/all
* /failed-messages/archived
* /failed-messages/message/{{id}}
* /failed-messages/pending-retries

**Comment by WilliamBZA** [comment]
I'm not a fan of `/endpoints-overview`

root `/endpoints` already implies an overview, doesn't it?
