### ISSUE TITLE
Prevent accidental usage of ES6 features

### ISSUE THREAD

**Issue by timbussmann** [Particular/ServicePulse#410]
Some supported browsers (I'm looking at you, Internet Explorer) don't support ES6 features like certain string operations or arrow functions and there is always the risk of breaking those browsers (e.g. see https://github.com/Particular/ServicePulse/issues/408). Those usages are sometimes hard to detect, as most likely no developer will use IE for smoke testing. 

For some reasons, neither VS nor R# are able to warn me about ES6 usage, although they are configured to not use ES6. Not sure whether this is just my machine, but even then, we don't enforce R# usage, so that doesn't seem to be a reliable option anyway.

Are there options to detect language feature usage which break browser compatibility, preferably automatable which we should use?

**Comment by mikeminutillo** [comment]
Is it worth investing in adding a transpiler like  [Babel](https://babeljs.io/) into the build chain to allow ES6 in code assets rather than defending against them?

It might be a bit messy as they're all built on nodejs (AFAIK) and we embed the js assets into the compiled Pulse assembly.

**Comment by timbussmann** [comment]
> Is it worth investing in adding a transpiler like Babel 

I think it would even make more sense to go with typescript then?

**Comment by WojcikMike** [comment]
@WilliamBZA as we are using Babel now, can we close this issue?
