### ISSUE TITLE
Dismiss button is not obvious, change its design and location to make it a button

### ISSUE THREAD

**Issue by ramonsmits** [Particular/ServicePulse#413]
I can't really say that the size and position of the Dismiss button make it a button. Took me a while to realize that is a button to dismiss that box.

![image](https://cloud.githubusercontent.com/assets/152998/23299534/29831934-fa82-11e6-81ca-a1f286ffcc38.png)

Wouldn't it be better if it is similar to this? Combined with an icon?

![image](https://cloud.githubusercontent.com/assets/152998/23299538/2ceddf78-fa82-11e6-97fc-030417eff849.png)

**Comment by sergioc** [comment]
This issue would need additional user testing for a proper validation - best done in combination with other tasks.

Not all buttons need an icon and it certainly shouldn't be a requirement to make a button.

For the time being, I propose enlarging the button a bit to make it more prominent - #415

**Comment by sergioc** [comment]
https://github.com/Particular/ServicePulse/pull/415 released, closing.
