### ISSUE TITLE
View in ServiceInsight button is not working

### ISSUE THREAD

**Issue by WojcikMike** [Particular/ServicePulse#416]
When opening message page (/failed-messages/message/id) clicking on button: View in ServiceInsight makes no effect. It should open ServiceInsight with the details of that message.

**Comment by gbiellem** [comment]
@WojcikMike  Are you aware that functionality only works  if the ServiceInsight MSI install has been run. 
It registers the URL protocol handler.  See https://github.com/Particular/ServiceInsight/blob/master/src/Setup/ServiceInsight.aip#L639.

**Comment by WojcikMike** [comment]
I was aware that SI needs to be on the box. Thanks for the clarification. In this case simply the event handler for button was detached ;) So no matter what, it wasn't working.

**Comment by sergioc** [comment]
Can we give an error message indicating SI is needed?

**Comment by gbiellem** [comment]
> for the clarification. In this case simply the event handler for button was detached

@WojcikMike  ah ok, I saw this [checkin](https://github.com/Particular/ServicePulse/pull/417/commits/161adb9f2a8c16cb261baf71b92727ebf34aec8f) and assumed you were removing it. My mistake.
