### ISSUE TITLE
Discuss a UI functional testing strategy

### ISSUE THREAD

**Issue by sergioc** [Particular/ServicePulse#419]
There's currently no UI functional testing strategy in place for SP. Though SP is not a terribly complex product, there's still important UI issues that are either missed when doing a new release (e.g. #416) or completely fly under the radar (e.g. #409).

The @Particular/servicecontrol-maintainers should discuss what's the most effective functional testing strategy (manual or automated) to improve quality.

**Comment by mikeminutillo** [comment]
@sergioc can you add a link to the meeting recording that we had about this and update the issue with a summary of the next steps?

**Comment by sergioc** [comment]
@mikeminutillo I don't have a link to the meeting recording.

Attending the meeting were me, @gbiellem, @mikeminutillo and @WilliamBZA. We agreed that we need to step up on UI testing. 

@WilliamBZA will open a new issue to describe a test environment setup procedure that he mentioned during the call.

**Comment by WojcikMike** [comment]
@mikeminutillo I looked at sp slack channel and here it is: https://drive.google.com/file/d/0B5pzkqQRf-JhMndGcGVVSmo4WDQ/view

**Comment by udidahan** [comment]
Is this small enough to be happening outside of plat-dev?

**Comment by sergioc** [comment]
@udidahan it was a 1hr discussion. I've added the discussion label to make it clear.
