### ISSUE TITLE
Group failed messages by EndpointName

### ISSUE THREAD

**Issue by sudheendra-bhat** [Particular/ServicePulse#427]
At present it is possible to group failed messages by "Exception Type and Stack Trace" and "Message Type". When message assembly is shared across several applications within a company it becomes difficult to look precisely or retry failed messages specific to an application. Group by endpoint name can help in this case.

**Comment by WilliamBZA** [comment]
Thanks @sudheendra-bhat, that's a good idea. I'm sure we can put something together around this.

**Comment by mikeminutillo** [comment]
@WilliamBZA did this get closed as a part of the [1.39 release of SC](https://github.com/Particular/ServiceControl/releases/tag/1.39.0)?

**Comment by WilliamBZA** [comment]
Yes it did
