### ISSUE TITLE
Retries stays in queued state forever.

### ISSUE THREAD

**Issue by pablocastilla** [Particular/ServicePulse#431]
I have requested a retry for a group and it doesn't work. The group stays in queued state forever.

![pulseproblem](https://cloud.githubusercontent.com/assets/8155105/24457083/6f4cdc8e-1495-11e7-8742-35d6c5ab946c.PNG)
.

I also see these exceptions:
System.InvalidOperationException: Map-Reduce index corruption detected.
   at Raven.Database.Indexing.IndexStorage.CheckMapReduceIndexState(IDictionary`2 commitData, Boolean resetTried) in c:\Builds\RavenDB-Stable-2.5\Raven.Database\Indexing\IndexStorage.cs:line 250
   at Raven.Database.Indexing.IndexStorage.OpenIndexOnStartup(String indexName) in c:\Builds\RavenDB-Stable-2.5\Raven.Database\Indexing\IndexStorage.cs:line 143

***************

ServicePulse v1.8.4  •  ServiceControl v1.38.0

Upgraded from Pulse 1.6.7 - SC 1.23

**Comment by pablocastilla** [comment]
ok, now it seems they have been launched. It has taken a lot of time.

Is this normal?

**Comment by WilliamBZA** [comment]
What transport are you using here @pablocastilla?

**Comment by pablocastilla** [comment]
Hi William!

Thanks for helping.

The transport is msmq

**Comment by WilliamBZA** [comment]
Pity, I would have had an answer for you but not for MSMQ.

The map reduce exception is a likely candidate here, but I haven't seen that happen before. Is there anything else interesting in the logfile? Could you perhaps share the logfile somewhere or send it through to us?

**Comment by sergioc** [comment]
@pablocastilla are you still experiencing this issue? If yes, are you able to share the logfile with use (shared privately)? If not, OK to close for now?

**Comment by pablocastilla** [comment]
Hi!

I am not in that company any more.

@ismaelhamed do you still have this problem?

Thanks

**Comment by ismaelhamed** [comment]
@pablocastilla we haven't seen this in a while and we use that feature often. @sergioc you can close it, thanks.
