### ISSUE TITLE
Present license information and support options in UI

### ISSUE THREAD

**Issue by ramonsmits** [Particular/ServicePulse#436]
After upgrading to the latest version of RavenDB I noticed 2 buttons at the botton. These are *red* when no license is found thus no support options except community is available and *green* if there is a license:

## No license

![image](https://cloud.githubusercontent.com/assets/152998/24706320/8ee91ba0-1a0f-11e7-8a54-3eba9558c7d9.png)

## Valid license

![image](https://cloud.githubusercontent.com/assets/152998/24706317/8bac048e-1a0f-11e7-999e-1d46d5b4b052.png)

Having a similar experience in ServicePulse would be interesting. It would be easier for our customer to get support if ServicePulse would contain some links and their support options explained with the SLA info based on their license.

**Comment by WojcikMike** [comment]
We should take into consideration the fact that SC does expose license information: #383

**Comment by sergioc** [comment]
Currently being handled via https://github.com/Particular/CustomerSuccess/issues/982
