### ISSUE TITLE
Dismissed groups don't stay dismissed

### ISSUE THREAD

**Issue by stimms** [Particular/ServicePulse#438]
We have a collection of groups where we've reprocessed the messages or archived them but the groups keep coming back. 

![groups come back](https://cloud.githubusercontent.com/assets/153912/24799944/37f9f600-1b5b-11e7-8a69-fde2bbafe113.gif)

I checked and nobody around the office has been casting revive and to make doubly sure I repainted all our D20s to only have 1s and 2s so their spell wouldn't work anyway. 

***************

*Technical information if reporting bug:*

- **ServicePulse version:**  ServicePulse v1.9.1
- **ServiceControl version:** ServiceControl v1.39.0

**Comment by WilliamBZA** [comment]
This was a bug introduced in v1.39.0 of SC which was subsequently fixed in version 1.40.0.

Sorry about that! 😞

**Comment by stimms** [comment]
Upgraded and confirmed that it fixed the problem. Thanks!
