### ISSUE TITLE
Retry custom selections of multiple messages

### ISSUE THREAD

**Issue by outofcoolnames** [Particular/ServicePulse#440]
At the moment, the retry options are: Retry 1 or more selected messages or retry all. This is fine when dealing with a few messages but it is not great when there are many failed message.

Providing shift-click de/selection would give users fine-grained selection when they need it.

**Comment by WilliamBZA** [comment]
@outofcoolnames Are you referring to the list of all messages? Or within a group of messages?

**Comment by outofcoolnames** [comment]
@WilliamBZA within a group of messages

**Comment by sergioc** [comment]
Both views share similar functionality on what concerns selecting and taking action on individual messages.

@outofcoolnames can your further elaborate on why exactly would you want to select 10, 50 or 200 messages instead of retrying just 1?

**Comment by outofcoolnames** [comment]
@sergioc 
Working with individual messages is absolutely fine. I was in a scenario this morning where a dependant service was unavailable due to a deployment, several hundred messages failed due to this. My options in this scenario would be to either individually select 1 failed message at a time or to retry all. I was concerned with retrying all of them at once as they were quite weighty messages and that they would negatively impact the destination system. I would appreciate a middle ground option of being able to quickly select multiple messages for retry. An option would be to allow for message selection by holding down the left mouse button

**Comment by WojcikMike** [comment]
Hi @outofcoolnames would grouping by endpoint solve your issue?
![image](https://cloud.githubusercontent.com/assets/604826/25382709/20f6e87a-29b9-11e7-80ad-ac3eb13e0326.png)
We have grouping by endpoint address which should allow you to retry only the messages related to given endpoint.

**Comment by outofcoolnames** [comment]
Hi @WojcikMike,
Not really, I would like the ability to retry batches of the 890 messages in your example.

**Comment by WojcikMike** [comment]
Ok, your response made me re-read your comment. In the end, you want to retry all impacted messages but you don't want to do it in one go, but rather divide it into smaller chunks so that the system performance is not impacted. Now I understand the issue

**Comment by outofcoolnames** [comment]
@WilliamBZA precisely

**Comment by sergioc** [comment]
@outofcoolnames still trying to better understand your idea.

Is the idea to test retrying more than 1 message at a time, but not all, and see what happens? Or, with the expectation that nothing will go wrong, trickle message retries so that they don't overload the system - i.e. manually retry one batch of messages at a time, a few times until all are retried?

**Comment by outofcoolnames** [comment]
@sergioc the latter would be the main use case in my scenario. These are messages that I know will work but I don't want to overload the destination system by retrying all of them

**Comment by WilliamBZA** [comment]
@outofcoolnames We can add a "Shift-click" to select multiple rows, which is probably a good idea anyway (and one we'll probably implement, thanks!).

I'm interested in your concern about overloading the destination system.  If you were to retry all 890 messages at once, the concern is your destination system would be overloaded. Is overloading perhaps related to concurrency? Perhaps you are experiencing something like deadlocks which are resolved by only processing say 2 messages at a time?

Is this perhaps related to why the messages are appearing in the SC error queue? If you examine your log file, are you seeing a lot of FLR or SLR errors that are related to processing too many messages at once? If yes, there might be a simple solution to tweak the concurrency of the endpoint. It might also be worthwhile investigating the handlers to ensure that they aren't trying to do too much or escalating transactions unnecessarily to DTC.

**Comment by outofcoolnames** [comment]
@WilliamBZA great to hear that about the "Shift-click". The destination system in this instance is a multi-tenant asp.net website with a few webapi controllers. I'm posting to these webapi controllers from the handler. This website was unavailable due to maintenance so the posts failed and built up in the PSP error queue. The risk I faced by re-queueing all the messages at once was the increased likelihood of users experiencing timeouts on the website due to the webapi controllers receiving lots of calls within a short period of time, persisting them to the database, using all the DB connections in the process

**Comment by WilliamBZA** [comment]
@outofcoolnames It will likely be a while before we implement the shift-click - I have no idea when - but it's on our radar for now.

In the meantime (and at the risk of derailing this issue), it sounds like reducing the max-concurrency on your processing endpoint would help you with your immediate problem. If you set the concurrency right down to 1 message at a time, you would only ever have 1 request from the retry process at a time being executed against your website which should reduce the impact on the users. If the website is generally tempermental, this reduction will also help users in case that there are a bunch of messages for whatever reason in the future.
