### ISSUE TITLE
Document Installation Parameters

### ISSUE THREAD

**Issue by TraGicCode** [Particular/ServicePulse#443]
It would be nice if the following commandline parameters were documented for the silent installation of servicepulse

INST_PORT_PULSE and INST_URI

.\Particular.ServicePulse-1.9.1.exe /Quiet /Log C:\t.txt INST_PORT_PULSE=12345 INST_URI=http://woot.com:33333/api/

**Comment by dvdstelt** [comment]
I created a doco PR, but will leave it up to maintainers to decide what to doco and what not : https://github.com/Particular/docs.particular.net/pull/2790

**Comment by WilliamBZA** [comment]
Thanks @dvdstelt and @TraGicCode

**Comment by WilliamBZA** [comment]
Documentation merged and released. Thanks again guys!
