### ISSUE TITLE
Add retry button on message on *All failed messages* view

### ISSUE THREAD

**Issue by ramonsmits** [Particular/ServicePulse#445]
Describe your problem / suggestion / idea / feedback here.

This is the current *All failed messages* view:
![image](https://cloud.githubusercontent.com/assets/152998/26719268/24a410b8-4784-11e7-9468-58d53e6f0ac4.png)

If you want to retry just a single message you first need to tick the checkbox and then select *Retry {0} selected* which is a bit annoying.

It would be nice to just have a button to retry a message with one click.

***************

*Technical information if reporting bug:*

- **ServicePulse version:** 1.9.1

### Solution

- Show message retry button when hovering each message row

**Comment by sergioc** [comment]
@ramonsmits what's the exact use case for retrying one message at a time?

**Comment by WojcikMike** [comment]
Will be released with 1.15
