### ISSUE TITLE
No hints for button actions

### ISSUE THREAD

**Issue by SimonCropp** [Particular/ServicePulse#452]
## Who's affected

* Users accessing ServicePulse on a small screen

## Description

On a small screen the icons shown on the navbar do not have any description of what they do.

![no-hints](https://user-images.githubusercontent.com/122666/27168103-94d0a15e-51e7-11e7-96d5-fdaa7a749db5.gif)

**Comment by sergioc** [comment]
The best fix is to switch directly from full labeled nav directly to collapsed nav since the icon-only nav is meant for mobile devices which don't have hover states to provide hints.

**Comment by WilliamBZA** [comment]
This has been fixed and will be released as part of 1.9.2

**Comment by SimonCropp** [comment]
@WilliamBZA thanks
