### ISSUE TITLE
Allow fine-grained access control

### ISSUE THREAD

**Issue by SzymonPobiega** [Particular/ServicePulse#453]
Allow setting up authorization on per-endpoint (or per-endpoint-group) basis. This is useful in a multi-team environment where each team wants to retain control over their retry/audits but the monitoring aspect can be centralized.

Related support case: https://eu1.salesforce.com/apex/Case?num=00028071

**Comment by WilliamBZA** [comment]
We have a platdev issue to track this, I propose we close this one and let the platedev process run it's course. https://github.com/Particular/PlatformDevelopment/issues/231

Any objections @SzymonPobiega?

**Comment by ramonsmits** [comment]
Help us design authorization for ServicePulse and ServiceControl. [We'd appreciate your feedback in our community discussion on our forum](https://discuss.particular.net/t/we-need-your-input-authorization-is-coming-to-servicepulse-and-servicecontrol/4648), on this issue, or privately via <support@particular.net>
