### ISSUE TITLE
Annotations for retry groups

### ISSUE THREAD

**Issue by tmasternak** [Particular/ServicePulse#457]
The problem to solve is the coordination of DevOp work at the level of retry groups. In order to share and coordinate work the users should be able to add tags and comment/notes to retry groups.

This is part of feedback from [UMG](https://github.com/Particular/LaunchWave.DevOpsAdvancedMonitoring/issues/73)

**Comment by WilliamBZA** [comment]
@tmasternak Can this be covered by https://github.com/Particular/ServicePulse/issues/283?

**Comment by tmasternak** [comment]
👍 for tags. This would add notes/comments on top of that.

**Comment by WilliamBZA** [comment]
The linked #164 covers comments via descriptions. Closing this one as all items are covered by other issues.
