### ISSUE TITLE
Housekeeping policy to automatically cleanup decommissioned/deleted endpoint instances

### ISSUE THREAD

**Issue by ramonsmits** [Particular/ServicePulse#468]
Implement a housekeeping policy, remove decommissioned/inactive/dead instances that are reported dead for more than a defined period (day, week, etc.).

This is based on customer feedback.

**Comment by ramonsmits** [comment]
Customer was experiencing this again and auto cleanup/hide would benefit customer that are running endpoints in an elastic environment.

**Comment by WilliamBZA** [comment]
[I spiked a way](https://github.com/Particular/ServiceControl/pull/3546) to achieve this using a new setting. The code uses a background task to check once an hour if there are any instances that are staler than the threshold. If they are staler than the threshold, they get removed. The spike wasn't completed but can be used as a reference point in the future.

**Comment by PhilBastian** [comment]
ServicePulse 1.42.1 and ServiceControl 5.9.1 have addressed this issue, by allowing elastic scale environments to be marked as such, which is then treated differently on the heartbeats screen. Monitoring for offline endpoints now goes away automatically after 1 hour for all endpoint types.

For more information you can see the [updated documentation](https://docs.particular.net/monitoring/heartbeats/in-servicepulse)
