### ISSUE TITLE
Archiving group of messages finished, but after refresh all failed messages are still in Servicepulse

### ISSUE THREAD

**Issue by gemas** [Particular/ServicePulse#489]
Describe your problem / suggestion / idea / feedback here.

You group the messages based on Message type.
Then I click on Archive group of 2325 messages
You see the progress (slowly) going to 100% and see message that archiving is completed
You click on Dismiss button
You don't see the message group anymore.
You leave the page and go back to the failed message group page.
=> The group of 2325 messages is back on the page.

*Technical information if reporting bug:*

- **ServicePulse version: 1.9.1
- **ServiceControl version: 1.41.2

**Comment by WilliamBZA** [comment]
Does the group _ever_ disappear from the failed message page? E.g. does it still show in the failed messages page now? Are you able to share the log file?

**Comment by WilliamBZA** [comment]
I'm assuming this is no longer a problem. If it is, reopen and let me know the current state.
