### ISSUE TITLE
Failed Messages list - multiple selection

### ISSUE THREAD

**Issue by HEskandari** [Particular/ServicePulse#491]
When selecting items to be retried/archived in ServicePulse the items need to be selected one by one which is very painful.

Considering how long the list could be, would be great to have a multi-selection option like in Gmail where you select the first item and shift-click the last item and all the items in between are checked.

Lacking the granular group by options this will be very helpful, but still valuable even with better grouping features.

**Comment by WilliamBZA** [comment]
Thanks @HEskandari. We have this captured in [this](https://github.com/Particular/ServicePulse/issues/440) issue.

**Comment by HEskandari** [comment]
I thought we have but my initial search didn't reveal that issue. Thanks for your reply.

**Comment by sergioc** [comment]
I've renamed the title of the other issue to make it easier to find in the future.
