### ISSUE TITLE
Selected grouping option isn't very obvious

### ISSUE THREAD

**Issue by ramonsmits** [Particular/ServicePulse#523]
In the upper right, the selected grouping option is visible but it isn't obvious that it is selected.

![image](https://user-images.githubusercontent.com/152998/31336130-c7f85450-acf5-11e7-9a2d-b9017778045e.png)

Alternatively, all options could be a sort of radio box at the top just above the groups itself.

Also, each group options should result in making that more obvious in each entry. In the folowing screenshot the grouping option is "Endpoint Instance". 

![image](https://user-images.githubusercontent.com/152998/31336256-4efbd918-acf6-11e7-9bf5-cf497c53916e.png)

Looking at the entries I think I expected the instance identifiers to be prefixed with a label.

**Comment by WilliamBZA** [comment]
> I expected the instance identifiers to be prefixed with a label.

I would love to be able to give that to you, but if it isn't sent through with the messages that end up in ServiceControl then we can't display it. In your screenshot the only data we had was HostIDs, so that's what had to be used.

**Comment by WilliamBZA** [comment]
We could maybe detect if it's a host ID and then not include those messages in the groups?

**Comment by sergioc** [comment]
I can see how it's hard to miss in such a wide screen. How about just placing the "Group by" menu next to the title "Failed message groups"?

**Comment by sergioc** [comment]
Issue closed until there's more evidence that this is a problem.
