### ISSUE TITLE
ServicePulse installer does not allow to change configuration (1.10.1)

### ISSUE THREAD

**Issue by ramonsmits** [Particular/ServicePulse#556]
I wanted to update the ServiceControl url via the installer but the **Modify** button is disabled. 
![image](https://user-images.githubusercontent.com/152998/33340957-bd32feda-d47d-11e7-8136-d2b38394f77b.png)

I expected the following dialog to be accessible via the installer:

![image](https://user-images.githubusercontent.com/152998/33340850-7c8577f0-d47d-11e7-8fa7-dd5b0197f22c.png)

### Uninstall / Install

It is required to first uninstall ServicePulse and then install ServicePulse again to modify the urls via the dialog.

### Manual editing of configuration file

The only way to modify it is when you know where ServicePulse is installed and to modify the configuration file directly which is:

    C:\Program Files (x86)\Particular Software\ServicePulse\app\js\app.constants.js

Currently it has the following content:

```
;(function (window, angular, undefined) {  'use strict';

    angular.module('sc')
        .constant('version', '1.10.1')
        .constant('showPendingRetry', false)
        .constant('scConfig', {
            default_route: '/dashboard',
            service_control_url: 'http://zolder.corp.nbraceit.com:33333/api/',
            monitoring_urls: ['http://zolder.corp.nbraceit.com:33633/']
        });

}(window, window.angular));
```

**Comment by tmasternak** [comment]
This will be a bit less painful when this is released https://github.com/Particular/PlatformInstaller/pull/220.

Still it will not allow `Modify` on installation.

**Comment by mauroservienti** [comment]
ServicePulse `1.20.0` supports changing connections configuration via the ServicePulse configuration screens. Closing.
