### ISSUE TITLE
Remove decimal point for Heartbeats and Failed Messages counters

### ISSUE THREAD

**Issue by sudheendra-bhat** [Particular/ServicePulse#563]
Remove decimal point for Heartbeats and Failed Messages counters

![image](https://user-images.githubusercontent.com/5879266/33476961-2b293136-d684-11e7-8beb-7d7d221ec695.png)

***************

-ServicePulse version 1.10.2
-ServiceControl version 1.43.4

**Comment by WilliamBZA** [comment]
Thanks @sudheendra-bhat, we'll get right on that!

**Comment by WilliamBZA** [comment]
PR submitted, waiting for review
