### ISSUE TITLE
ServicePulse does not show connectivity issues 

### ISSUE THREAD

**Issue by ramonsmits** [Particular/ServicePulse#569]
SC.Monitoring isn't installed so cannot be running but the ServicePulse monitoring screen isn't mentioning this

![vmconnect_2017-12-04_13-15-04](https://user-images.githubusercontent.com/152998/33552628-e7af3e40-d8f5-11e7-9458-31d4e43eb4ee.png)

***************

*Technical information if reporting bug:*

- **ServicePulse version:** 1.10.2
- **ServiceControl version:** 1.43.4

**Comment by WojcikMike** [comment]
The current message looks like this:
![image](https://user-images.githubusercontent.com/604826/38619660-f502290c-3d9c-11e8-8d46-38504588588e.png)

What is more we are showing a toast when the connection cannot be established
