### ISSUE TITLE
Failed Count Tags showing X.0 instead of X

### ISSUE THREAD

**Issue by TechneWare** [Particular/ServicePulse#572]
Just some feedback that for some reason with the ServicePulse v1.10.2  version, all # of issues counters are showing as 1.0 instead of 1.  I can't imagine a case where I would have a fractional issue. 

But otherwise looks good so far.

***************

*Technical information if reporting bug:*

- **ServicePulse version:** 
- **ServiceControl version:**

**Comment by WojcikMike** [comment]
Thank you @TechneWare for raising this. It seems to be connected to this issue: https://github.com/Particular/ServicePulse/issues/563 but I will double check that. we have the fix ready but we will look into the second issue that you created

**Comment by WojcikMike** [comment]
Sorry @TechneWare I missed that issue, but after we fixed #563 this issue no longer occurs. I verified it today on version 1.12. Because of that I am closing this issue. Thanks for raising it.
