### ISSUE TITLE
Upgrade to ServicePulse v1.10.2  overwrites configured registry values

### ISSUE THREAD

**Issue by TechneWare** [Particular/ServicePulse#573]
I had setup my Service Pulse to be accessible on port 80 and exposed it our internal staff, but after upgrading it had overwritten the values in the registry and caused it to no longer be accessible.

Minor issue as I just had to re-update the registry but it seems it should respect changed values.

I used the platform installer to do this.

***************

*Technical information if reporting bug:*

- **ServicePulse version:** 
- **ServiceControl version:**

**Comment by WojcikMike** [comment]
Thank you for reporting this issue, I will look into a way to preserve the value between installs

**Comment by WilliamBZA** [comment]
@TechneWare I'm resurrecting this from the dead, I hope that's ok.

Can you remember which registry value you had to change? The URL Port reservations should be maintained between installations.

**Comment by tmasternak** [comment]
@WilliamBZA I've done some investigations and it looks that it's not the ulr registration that is the problem but the fact that we do not check the current SP port during upgrades. The value used in the installer is always 9090 even if SP has been already installed on some other port. In such case, if the user does not spot this difference during the installation the SP will switch to default port after the update. 

I think this is the problem that @TechneWare experienced.

**Comment by sergioc** [comment]
Fixed in upcoming 1.15 release
