### ISSUE TITLE
ServicePulse installer doesn't show its 'pulse' icon in the Windows uninstall screen

### ISSUE THREAD

**Issue by ramonsmits** [Particular/ServicePulse#585]
![image](https://user-images.githubusercontent.com/152998/33942475-4def9250-e016-11e7-9ea3-426d9aec9d21.png)

***************

*Technical information if reporting bug:*

- **ServicePulse version:** 1.11.0
- **ServiceControl version:**

**Comment by WilliamBZA** [comment]
@Particular/platforminstaller-maintainers I have no idea where to change this. Do you guys know where to look? If you point me in the right direction I can fix.

**Comment by WojcikMike** [comment]
Works for me:
![image](https://user-images.githubusercontent.com/604826/33986282-6b2bc22e-e0bd-11e7-8e72-d1f98bb2e87b.png)

**Comment by timbussmann** [comment]
also seems to work on my machine although I did update an existing installation. @ramonsmits is that a new installation or did you upgrade as well?

**Comment by ramonsmits** [comment]
@WojcikMike Yes, SP works for you, but your SCMU is broken :-) So maybe nothing is wrong and its an issue in Windows 10.

**Comment by sergioc** [comment]
Closing since it seems outside our possibilities.
