### ISSUE TITLE
Version check not performed via SSL

### ISSUE THREAD

**Issue by ramonsmits** [Particular/ServicePulse#589]
A version check is performed but this is not done over SSL

- http://platformupdate.particular.net/servicepulse.txt

**Comment by WilliamBZA** [comment]
Step 1: We need to somehow host this file over HTTPS. Do the @Particular/deployment-maintainers or @Particular/platforminstaller-maintainers know how we can change this behaviour?

**Comment by dbelcham** [comment]
Not sure that deployment-maintainers will be of much initial help. Where does this file reside? Is it part of the website? Stored in S3?

**Comment by kbaley** [comment]
Pinging @Particular/website-backend-maintainers and @Particular/website-frontend-maintainers. One of them should be able to set up SSL for this.

**Comment by DavidBoike** [comment]
Looks like that CNAMEs to S3. Wouldn’t it be simpler to use the S3 name that would natively support SSL? I don’t think we’ll be able to have S3 use our wildcard cert. It could be possible, but even if it is, why bother?

**Comment by dbelcham** [comment]
I think to use a cert on S3 (digging the depths of my memory from setting up my blog on AWS) you had to setup CloudFront (CDN) over S3 and setup your cert for that.

**Comment by DavidBoike** [comment]
So can the URL used be https://s3.amazonaws.com/platformupdate.particular.net/servicepulse.txt ?

**Comment by kbaley** [comment]
That would probably work but looks kind of fishy to anyone monitoring the network requests.

**Comment by DavidBoike** [comment]
> Specifying a schema http in front of the schema less urls

This will result in mixed mode warnings in the browser, or may not even work.

**Comment by mattcanty** [comment]
I'm seeing this cert issue with `v3.6.2` but there is no file `app/js/services/services.platform-update.js`.

I'm actually investigating an issue with duplicate results in failed message groups. My suspicion is that this failing request is causing a 2nd request to be made to `/errors` and the result is concatenated.

![image](https://user-images.githubusercontent.com/2089581/54190055-fe1db680-44aa-11e9-97a4-e2bea60788c0.png)

**Comment by WilliamBZA** [comment]
@mattcanty The double message has been fixed in version [1.17.0](https://github.com/Particular/ServicePulse/issues/726)
