### ISSUE TITLE
Archive all doesn't work if there are a lot of messages to archive

### ISSUE THREAD

**Issue by JSCProjects** [Particular/ServicePulse#592]
When there a lot(> 1000) of messages to archive not all the messages are archived and the UI still shows the wrong mount of records. I know it should be eventually consistent but our Administrators are complaining and they don't trust the message count anymore. For more info look at the screenshots

Screenshots: 
![image](https://user-images.githubusercontent.com/19533149/35139630-453db560-fcf4-11e7-9aab-c31588ae3a08.png)

![image](https://user-images.githubusercontent.com/19533149/35139698-9474626e-fcf4-11e7-8e88-43d7911653a0.png)

*Technical information if reporting bug:*

ServicePulse v1.12.0  •  ServiceControl v1.46.0

**Comment by WilliamBZA** [comment]
Hi @JSCProjects 

Can you give me a bit of info about the type of machine that ServiceControl is running on? ServiceControl uses RavenDB as it's internal database and the numbers that you see are a result of the RavenDB indexes. We tend to see that these differences between index values are more common when the ServiceControl machine is starting to struggle with the throughput.

[Here](https://docs.particular.net/servicecontrol/capacity-and-planning) is some guidance on doing capacity planning for the ServiceControl environment.

**Comment by JSCProjects** [comment]
Hi @WilliamBZA 

The machine is hosted in Azure and has size "Standard DS11_v2 (2 Cores, 14 GiB memory)" and
ServiceControl binaries and database is running on a seperate datadisk with premium storage 
and a IOP limit of 5000, throughputlimit of 200 MB/S

Do you need more info? I will look at the guidance

**Comment by WilliamBZA** [comment]
How many messages is the instance ingesting?
What is the size of the Database directory?
Is there anything else running on the VM?

**Comment by JSCProjects** [comment]
Our complete DTAP (ServiceControl/Monitoring) is currently running on that machine. Currently there are 400k messages audited the DTAP.  More than 160k is from P. The size of the P db is 2.57GB. The machine is only running Particular software and IIS for serving servicepulse

**Comment by WilliamBZA** [comment]
Do the counts ever match up after a while? Or are they permanently out of sync with each other?

If they never match up, that could be an indication that something is wrong with the indexes.

**Comment by WilliamBZA** [comment]
@JSCProjects Can I ask you to please drop me an email? william.brander@particular.net I'd like to dig deeper into this than a public github issue allows.

**Comment by WilliamBZA** [comment]
We worked through the system where this was a problem and uncovered a potential bug with the archive operation.

The process for the operation is:

1. Send a message to ServiceControl to tell it to archive all messages in that group
2. ServiceControl handles the message and creates an `ArchiveOperation`. This `ArchiveOperation` represents the state that the group is currently being archived.
3. ServiceControl then splits the group into various batches called `ArchiveBatch`. 
4. As each batch is archived, it deletes the specific `ArchiveBatch` document
5. Once all batches are archived, the `ArchiveOperation` is flagged as completed and waits to be dismissed.

The bug in this case occurred when there was no `ArchiveOperation` document, but there were `ArchiveBatch` documents. So when ServiceControl tried to handle the archive message, it tried to create the ArchiveOperation, but failed when creating the ArchiveBatches as they already existed (The IDs are deterministic).

This results in RavenDB throwing a ConcurrencyException, and the archive message being in ServiceControl's error queue.

**This means that the archive operation will _never_ complete until the documents are cleaned up**

I suggest the following as a fix:

* Change the optimistic concurrency to ONLY be on the `ArchiveOperation`

This means that no 2 archive operations of the same group can be done at the same time, but if the `ArchiveBatch` documents already exist, they will simply be updated.

@Particular/servicecontrol-maintainers thoughts?

**Comment by SzymonPobiega** [comment]
@WilliamBZA how is it possible that the `ArchiveBatch` documents existed without an `ArchiveOperations`?

**Comment by WilliamBZA** [comment]
That is an excellent question @SzymonPobiega. I'm not sure how the system ended up in this state, but that is the state that it was in.

Maybe [this](https://github.com/Particular/ServiceControl/blob/master/src/ServiceControl/Recoverability/Archiving/ArchiveDocumentManager.cs#L120) would be the cause? Extremely unlikely though as that's not doing a query anywhere so indexes wouldn't be at fault.

**Comment by WilliamBZA** [comment]
PR with test submitted https://github.com/Particular/ServiceControl/pull/1090
