### ISSUE TITLE
Make new monitoring screens usable on mobile devices

### ISSUE THREAD

**Issue by sergioc** [Particular/ServicePulse#598]
Make new monitoring screens usable on mobile devices. Currently the UI is only usable in screen widths down to 1440px.

Use case: dev/ops person gets a call to inform the system is misbehaving and doesn't have a computer nearby to check the problem and solve it. However, because SP can be accessed and is usable on mobile, this person has the ability to help the rest of the team diagnose the issue to fix it.

**Comment by mauroservienti** [comment]
I suppose these are the type of problems we want to address:

![image](https://user-images.githubusercontent.com/1325611/36672708-97647ef8-1b00-11e8-8477-40cbbf4d5672.png)

![image](https://user-images.githubusercontent.com/1325611/36672743-b69448a8-1b00-11e8-81ad-8f99b2fb337f.png)

Screenshots taken from iPad

**Comment by sergioc** [comment]
We're likely not adding mobile support anytime soon and will make 1440px the minimum required width. Closing

**Comment by mauroservienti** [comment]
Are we considering iPad a mobile device and thus excluding tablets as an option for Ops people?

**Comment by sergioc** [comment]
iPad is traditionally considered a mobile device. The resolution @2x is lower than 1440px in any case. This doesn't mean the UI won't be usable. It will just scale and elements will show smaller as a result. Touch support might also be sub-optimal.
