### ISSUE TITLE
Endpoints nav link is confusing

### ISSUE THREAD

**Issue by sergioc** [Particular/ServicePulse#600]
The current endpoint nav icon is too similar to the monitoring icon:

<img width="188" alt="image" src="https://user-images.githubusercontent.com/493451/33559619-ab600830-d90d-11e7-97eb-02e14848ca80.png">

 It also does not match the endpoint icon used in SI:

<img width="67" alt="image" src="https://user-images.githubusercontent.com/493451/33559657-c9614f1a-d90d-11e7-871e-8dfa4670059e.png">

Finally, the linked screen is only about Heartbeats, yet endpoints are also handled in 2 other screens (monitoring and configuration).

Proposal: Rename the nav link from "Endpoints" to "Hearbeats" since that's the only function of that view.

**Comment by WilliamBZA** [comment]
Alternative proposal: Remove that view completely and incorporate heartbeats into the monitoring page

**Comment by sergioc** [comment]
Well that would be the ideal option, but much more difficult to achieve.

**Comment by sergioc** [comment]
Nav link renamed in https://github.com/Particular/ServicePulse/pull/599
