### ISSUE TITLE
Unknown message type tracked by the Monitoring demo

### ISSUE THREAD

**Issue by mauroservienti** [Particular/ServicePulse#604]
When I start the monitoring demo on my machine the UI in ServicePulse shows all expected data, plus the following:

![image](https://user-images.githubusercontent.com/1325611/36672799-ec757c08-1b00-11e8-86e8-29f9d448703d.png)

**Comment by tmasternak** [comment]
PlatDev issue: https://github.com/Particular/PlatformDevelopment/issues/1881

**Comment by seanfarmar** [comment]
@mauroservienti With the latest version I wasn't able to reproduce this, can you provide a repro, please?

**Comment by mauroservienti** [comment]
As far as I remember it has been fixed a while ago @seanfarmar. W can close this one.
