### ISSUE TITLE
On narrow screens the hamburger menu has some glitches

### ISSUE THREAD

**Issue by mauroservienti** [Particular/ServicePulse#605]
When using ServicePulse on a narrow screen, or by reducing the width of the browser window, or when the screen is in portrait mode the hamburger menu has some glitches:

![pulse-hamburger](https://user-images.githubusercontent.com/1325611/37209682-5f79b482-23a6-11e8-8d25-810719e5e687.gif)

**Comment by sergioc** [comment]
To fix via https://github.com/Particular/ServicePulse/issues/653
