### ISSUE TITLE
Set GroupBy selection into the url so we can bookmark the page with the preferred grouping

### ISSUE THREAD

**Issue by fcastellscha** [Particular/ServicePulse#607]
Suggestion:

In the Failed Message groups page, it's possible to choose the type of grouping, but the selected option is not set in the url nor persisted. Therefore, every time you open the page the selection is gone. 
The easy fix is to add the selection in the url at least this allows to bookmark the page with the preferred grouping.

**Comment by sergioc** [comment]
Thanks for the suggestion @fcastellscha. We'll look into this as soon as possible. Also relates to #597.

**Comment by sergioc** [comment]
Fixed in upcoming v1.15 release
