### ISSUE TITLE
Continually showing "connected to SC" is redundant and distracting

### ISSUE THREAD

**Issue by SimonCropp** [Particular/ServicePulse#608]
every time i navigate to SP or refresh the page i get the following

![image](https://user-images.githubusercontent.com/122666/38284532-1ce1ac98-37ff-11e8-939b-ea8e3d87d870.png)

SP version v1.12.0  

## Solution

- [ ] eliminate duplicate notifications
- [ ] only show notifications when unable to connect
- [x] Show a permanent SC connectivity status indicator (e.g. place a red/green light somewhere TBD)

**Comment by WojcikMike** [comment]
Again thanks @SimonCropp , I can see this message being of value when the connection was lost and later on reestablished. I will keep you posted how this progress

**Comment by SimonCropp** [comment]
Any update on fixing this?

**Comment by WilliamBZA** [comment]
It's not done yet, but I'd like to re-open this so that it does eventually get added. I feel a simple status icon is much more appropriate that an annoying pop-up

**Comment by HEskandari** [comment]
Although showing connected / disconnected from SC does add _some_ value, the repetition is what bothers me the most.

![image](https://user-images.githubusercontent.com/132117/44259082-df787980-a253-11e8-8293-984c51afaa4b.png)

**Comment by sergioc** [comment]
Fixed in upcoming v1.15 release
