### ISSUE TITLE
SP obscures an error with SC reading a failed message with a misleading error

### ISSUE THREAD

**Issue by SimonCropp** [Particular/ServicePulse#609]
When SC fails to retrieve a failed message (eg https://github.com/Particular/ServiceControl/issues/1119)
this page `/#/failed-messages/message/b6ee1f42-722d-5072-9e90-19c2739fe434` displays

> Could not find message. This could be because the message URL is invalid or the corresponding message was processed and no longer audited by ServiceControl.

![image](https://user-images.githubusercontent.com/122666/38287923-cf144748-3810-11e8-82e6-d8d2e13242eb.png)

but if u look in the network tab it is clear the proxied call to SC has had a critical error with a `500 Internal Server Error`

![image](https://user-images.githubusercontent.com/122666/38287955-fbc493d8-3810-11e8-881e-c5db63a74759.png)

This error is hidden from the user and gives useless guidance as to how someone should proceed. ie that is a generic nancyfx error

Specifically

 * "not found" should not be shown when a response is an error code
 * an error message should be surfaced to the UI that includes the log location of where to view the exception message and stack trace.

**Comment by WojcikMike** [comment]
Thanks @SimonCropp for raising that, There is definitely value in making this page more useful by exposing more details to end user. I will let you know when we will have a change to implement it

**Comment by WojcikMike** [comment]
I reviewed the issue and as we are actually recognizing in SC when the message is not found we return 404. While when there is an error we return 500 (saying we is a bit of a stretch here, we are throwing an exception which is represented as 500). So we can implement this feature in current maintainer release (internal gibberish)
