### ISSUE TITLE
Monitoring - Endpoints overview - Links to 'Failed Messages' instead of 'Endpoint Details'

### ISSUE THREAD

**Issue by cjoergensen** [Particular/ServicePulse#626]
Elements in the 'Endpoints overview' with failed msgs links to the 'Failed Messages' instead of the 'Endpoint details' page:

![image](https://user-images.githubusercontent.com/8087733/39417722-80c1a43c-4c56-11e8-9590-263355b4310d.png)

I would expect that clicking on the endpoint name takes me to the 'Endpoint details' page and clicking on the failed messages icon  would take me to the Failed Messages page
![image](https://user-images.githubusercontent.com/8087733/39417802-fd44d934-4c56-11e8-8b66-6e8f70d34121.png)

***************

*Technical information if reporting bug:*

- **ServicePulse version:** 1.12.0
- **ServiceControl version:** 1.47.3

**Comment by WojcikMike** [comment]
Hi @cjoergensen thanks for raising it. When I checked it on my laptop (works for me right ;)) it works as you would like it to work. Check the screen below, name links to endpoint details while failed message icon to failed messages page. I put a border around links to easier identify where the clickable elements are. 

![image](https://user-images.githubusercontent.com/604826/39418672-f595c130-4c5b-11e8-9629-ea0a18f3add6.png)

Can you doublecheck that it works differently on your version?

**Comment by cjoergensen** [comment]
@WojcikMike Here is the inspected element from Firefox 59.0.2 (64-bit):

![image](https://user-images.githubusercontent.com/8087733/39419077-4783cecc-4c5e-11e8-8177-9792e7bc023a.png)

Here is the row html for further inspection:
[row-elm.txt](https://github.com/Particular/ServicePulse/files/1959855/row-elm.txt)

:-)

**Comment by WojcikMike** [comment]
Yeah, I see. Could you by any chance open that site in-privet/private window/incognito kind of view. As it looks like a caching problem (at least my html is different for that site)

**Comment by cjoergensen** [comment]
Same problem in Private Mode

**Comment by sergioc** [comment]
@cjoergensen are you sure you're on ServicePulse v1.12.0? I believe this is not the first time we come across this bug and it's been fixed before.

One way of seeing that you have v1.12.0 is the endpoint names should be dark blue hand have a dotted underline. You would also need to click on the name directly to open the details page. In your case the endpoint names are black, so something is outdated there.

Alternatively try installing the just released v1.13.0 and see if it helps.

**Comment by cjoergensen** [comment]
Upgraded to v1.13.0 fixed the issue!

Thanks!
