### ISSUE TITLE
Return from MessageView does not work with Angular 1.7.0

### ISSUE THREAD

**Issue by mohlerm** [Particular/ServicePulse#637]
This issue seems to be related to #635, which got fixed in #636.
When trying to return from the message view by pressing the back button, I receive a 'address wasn't understood' error.
![back](https://user-images.githubusercontent.com/3135878/40903917-5655ae7a-67d9-11e8-95a9-f2c5de82caa9.png)
![message](https://user-images.githubusercontent.com/3135878/40903918-5684e82a-67d9-11e8-8789-4017aca7d29c.png)
The browsers' address bar shows: unsafe:javascript:javascript:history.go(-1)

Thank you.

***************

*Technical information if reporting a bug:*

- **ServicePulse version:** v1.14.0
- **ServiceControl version:** v1.48.0 
- **Browser version:** Firefox Quantum 59.0.2 (64-bit)

**Comment by WilliamBZA** [comment]
Thanks @mohlerm, PR and release coming soon

**Comment by WilliamBZA** [comment]
Thanks again @mohlerm, this should be fixed in [1.14.1](https://github.com/Particular/ServicePulse/releases/tag/1.14.1)
