### ISSUE TITLE
Add a Select All button to Service Pulse

### ISSUE THREAD

**Issue by outofcoolnames** [Particular/ServicePulse#639]
Describe your problem / suggestion / idea / feedback here.

When browsing https://<psp>/#/failed-messages/groups/ it would be useful to have a select all feature. Often, when opening message failures for a specific endpoint, there may be a large number of messages where you may want to archive/retry 250 out of 260 failures. By adding a select all feature, it would all unticking a handful of message failures. Alternatively, could you point me to some API documentation allowing retries by endpoint and failure type.
***************

*Technical information if reporting a bug:*

- **ServicePulse version:** 
- **ServiceControl version:** 
- **Browser version:**

**Comment by WojcikMike** [comment]
Thanks @outofcoolnames for raising it. Can you describe in more detail the business case when you would like to use such a feature? The problem that I see with proposed implementation is that we are using infinite scroll so for the most part 260 items (in your example) will not be displayed on a page but probably we could find a way around it. The bigger problem is that a user needs to find 10 messages out of 260 to exclude them which is not a simple task, and is error-prone. 

Maybe it is a classification problem (user wants to retry/archive all errors send from a given endpoint, or of a given type etc.). I would like to understand better when you are in need to do such retry/archive.

**Comment by outofcoolnames** [comment]
@WojcikMike , I get around the infinite scoll by scrolling to the bottom until all items are loaded. Lets say I'm in the list where I've selected "Failed message groups" and grouped by "Endpoint Address". I may have a mixture of failures in the list. An even more useful solution in this instance would be a search filter where I could type "failure message" and the list would be filtered, I could then archive/ retry these. 
You may say that this functionality is available when I've selected "Failed message groups" and grouped by "Exception Type and Stack Trace". However, when opening a failure in this list, there may be multiple endpoints returned. I may not want to retry / archive all of these. A search filter would be useful here too to filter by endpoint

**Comment by WojcikMike** [comment]
If I understand correctly the actual need is to make operations on a group of certain message types (or exceptions types) in a context on 1 endpoint. Which at the moment you can't do. Let me think about it as I am a bit reluctant implementing select all button to solve this problem. Easily you might want to retry/archive 30% of failed messages in which case select all doesn't solve the problem.

**Comment by sergioc** [comment]
@outofcoolnames we've just [released ServicePulse 1.27](https://github.com/Particular/ServicePulse/releases/tag/1.27.0) and added a button to select all messages. Note that this only applies to messages that were already loaded in the UI.

**Comment by WojcikMike** [comment]
Just for clarity in the ServicePulse version 1.30 we replaced infinite scroll with pager.
