### ISSUE TITLE
Installing ServicePulse 1.14.1 still shows v1.14.0 in the UI

### ISSUE THREAD

**Issue by davidsavagejr** [Particular/ServicePulse#641]
After installing v1.14.1 the ui still shows v1.14.0 as the current version and that 1.14.1 is available for update.  This was an upgrade from 1.14.0.  I also completely uninstalled, reinstalled.

***************

*Technical information if reporting a bug:*

- **ServicePulse version:** 1.14.1
- **ServiceControl version:** 2.0.2
- **Browser version:** Chrome (latest)

![screen shot 2018-06-14 at 11 11 27 am](https://user-images.githubusercontent.com/1714830/41424527-eb545e3a-6fc3-11e8-99dc-e7da58805d86.png)
![screen shot 2018-06-14 at 11 11 08 am](https://user-images.githubusercontent.com/1714830/41424541-f1f41d7a-6fc3-11e8-9505-dbbc041ba03a.png)
![screen shot 2018-06-14 at 11 10 23 am](https://user-images.githubusercontent.com/1714830/41424548-f6ef8404-6fc3-11e8-8877-81d239fa5f33.png)

**Comment by WilliamBZA** [comment]
That's very strange @davidsavagejr. Can you open up the `app.constants.js` file in the app directory above and see what version it reports there please?

**Comment by davidsavagejr** [comment]
Actually what I found out is it was a browser caching issue.  It just cleared up after I cleared everything.  Will go ahead and close this out ;)
