### ISSUE TITLE
Rendering of the message types view in the monitoring view of an enpoint is not correct

### ISSUE THREAD

**Issue by gemas** [Particular/ServicePulse#642]
Rendering of the message types view in the monitoring view of an enpoint is not correct

![image](https://user-images.githubusercontent.com/4850361/41716606-4b3e6f96-7557-11e8-8419-db3244003ebf.png)

***************

*Technical information if reporting a bug:*

- **ServicePulse version:** 1.14.1
- **ServiceControl version:**  2.0.3
- **Browser version:**  chome/ie

**Comment by gemas** [comment]
duplicate issue 
https://github.com/Particular/ServicePulse/issues/612

**Comment by WojcikMike** [comment]
Hi @gemas thanks for raising this bug, and thanks for identifying that it's a dupliate We are currently working on it.

**Comment by WojcikMike** [comment]
Hi @gemas we just released version 1.14.3 which solves this problem. Please have a look and tell us what you think
