### ISSUE TITLE
Remove namespace from message type

### ISSUE THREAD

**Issue by WojcikMike** [Particular/ServicePulse#644]
In monitoring screen of an endpoint we are showing message types that include namespace. In production systems namespaces tend to be long, which uses a lot of space. We should display message types in a grid without namespaces, and expose full type in tooltip.

Alternatively we could make it configurable. 

This functionality was mentioned in this issue: https://github.com/Particular/NServiceBus/issues/5198#issuecomment-400318670

***************

*Technical information if reporting a bug:*

- **ServicePulse version:** 1.14

**Comment by sergioc** [comment]
Released in 1.27
