### ISSUE TITLE
Rendering issue graphs in Servicepulse Monitoring view

### ISSUE THREAD

**Issue by mohlerm** [Particular/ServicePulse#646]
We just updated to the latest ServicePulse and ServiceControl version and experience a display issue when looking at the monitoring view.
In particular when displaying a single endpoint under Monitoring -> Select an endpoint.
Some of the graphs seem off and go off the grid, see the screenshot below:
![issue_servicepulse](https://user-images.githubusercontent.com/3135878/42624425-aa25b0b8-85c5-11e8-9c56-3dc6e70f76d9.png)
It does not happen for all of our services but we can not figure out any pattern.
I tried different browsers and it persists in Firefox Quantum, Internet Explorer and Edge.

Thank you for looking into it.

***************

*Technical information if reporting a bug:*

- **ServicePulse version:** v1.14.3
- **ServiceControl version:** v2.1.1
- **Browser version:** Firefox Quantum 59.0.2 (64-bit)

**Comment by WojcikMike** [comment]
@mohlerm thanks for raising this issue. I will check it on my environment and let you know. Could you specify which version of ServiceControl.Monitoring nuget package are you using?

**Comment by WojcikMike** [comment]
Yes, that's the one. Thanks, even despite that I gave you the wrong name ;)

**Comment by WojcikMike** [comment]
This issue was fixed as a part of 1.14.4. @mohlerm please download the latest and check if it fixed your problem. I diagnosed that it can be seen when you have an endpoint that reports information about retries but not throughput (meaning that it fails on a group of messages without successfully processing any in reported time).

**Comment by mohlerm** [comment]
Hi @WojcikMike 
Perfect, thank you very much for fixing it so quickly.
I installed the latest version and it looks good so far.

Cheers
