### ISSUE TITLE
Do not show monitoring empty state before populating screen with data

### ISSUE THREAD

**Issue by sergioc** [Particular/ServicePulse#648]
Do not show empty state before populating data in monitoring screens screens (unless it's valid to show the empty state), so that the user is not incorrectly mislead to think there's a problem with monitoring.

**Comment by mikeminutillo** [comment]
@sergioc are you able to test this again on master and either close it or provide more context? We aren't sure exactly what is meant by empty state.

**Comment by sergioc** [comment]
I've tested this and I'm no longer able to reproduce the problem.
