### ISSUE TITLE
Graphs with no data should always show solid line at the bottom

### ISSUE THREAD

**Issue by sergioc** [Particular/ServicePulse#651]
Graphs with no data should always show solid line at the bottom. In the example below there's 2 graphs with no data that show only the average lines at the bottom:

<img width="1050" alt="image" src="https://user-images.githubusercontent.com/493451/33430633-85c09994-d5d1-11e7-973f-a1515041fe5c.png">

This may lead user to unnecessarily wonder why do those graph display differences exist.

**Comment by WojcikMike** [comment]
Will be released as a part of 1.15
