### ISSUE TITLE
Force minimum viewport width of 1440px

### ISSUE THREAD

**Issue by sergioc** [Particular/ServicePulse#653]
Force minimum viewport width of 1440px to prevent bootstrap responsive styles from kicking in and re-adjusting layout in uncontrolled manner.

**Comment by mauroservienti** [comment]
@sergioc I vote to leave this here, seems low hanging fruit that can be handled during the next maintenance release. Thoughts?

**Comment by WilliamBZA** [comment]
Agreed @mauroservienti

**Comment by mauroservienti** [comment]
@Particular/developer-experience-squad Hadi and myself think this is a small feature that is better handled by @Particular/servicepulse-maintainers during a maintenance release. Thoughts?

cc @Particular/keeping-the-lights-on-squad

**Comment by sergioc** [comment]
It problably only takes adding a viewport metatag in the HTML to fix this, do we need to wait for a maintenance release to fix something as simple as that?

**Comment by mauroservienti** [comment]
In theory yes @sergioc, however what prevents anyone to raise a PR with such a little fix in their spare time?

**Comment by sergioc** [comment]
So if someone does it in the meanwhile, we don't need to wait for a maintenance release.

**Comment by HEskandari** [comment]
@mauroservienti @sergioc IMO even raising a PR and getting it merged is different than releasing it. Think of it this way: what's the benefit for the user to upgrade? Having a better/more meaningful release would give more incentive for people to upgrade.
