### ISSUE TITLE
Endpoint details screen should show "No Messages processed in this period of time" instead of a blank section

### ISSUE THREAD

**Issue by sergioc** [Particular/ServicePulse#654]
If the user is looking at the details of an endpoint for a period of time where no messages have been processed yet, it should be made explicit that no messages have been processed with a simple message in the list of message types instead of showing it empty:

<img width="1453" alt="image" src="https://user-images.githubusercontent.com/493451/35563024-a7d821aa-05b5-11e8-98d1-d5dbb01d7580.png">

**Comment by WojcikMike** [comment]
Will be released as a part of 1.15
