### ISSUE TITLE
Change monitoring overview page URL slug

### ISSUE THREAD

**Issue by sergioc** [Particular/ServicePulse#655]
Change monitoring overview page URL slug in SP to match the convention used in other screens (i.e. slug matches nav label and page title, e.g. Failed Messages > `failed-messages`).

Change from `/monitored_endpoints`to `/monitoring`. An endpoint detail page URL would change to `/monitoring/endpoint/<endpoint-id>`

**Comment by mauroservienti** [comment]
@Particular/developer-experience-squad Hadi and myself think this is a small feature that is better handled by @Particular/servicepulse-maintainers during a maintenance release. Thoughts?

cc @Particular/keeping-the-lights-on-squad

**Comment by sergioc** [comment]
Isn't this small enough to justify not waiting for a maintenance release?

**Comment by HEskandari** [comment]
@sergioc IMO releasing anything on its own would be against the current processes. Other than that, this issue might result in breaking people's bookmarks so we might need to think about doing redirects (see, it quickly gets more complicated).

**Comment by dvdstelt** [comment]
Could it be combined with #653 and perhaps some other small tasks for a maintenance release?
