### ISSUE TITLE
Monitoring view - if message type name is long, the display is unreadable 

### ISSUE THREAD

**Issue by seanfarmar** [Particular/ServicePulse#659]
Monitoring view - if message type name is long, the display is unreadable 

***************

*Technical information if reporting a bug:*

- **ServicePulse version:** : 1.14.1
- **ServiceControl version:** : 3.1.2
- **Browser version:** any
![screen shot 2018-10-02 at 11 49 39](https://user-images.githubusercontent.com/125256/46344889-8bc2c380-c63a-11e8-9bb4-3c50189b8583.png)

**Comment by sergioc** [comment]
@seanfarmar this issue was fixed a couple of releases ago, in v1.14.2

Let us know if it still persists after you update.

**Comment by seanfarmar** [comment]
Yup, Upgraded to the latest and it works, thanks!
