### ISSUE TITLE
Unarchive does not support bulk operation

### ISSUE THREAD

**Issue by HEskandari** [Particular/ServicePulse#661]
The scenario is that when a user archives a category of errors by accident and then need to undo that change. There could be thousands of messages to un-archive and the operation currently is one-by-one, or at best page by page by using the new Shift-Click selection.

This is applicable to the latest version of ServicePulse.

**Comment by parto** [comment]
I have two more issues with the Unarchive functionality:

1. If you select more than 50 messages to unarchive, all of them are removed from the UI but only 50 of them are actually unarchived without any warning or error. If you refresh the page you still get the failed unarchived messages in the list.
2. The _infinite scrolling_ doesn't work properly when you're trying to unarchive a lot of messages. Assume you have 200 messages to unarchive. Select the first 55, scroll to top, unarchive, you only get a few more of the preloaded items and infinite scrolling fails to fetch next pages. If you unarchive the rest of the messages that are visible on the page, it shows a "_There are currently no archived messages_" while the **Archived Messages** tab above still shows the actual number of archived messages. Refreshing the page resolves the issue though.

**Comment by sergioc** [comment]
@parto I've opened 2 separate issues based on your feedback: #664 & #665
