### ISSUE TITLE
Archived messages view state becomes inconsistent after unarchiving some messages

### ISSUE THREAD

**Issue by sergioc** [Particular/ServicePulse#665]
Feedback from @parto:

The infinite scrolling doesn't work properly when you're trying to unarchive a lot of messages. Assume you have 200 messages to unarchive. Select the first 55, scroll to top, unarchive, you only get a few more of the preloaded items and infinite scrolling fails to fetch next pages. If you unarchive the rest of the messages that are visible on the page, it shows a "There are currently no archived messages" while the Archived Messages tab above still shows the actual number of archived messages. Refreshing the page resolves the issue though.

***************

*Technical information if reporting a bug:*

- **ServicePulse version:** v1.14.4
- **ServiceControl version:** v3.0.1 / 3d24e07
- **Browser version:** Chrome Version 69.0

**Comment by parto** [comment]
ServiceControl v3.0.1 / 3d24e07
ServicePulse v1.14.4
Chrome Version 69.0

**Comment by kbaley** [comment]
This is a side effect of #664. A PR is up to address that, and by extension this, problem.
