### ISSUE TITLE
ServiceControl Url Error

### ISSUE THREAD

**Issue by Varorbc** [Particular/ServicePulse#676]
![image](https://user-images.githubusercontent.com/5714438/48116005-b0483600-e29f-11e8-9332-2c18b64e9dce.png)
![image](https://user-images.githubusercontent.com/5714438/48116081-e8e80f80-e29f-11e8-8745-0b6af041d396.png)

**Comment by WilliamBZA** [comment]
Can you show me the HTTP response of the browser downloading the `app.constants.js` file @Varorbc?

Are you behind a reverse proxy by any chance?

**Comment by Varorbc** [comment]
![image](https://user-images.githubusercontent.com/5714438/48121932-3e78e800-e2b1-11e8-9abd-f1085a594632.png)

**Comment by WilliamBZA** [comment]
Yeah so that file has either not been saved correctly or the browser is caching it. Can you try refresh after clearing the cache?

**Comment by Varorbc** [comment]
Thank you, is the cache problem
