### ISSUE TITLE
It is not possible to override previously configured urls during SP upgrade during unattended installation

### ISSUE THREAD

**Issue by tmasternak** [Particular/ServicePulse#681]
### Problem
If SP is being installed unattended on a machine that had SP already installed it is not possible to change previously configured service urls when using unattended mode. 

The only option is to go to `app.constants.js` after installation is done and change the url entries there. This is happening because:
 * even after SP is uninstalled the configuration is being kept in the installation folder,
 * the installer will search for any existing `app.constants.js` files and if one found it will override user-specifed url values with those found in the file.

**Comment by mauroservienti** [comment]
ServicePulse `1.20.0` supports changing connections configuration via the ServicePulse configuration screens. Closing.
