### ISSUE TITLE
Add multiple instances feature like servicecontrol

### ISSUE THREAD

**Issue by TraGicCode** [Particular/ServicePulse#690]
I’m order to have servicepulse be installed on 1 machine and we for multiple environments we have to jump through the iis steps outlined in the docs.  Is it possible to take the same approach as service control and have multiple instances of service pulse that run on a different port?

**Comment by WilliamBZA** [comment]
What about allowing a single instance of ServicePulse connect to multiple instances of ServiceControl - similar to how it can do it with the monitoring bits?

**Comment by TraGicCode** [comment]
That would also work.  You would need to add a drop-down to change the context of the user ( All Instances / Dev Instance / Prod Instance ) etc but yea that sounds like it would work

**Comment by TraGicCode** [comment]
Thanks !

**Comment by TraGicCode** [comment]
Hey @williambza,

Any updates on this feature?

**Comment by sergioc** [comment]
@TraGicCode we'll be addressing this problem soon, stay tuned!

**Comment by TraGicCode** [comment]
> @TraGicCode we'll be addressing this problem soon, stay tuned!

Any updates on this and where it might land on the roadmap?

**Comment by sergioc** [comment]
We're [currently busy with this](https://github.com/Particular/ServicePulse/pull/725) and we're not far off from having it ready.

**Comment by WilliamBZA** [comment]
This will be released as part of 1.20.0. Closing for now. I will ping once the release is out

**Comment by WilliamBZA** [comment]
Release is available here: https://github.com/Particular/ServicePulse/releases/tag/1.20.0
