### ISSUE TITLE
Installer labels for "Note" overlapping

### ISSUE THREAD

**Issue by ramonsmits** [Particular/ServicePulse#691]
![image](https://user-images.githubusercontent.com/152998/49433306-fd8dc980-f7b1-11e8-9371-a23b40d2e626.png)

**Comment by sergioc** [comment]
Tx, small fix for the next release

**Comment by ramonsmits** [comment]
Seems it is already fixed:

![image](https://user-images.githubusercontent.com/152998/79950475-680eda80-8477-11ea-8e67-e84399463cf5.png)
