### ISSUE TITLE
All failed messages view does not work on IE

### ISSUE THREAD

**Issue by WojcikMike** [Particular/ServicePulse#694]
When using IE and navigating into: `/failed-messages/all` the screen does not work. That page works correctly on Edge (even in compatibility mode) and other browsers.

***************

*Technical information if reporting a bug:*

- **ServicePulse version:** 1.15
- **Browser version:** IE 9+

**Comment by timbussmann** [comment]
This is fixed in version 1.15.1 which just has been released.
