### ISSUE TITLE
Checkbox not showing in latest chrome when creating a redirect

### ISSUE THREAD

**Issue by TraGicCode** [Particular/ServicePulse#707]
When creating a "Redirect" the checkbox is missing to indicate that failed messages that match this redirect should be automatically retried.

![image](https://user-images.githubusercontent.com/6224270/50743740-06beeb80-11e1-11e9-93a6-9ce1677947ee.png)

***************

*Technical information if reporting a bug:*

- **ServicePulse version:** 
v1.15.1
- **ServiceControl version:** 
v3.5.0
- **Browser version:** 
71.0.3578.98 (64-bit)

**Comment by WojcikMike** [comment]
Thanks, @TraGicCode for raising it, we will address it in the future releases

**Comment by sergioc** [comment]
Tested, problem reproduced on:

* Chrome 71.0.3578.98
* IE 11.471.17134.0
* Firefox 64.0.2
* Edge 42.17134.1.0
