### ISSUE TITLE
Question: how to specify service name and display name?

### ISSUE THREAD

**Issue by kbulte** [Particular/ServicePulse#736]
When installing service pulse via the installer is it possible to pass a service name and display name?
`.\Particular.ServicePulse.exe /Quiet /Log C:\temp\servicepulse-installer.log INST_PORT_PULSE=12345 INST_URI=http://localhost:33333/api/`

Or is it only possible to pass the service name and display name after copying the ServicePulse.Hoste.exe from the install folder of another instance and executing the following command?
`ServicePulse.Host.exe --install --serviceName="MyServicePulse" --displayName="MyServicePulse"`

**Comment by WilliamBZA** [comment]
It's unfortunately only possible from the `ServicePulse.Host.exe` file

**Comment by kbulte** [comment]
Thanks for the reply. I execute the installer now first with powershell and take a copy of the install folder, next I can call the ServicePulse.Host.exe and pass the service and display name. It's a bit cumbersome but it works.
