### ISSUE TITLE
Failed msg group name missing in list of last 10 completed retry requests

### ISSUE THREAD

**Issue by sergioc** [Particular/ServicePulse#744]
<img width="705" alt="image" src="https://user-images.githubusercontent.com/493451/56661626-74185e80-66a2-11e9-97fc-b8e7ce10ecec.png">

***************

*Technical information if reporting a bug:*

- **ServicePulse version:** 1.19.0
- **ServiceControl version:** 3.6.9

**Comment by WojcikMike** [comment]
@sergioc I am almost sure that we display lack of title if you retry a single message. Can you confirm that? Retry a group and later a single message and see what is presented in the 10 completed retry requests

**Comment by sergioc** [comment]
Seems to be the case:

<img width="983" alt="image" src="https://user-images.githubusercontent.com/493451/56880037-7dffe000-6a5b-11e9-8a11-5a8b5fe58884.png">
