### ISSUE TITLE
Upgrade protection warning doesn't respect IIS virtual directory

### ISSUE THREAD

**Issue by shoffman11** [Particular/ServicePulse#751]
When ServicePulse is deployed in a virtual directory, the "View license details" button on the "Upgrade protection expires soon" does not respect the virtual directory.

I.e. when ServicePulse is deployed at http://mydomain.example.com/MyServicePulse the button links to http://mydomain.example.com/#/configuration/license instead of ...com/MyServicePulse/#/configuration/license

The same problem also appears to exist in the subscription expiring, trial expiring, upgrade protection expired warning messages.

Similiar to [704](https://github.com/Particular/ServicePulse/issues/704)

***************
- **ServicePulse version:** 1.19.0
- **ServiceControl version:** N/A
- **Browser version:** Chrome 74

**Comment by dbelcham** [comment]
@shoffman11 Thanks for the bug report and corresponding PR. We're trying to figure out when we'll be able to get this fixed and release. We should put an update here once we've got that determined.

**Comment by WojcikMike** [comment]
@shoffman11 Thank you for the PR. 

I was able to merge it and do the release. I made a small change to remove monitoring.dist.js from your PR as it is not needed. The version 1.20.1 is out and it contains the fix.

**Comment by WojcikMike** [comment]
@shoffman11 could you please send me your personal information (name and address) to my email:
michal.wojcik@particular.net

We would like to send you a small gift for your contribution to ServicePulse
