### ISSUE TITLE
The message when monitoring is not available is not clear

### ISSUE THREAD

**Issue by mikeminutillo** [Particular/ServicePulse#755]
When you go to the monitoring tab, if there is no data to display you see the following:

![image](https://user-images.githubusercontent.com/124014/59898184-3e81be80-9422-11e9-9706-90ba7ff16541.png)

The third point is not very clear. I believe the original intent was to capture endpoints that don't have the monitoring plugin installed. They would normally appear on this page if they are sending data to ServiceControl. If there is no data at all to display, then you see this message.

I'm not sure that it adds any value. Perhaps we should consider dropping this point altogether. It may make more sense to have a generic "Why don't my endpoints appear?" link off to the documentation website with some troubleshooting guidelines.

**Comment by gkorobkov** [comment]
We had the same issue. We configured monitoring service and endpoints but did not see any endpoints here until we added the following permissions: "Delete", "Receive Message", "Peek Message" and "Send Message" to Everyone and ANONYMOUS LOGON users for two queues: particular.servicecontrol and particular.monitoring

**Comment by WilliamBZA** [comment]
This will be improved in release 1.25.0 (coming next week)

**Comment by WilliamBZA** [comment]
Release is out! You can download [1.25.0](https://github.com/Particular/ServicePulse/releases/tag/1.25.0) and this should be done.
