### ISSUE TITLE
Dashboard messages lack endpoint name

### ISSUE THREAD

**Issue by philippdolder** [Particular/ServicePulse#759]
The messages on the Dashboard would be more helpful if the endpoint name / instance would be displayed as well.

I observed the info is missing in 
- Endpoint heartbeats have been restored.
- Endpoint has failed to send expected heartbeat to ServiceControl. It is possible that the endpoint could be down or is unresponsive. If this condition persists restart the endpoint

**Comment by DavidBoike** [comment]
Thanks @philippdolder! I agree that would be helpful. I've raised it as a possibility for our enhancement release process, but I'm not sure when we might be able to get that prioritized.

**Comment by WojcikMike** [comment]
This issue will be addressed by https://github.com/Particular/ServiceControl/pull/1975

**Comment by WilliamBZA** [comment]
This has been released in version [4.9.0 of ServiceControl.](https://github.com/Particular/ServiceControl/releases/tag/4.9.0)
