### ISSUE TITLE
We need some sort of tree view or categories in "Endpoint heartbeats" and "Endpoints overview"

### ISSUE THREAD

**Issue by gkorobkov** [Particular/ServicePulse#765]
We have more than one hundred Workers being monitored in ServicePulse and this amount will increase in the future so probably we will have some hundreds of Workers.
Now we can see the simple lists of Workers listed in the alphabetic ordere and it is hard to review these instances or find something.

We need some sort of tree view or categories.

It would be great if you can create an automatic tree split by dots in the name of the Worker. 

Example: names of some workers are
- "Universe.SolarSystem.Earth"
- "Universe.SolarSystem.Mars"
- "Universe.AlphaCentauri.ProximaCentauri"

So we can see it like this tree:
+ Universe
    + SolarSystem
         + Earth
         + Mars
    + AlphaCentauri
         + ProximaCentauri

***************

*Technical information if reporting a bug:*

- **ServicePulse version:1.20.4** 
- **ServiceControl version:3.8.3**

**Comment by DavidBoike** [comment]
Thanks @gkorobkov. I know others have requested exactly this as well. I'll mark it as a possible feature for a future release of Service Pulse.

**Comment by sergioc** [comment]
@gkorobkov we've just made [ServicePulse 1.27 available](https://github.com/Particular/ServicePulse/releases/tag/1.27.0) and added the ability to group endpoints. Have a look and feel free to let us know what you think.
