### ISSUE TITLE
Heartbeats when scaling up/down

### ISSUE THREAD

**Issue by pardahlman** [Particular/ServicePulse#778]
We're using ServicePulse with heartbeats for keeping track of our distributed system. We run several instances of the same logical endpoint with manually upscale/downscale. At times we run at double capacity and want to be able to observe heartbeats for all instances and be informed if any particular instance does not send a heartbeat. However, when we're at normal capacity, we don't want endpoints from the decommissioned/downscaled servers to show up as inactive endpoint.

I understand that you recommend setting Instance Id on the endpoints, but I don't see how that would help in this case. If this would solve my problem, feel free to elaborate 👍 

Other options that would make sense for us, is if you could provide an API to remove decommissioned endpoints - or perhaps even a group of endpoints based on there physical host.

**Comment by pardahlman** [comment]
A related issue is that in the Monitoring tab all endpoints that have had instances that has been decommissioned gets this symbol 
![bild](https://user-images.githubusercontent.com/1032755/64404288-b8b5fc80-d07b-11e9-9ee8-be90d23cebd7.png)

**Comment by dvdstelt** [comment]
Sorry, but at the moment we don't support this yet. We have it on our radar though.

We have another issue that contains the same problem which the appropriate groups already have on their radar. Would it be possible to subscribe to that issue, so if we update it you'll get notified? That way we don't have to track two issues.
The other issue is this one: https://github.com/Particular/ServicePulse/issues/756

**Comment by pardahlman** [comment]
Perfect, thanks!
