### ISSUE TITLE
Monitor dead letter queues

### ISSUE THREAD

**Issue by andreasohlund** [Particular/ServicePulse#8]
Moved from 

https://github.com/Particular/NServiceBus/issues/383

**Comment by cjoergensen** [comment]
@andreasohlund are you still considering doing this? I would a very helpful feature!

**Comment by andreasohlund** [comment]
No work is currently done here. The blocker is that we need to run as admin in order to read from the local DLQ's in msmq and we currently don't have anything that is running with those priviliges. 

What is the main driver for you @cjoergensen ? (retrying? just beeing aware of DLQ messages? other?)

**Comment by cjoergensen** [comment]
@andreasohlund Our main driver would be monitoring and retrying. Today we handle this by using QueueExplorer, but it is a tedious and error prone routine.

**Comment by andreasohlund** [comment]
Thanks @cjoergensen , that makes sense. Unfortunately since we don't have any "agents" running with admin rights on each machine means that we won't implement this in the near future :(

**Comment by cjoergensen** [comment]
@andreasohlund just a thought... Like the the HeartBeat plugin, could you have a "DLQAgent" plugin, that runs within the NServiceBus host and monitors the DLQ and reports back to ServiceControl? Given that the NServiceBus host runs with the proper privileges to access DLQ.

**Comment by andreasohlund** [comment]
>Given that the NServiceBus host runs with the proper privileges to access DLQ.

Unfortunately you need to have admin rights to read the DLQ's and the host should not run with those privileges. We would need to have a dedicated "agent" on each box to pull this off?

**Comment by WojcikMike** [comment]
This issue is connected with: Particular/PlatformDevelopment#810

**Comment by WilliamBZA** [comment]
We have an internal issue to prioritize and implement this. Given the size and current focus of shipping V6, we don't have any concrete plans on when this will be implemented, I'm going to close this issue. The internal platdev issue will ensure that this is issue not lost and will eventually be implemented once we have capacity again.
