### ISSUE TITLE
ServicePulse: should be able to group by also for archived messages

### ISSUE THREAD

**Issue by nikolaimaric** [Particular/ServicePulse#801]
It would be nice to be able to group archived messages is servicepulse in the same way that we can for failed messages. In other words, probably add an Archived Message Groups section.

**Comment by boblangley** [comment]
@nikolaimaric I am moving this issue to the relevant https://github.com/Particular/ServicePulse repository

Thank you for contributing this suggestion. We have noted it and placed it in our backlog. As you can imagine we can not always act immediately on requests like this, so we will update this issue when this status changes.

**Comment by pardahlman** [comment]
This is a huge pain point for us as well. Hope this get priority

**Comment by WilliamBZA** [comment]
This will be released on Monday in version 1.25.0 of ServicePulse.
