### ISSUE TITLE
How to build and run  ServicePluse project?

### ISSUE THREAD

**Issue by junbao520** [Particular/ServicePulse#805]
How to build and run  ServicePluse project?

**Comment by HEskandari** [comment]
@junbao520 Why do you want to run it from source? You can download it directly from [our website](https://particular.net/downloads), or from the [releases page](https://github.com/Particular/ServicePulse/releases).

**Comment by junbao520** [comment]
I want to learn your source code.


I have a question.
I can not open your raven db
Can you tell me how to open this db?





------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Hadi Eskandari"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月28日(星期四) 下午2:58
收件人:&nbsp;"Particular/ServicePulse"<ServicePulse@noreply.github.com&gt;;
抄送:&nbsp;"等待。情缘"<757114760@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [Particular/ServicePulse] How to build and run  ServicePluse project? (#805)




@junbao520 Why do you want to run it from source? You can download it directly from our website, or from the releases page.

**Comment by HEskandari** [comment]
Hi @junbao520 

The RavenDB is not in ServicePulse. You should not be messing with it unless you know what you are doing. If you have an issue, please open a support case with us, as advised above.
