### ISSUE TITLE
Change "Archive" to "Trash"

### ISSUE THREAD

**Issue by ramonsmits** [Particular/ServicePulse#806]
Feedback during a training.

Customer mentioned that 'Archive' isn't really the right term as after the age is older than the retention period it will be purged. Its better to use a different term to indicate that the data will eventually be lost like for example 'Trash'.

**Comment by seanfarmar** [comment]
@sergioc @timbussmann it looks like we use Archive every ware, not only buttons but also messages and tooltips.

Do we change all? Do we use "move to trash"? or "Delete"?

**Comment by sergioc** [comment]
Closed via https://github.com/Particular/ServicePulse/pull/951

**Comment by sergioc** [comment]
Done.
