### ISSUE TITLE
Clicking failed message on dashboard should navigate to message body

### ISSUE THREAD

**Issue by TraGicCode** [Particular/ServicePulse#812]
When click on a failed message on the dashboard

![image](https://user-images.githubusercontent.com/6224270/72536804-98275b80-3840-11ea-9873-167c15d5bce0.png)

You are taken to the failed message groups page.  This isn't very helpful and the expectation from a user is that you are taken to the message body to see the full message along with having an understanding of what endpoint caused the error message.

ServicePulse Version: 1.23.0

**Comment by WilliamBZA** [comment]
This will be fixed and released in version 1.25.0. Expect it in roughly 2 weeks.

**Comment by WilliamBZA** [comment]
Release is out! You can download [1.25.0](https://github.com/Particular/ServicePulse/releases/tag/1.25.0) and this should be done.
