### ISSUE TITLE
Filter the endpoints that are shown in the overview

### ISSUE THREAD

**Issue by frankwinfaber** [Particular/ServicePulse#830]
When using ServicePulse to monitor the Endpoints I would like to see the endpoints I am interested at once, without scrolling.

Can this be done with adding a filter in the URL? (e.g. https://servicepulse.domain.com/#/monitoring?filter=endpoint1+endpoint5+endpoint88)
If it can be implemented in this way I can make a shortcut to re-use the filter.

**Comment by indualagarsamy** [comment]
Thank you for raising this. I have let the team know. The team will prioritize the issue and will provide updates here when it's ready to be worked on. Thanks.

**Comment by dvdstelt** [comment]
@frankwinfaber Would the list always be the same? In other words, are there favorite endpoints that should always go on top and we can add a 'star' icon to endpoints to mark them as favorites?
Or is to to have different shortcuts in the browser to group certain endpoints?

**Comment by frankwinfaber** [comment]
Hi Dennis,

The list will be different for various usergroups. Idea is to be able to only see the endpoints for a certain domain ot application.
If it is possible to have different shortcuts it is easier to create a group once and share with team members.

With kind regards,

Frankwin

Van: Dennis van der Stelt<mailto:notifications@github.com>
Verzonden: maandag 23 maart 2020 08:58
Aan: Particular/ServicePulse<mailto:ServicePulse@noreply.github.com>
CC: Frankwin Faber<mailto:frankwin@live.nl>; Mention<mailto:mention@noreply.github.com>
Onderwerp: Re: [Particular/ServicePulse] Filter the endpoints that are shown in the overview (#830)


@frankwinfaber<https://github.com/frankwinfaber> Would the list always be the same? In other words, are there favorite endpoints that should always go on top and we can add a 'star' icon to endpoints to mark them as favorites?
Or is to to have different shortcuts in the browser to group certain endpoints?

**Comment by dvdstelt** [comment]
That makes sense. Thanks. We'll discuss this, but I can't say when this will be picked up. Thanks for reporting it though.

**Comment by sergioc** [comment]
@frankwinfaber we've just made [ServicePulse 1.27 available](https://github.com/Particular/ServicePulse/releases/tag/1.27.0) and added the ability to filter endpoints and bookmark the filtered view. Have a look and feel free to let us know what you think.
