### ISSUE TITLE
Ability to export message data

### ISSUE THREAD

**Issue by ramonsmits** [Particular/ServicePulse#850]
Having the ability to export a set of messages to XML, CSV or maybe Excel from with the user interface can be useful to pass on information to others for analysis.

**Comment by ASKyleGress** [comment]
I just wanted to upvote this issue. My management wants metrics for the activity in NServiceBus.

**Comment by boblangley** [comment]
@ASKyleGress thanks for the comment.

As an alternative, it is possible to send NServiceBus metrics data to other monitoring software.

We have samples showing how to do so with some popular software:

- DataDog: https://docs.particular.net/samples/logging/datadog/
- New Relic: https://docs.particular.net/samples/logging/new-relic/
- Prometheus with Grafana: https://docs.particular.net/samples/logging/prometheus-grafana/
- Azure Monitor Application Insights: https://docs.particular.net/samples/logging/application-insights/

If we add more samples they would be found here: https://docs.particular.net/samples/logging/

If you are already using another monitoring tool in your organization, it is possible to create your own implementation to interface with it:

https://docs.particular.net/monitoring/metrics/raw

**Comment by ramonsmits** [comment]
Ability to export to CSV is available in 1.30, <https://github.com/Particular/ServicePulse/releases/tag/1.30.0>
