### ISSUE TITLE
Combine the connection status icons with the version checks

### ISSUE THREAD

**Issue by WilliamBZA** [Particular/ServicePulse#885]
Currently we show the version check information separately from the connection status information. These 2 things can be combined into 1 to use less real-estate.

**Comment by WilliamBZA** [comment]
Combined status icons:

![image](https://user-images.githubusercontent.com/1060960/102470430-a5565700-405c-11eb-851a-138915a8e4d3.png)

**Comment by WilliamBZA** [comment]
And when not connected: 
![image](https://user-images.githubusercontent.com/1060960/102470482-b30bdc80-405c-11eb-9200-34058eb78a53.png)

**Comment by sergioc** [comment]
@WilliamBZA can you show the full footer, including also the SP version info with upgrade available link and how would that fit at 1440px? (minimum supported resolution)?

**Comment by WilliamBZA** [comment]
Good catch @sergioc, it was bad.

I've updated it to look like this at 1440px:

![image](https://user-images.githubusercontent.com/1060960/102494758-d4c98b80-407d-11eb-9fa9-dc9c913830a0.png)


And on larger screens:

![image](https://user-images.githubusercontent.com/1060960/102494787-e317a780-407d-11eb-86d5-befb7454e64f.png)

**Comment by sergioc** [comment]
👍 

Alright, only missing the SP version and upgrade link. Everything should center align in the footer too.

**Comment by WilliamBZA** [comment]
Disconnected state: 
![image](https://user-images.githubusercontent.com/1060960/102503712-aa310000-4088-11eb-9a20-e3b20646bf64.png)

Connected state:
![image](https://user-images.githubusercontent.com/1060960/102503743-b2893b00-4088-11eb-852f-daeff0ad5be2.png)
