### ISSUE TITLE
SSL cert invalid

### ISSUE THREAD

**Issue by markgould** [Particular/ServicePulse#908]
https://platformupdate.particular.net/servicepulse.txt

This results in ServicePulse not knowing when there are new versions (I noticed errors when looking at requests in Chrome devtools)

Results in an SSL error. Cert shows issued to s3.amazonaws.com

![image](https://user-images.githubusercontent.com/2712328/85607219-816c0880-b619-11ea-905d-247f4e51ed90.png)

**Comment by danielmarbach** [comment]
Hi @markgould we fixed it

https://platformupdate.particular.net/servicepulse.txt

Thanks for reporting
