### ISSUE TITLE
Add "Hosting Process" data to Heartbeats

### ISSUE THREAD

**Issue by johnsimons** [Particular/ServicePulse#94]
We need to display more host specific information to aid OPS to identify the endpoint in stress.

Things like:
- Exe patch
- Windows service name
- PID

**Comment by WilliamBZA** [comment]
I'm closing this as there is too much external system changes and coordination required before SP can be changed to display this information anywhere.

If this issue is still important and relevant, I suggest creating an issue under Platform Dev to coordinate the various repos involved.
