### ISSUE TITLE
Message Count on envelope on Monitoring page can get out of sync

### ISSUE THREAD

**Issue by eprod-edblakes** [Particular/ServicePulse#950]
- **ServicePulse version:** 1.25.4
- **ServiceControl version:** 4.11.0
- **Browser version:** N/A (issue seen in both Chrome and Edge)

The Failed Message Count envelope can get out of sync. See attached pictures. Observed that the count corrects when a new failed message is received.

The 4,323 messages were successfully archived as a group but the envelope count did not update.

![Failed Message Count 1](https://user-images.githubusercontent.com/9832128/96002040-4ecf6100-0dfe-11eb-8a33-7abca9287071.png)
![Failed Message Count 2](https://user-images.githubusercontent.com/9832128/96002057-51ca5180-0dfe-11eb-9740-e8005ceaf130.png)

**Comment by WilliamBZA** [comment]
Is it still out of sync @eprod-edblakes or did it sync eventually? These values come from different indexes so their update state is eventually consistent.

If it is still out of sync, it may be a bug.

**Comment by eprod-edblakes** [comment]
The value updated once a new message failed. It was out of sync up to then, which was many hours later.

**Comment by WilliamBZA** [comment]
Hmm. Would be willing to send your ServiceControl log files to support@particular.net? You can set the subject of the mail for attention to me.

**Comment by eprod-edblakes** [comment]
I'll have to ask since it is a production environment. Also, given our volume, the logs may have rolled off. Give me at least a week to get back to you.

**Comment by WilliamBZA** [comment]
Any news on the log files?

**Comment by WilliamBZA** [comment]
I'm going to close this, but if you're able to get the log files you can reopen this issue or send them through to the address above.
