### ISSUE TITLE
Unknown Message Type listed in Monitoring when multiple message types

### ISSUE THREAD

**Issue by feinoujc** [Particular/ServicePulse#970]
Similar to #604, I am seeing Unknown listed as the message type after upgrading to 1.27.0. However it looks like it shows unknown only if the message type has multiple message types listed via inheritance (the hover over icon shows this correctly)

![image](https://user-images.githubusercontent.com/1733707/96734316-6bccdc80-1388-11eb-9613-b71b151b6d8b.png)

***************

*Technical information if reporting a bug:*

- **ServicePulse version:1.27.0 
- **ServiceControl version:4.7.1
- **Browser version:Firefox latest

**Comment by timbussmann** [comment]
Hey @feinoujc , thanks for raising this. It seems this has been broken with the 1.27 release. We're working on fixing this, I'll update you on the progress.

**Comment by timbussmann** [comment]
Hey @feinoujc , we've just released ServicePulse 1.27.1 that should fix this issue. Can you update your version and let me know whether that resolves the issue?

**Comment by feinoujc** [comment]
@timbussmann done and it fixed it! thanks

**Comment by timbussmann** [comment]
glad to hear. Thanks for raising this 👍
