### ISSUE TITLE
Adding notes to failed messages

### ISSUE THREAD

**Issue by nikolaimaric** [Particular/ServicePulse#975]
It would sometimes be useful to add some freetext notes to a failed message in ServicePulse that is under investigation.

**Comment by adamralph** [comment]
Thanks for raising this @nikolaimaric. We'll take it into consideration for a future release.

**Comment by oskar** [comment]
I saw PR #1055 that was merged in May 2021 so I thought this feature would have been available now, but after upgrading to latest version of ServicePulse and ServiceControl I still cannot find any button to add/edit notes.

What is the status of this feature?

**Comment by andreasohlund** [comment]
@oskar the ability to add notes should be released and available in ServicePulse, what version of ServicePulse and ServiceControl are you using?

https://docs.particular.net/servicepulse/intro-failed-messages#failed-messages-page-failed-message-groups-tab-failed-groups-list-managing-failed-message-groups

**Comment by oskar** [comment]
We had just upgraded to ServicePulse 1.31.1 and ServiceControl 4.21.3 when I couldn't find the new feature. I asked around, and some of my colleagues could see the notes feature. After completely clearing my browser cache (Chrome, Win 10), I got the latest version as well. Some of my colleagues had to do the same, but some didn't.

I vaguely remember this behavior from an earlier release as well, where I couldn't see the new Events page in the header menu at first. Maybe there is a cache busting problem in ServicePulse?

But as for adding notes, I guess this issue can be closed as fixed now 😃

**Comment by andreasohlund** [comment]
@oskar how are you hosting ServicePulse? (using our host or in IIS)

**Comment by oskar** [comment]
In IIS

**Comment by andreasohlund** [comment]
Ah, that explains it IIS might be caching index.html a bit too heavy. Perhaps you can check if there is some setting that can be tweaked?

I'll close this issue as done for now
