### ISSUE TITLE
Microsft Defender SmartScreen blocks ServicePulse installer

### ISSUE THREAD

**Issue by antmeehan** [Particular/ServicePulse#995]
When I tried to install v1.28.0, on Windows 10 (10.0.18363.1256) I got the following prompt:

![image](https://user-images.githubusercontent.com/9822503/102085847-268dce00-3e52-11eb-879d-c22c2d8cb30f.png)

Have you seen any other instances of this happening?

**Comment by ramonsmits** [comment]
@antmeehan The files ARE signed correctly and it shows "NServiceBus Ltd" as the signee, but Microsoft needs to "build trust in" the certificate before not showing the warning. This involves some black magic Microsoft won't tell you, but one of the main inputs is to get users to override the warning and install the files.So for a period of time, our users will have to override that warning by clicking "Run Anyway" until our new certificate gets the thumbs up by Microsoft SmartScreen.

**Comment by antmeehan** [comment]
Wow what a painful process. Thanks for explaining. 👍
